### ISSUE TITLE
Image for background or on top next to name while in-app?

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#10]
It'd be great to have the IA logo (Brewster OK'd co-branding) or something relevant for the background.

If we can't figure out anything, I'm partial to NASA's photo of Sagan's Voyager Golden Record since I have no budget or skills to properly brand this project (yet): https://en.wikipedia.org/wiki/Voyager_Golden_Record

The idea for the project was to white-label it so anyone can integrate it into their apps/workflow, so making it easy for them to co-brand would be cool...Would love your thoughts on this!

**Comment by n8fr8** [comment]
I agree that less is more, and that we should more clearly state this is a client app for IA, and that OA is a collection inside of it. Will think about this some more. I may have some funds for our UX/UI designer as well to take a look. We can also talk with the SimplySecure.org team who are great and have general funding to help with efforts like this.
