### ISSUE TITLE
Missing sardine-android?

### ISSUE THREAD

**Issue by leophys** [OpenArchive/Save-app-android#100]
It seems that the guardianproject [fork](https://github.com/guardianproject/sardine-android) of `sardine-android` is needed in the project root.
It is missing as submodule.

**Comment by n8fr8** [comment]
Yes, we're in the midst of a sprint, and will be pushing that and cleaning it up.

**Comment by n8fr8** [comment]
(We had hoped our changes would be merged upstream into the main sardine-android project but we haven't been able to get that done yet)

**Comment by leophys** [comment]
Thanks! Feel free to close this issue whenever you want, then.
