### ISSUE TITLE
Batch editing in Preview screen

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#107]

**Comment by n8fr8** [comment]
progress https://github.com/OpenArchive/Save-app-android/releases/tag/0.2.2-beta-1

**Comment by foundscapes** [comment]
It is working on both Samsung Galaxy S7 and MotoG, however the edit and delete icons are way too hard to see. 
![BatchEditHardToSeeS7](https://user-images.githubusercontent.com/2231711/71022594-b10fe600-20b5-11ea-86e1-2384c845375d.jpg)

Can we make a multi edit icon like in ios in teal so it stands out before taking you to edit screen? Like this:

![BatchEditIosCorrect](https://user-images.githubusercontent.com/2231711/71022605-b66d3080-20b5-11ea-883e-9dbe1848b234.png)

**Comment by foundscapes** [comment]
Make all action buttons/text teal - solves all the problems
except metadata buttons!

**Comment by foundscapes** [comment]
0.2.2-beta-3 
This looks fine on all phones except moto-g OS 5.1 when in bulk edit screen
![motoGBulkEditHardtoSee](https://user-images.githubusercontent.com/2231711/71791553-471a9a80-2fea-11ea-994a-b5b4c4094051.png)

**Comment by n8fr8** [comment]
update the icons to be *actually* teal instead of using the tintMode

**Comment by roseregina** [comment]
Save 0.2.2-beta-7
motoG, GalaxyS7, Pixel3a

Icons are teal. It looks nice and icons are easily visible (including when screenshot was converted to b&w to check if the green on grey might be tricky with colorblindness). 
![image](https://user-images.githubusercontent.com/15040203/72223442-9d746580-3523-11ea-8ce0-03cd8a28c14f.png)
