### ISSUE TITLE
add more debug info when upload fails

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#108]

**Comment by johnhess** [comment]
This might be under specified @tladesignz, but take your best shot at it.  It would also be helpful to have debug information for uploads which succeed.

I noticed some wonky behavior around uploads.  Some of that behavior might be in the application's presentation layer, but especially as we talk less-straightforward upload paths (Tor, IPFS, chunked uploads, flakey/changing networks) it'd be nice to have clear logging.

**Comment by tladesignz** [comment]
"might" is quite the understatement, @johnhess. 🤣

Happy to fill in some gaps, but this definitely needs some explanation before I can start implementing anything.

Questions:

- Add more debug info to what? 
  - A log?
  - CleanInsights?
- If log, where should this log reside? 
  - In the app database? 
  - In the app filesystem? 
  - In the user-accessible part of the file system? 
  - In RAM?
  - On a server?
- Who will want to read this log? The user? Somebody else?
- By which means shall these persons be able to acquire that log? 
  - Does the user send in emails? 
  - Should the app send the log to some server? 
  - Automatically? 
  - On demand by the user? 
  - What sink would that be?
    - A ticketing system?
    - Github?
    - Something else? 
- What value should this log provide?
  - Should the user be able to better understand, what went wrong?
  - Or some support personnel? Who would that be?
  - Or the devs?
- What's the impact of these wishes on the user privacy and the promises we give to them?

**Comment by johnhess** [comment]
I trust your judgment too as to what's worthwhile and what's not worth the effort.

I'd like to have a 

* local-to-device log that we can use for both debugging/replicating (not sure to what degree we have it now)
* way for a user to get more information on their failing upload that they could optionally share with us [nice to have].    
  * No need to have an automated reporting mechanism/sink for them today.
  * Ideally the user should get some kind of indication of what's gone wrong.  Again, nice to have.
  * I'd settle for any error message, but the more informative, the better.
* I'm not an Android dev, so I would trust your judgment on where to write the log to.  My naive assumption is it would be the log stream I get when I plug my phone in to the Android Studio debugger.
* The value of the log is mostly for developers and, if it's not too hard to surface, to a user when/if they could do something about it.  Without knowing which failure modes are actually user-fixable and how common they are, the value of the user-facing info is speculative.
* I'd like to see everything stay on-device and any data written to an untrusted/un-deleteable log stream should be minimized.  If you look at it and see a threat (e.g. logging creates an indelible mark that you've uploaded then deleted content from your phone to $my_private_server), then let's limit that radioactive logging to a debug build.

**Comment by tladesignz** [comment]
As talked on the meeting, I'll first do #268 and then revisit this with the knowledge of my findings.

**Comment by hiromipaw** [comment]
Closing for now.
