### ISSUE TITLE
Homescreen? latest image persists when closing/opening the app

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#11]
I thought it would take me to the home screen when I closed and then re-opened the app, but it just shows the list of uploads we've done, which seems a bit confusing. Is there a way to have them save somewhere and have a homescreen, or do you not think a homescreen is necessary?

**Comment by n8fr8** [comment]
I don't think a homescreen is necessary, especially with the new floating action button that has all of the import/capture options.

We should take people either right into their own content, or potentially, into the latest content from the openarchive or a search. This is the instagram style flow that I completely agree with.

**Comment by foundscapes** [comment]
Agreed. It'd be great, ultimately, to take them to the latest OA content/search!
