### ISSUE TITLE
Browse project is not working

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#111]
Browse Project is not clickable on Android device.

**Comment by purvi-ranawat** [comment]
The app crashes when we click on Browse Projects. Tested on Samsung galaxy A70

**Comment by n8fr8** [comment]
Here's a new build to test: https://github.com/OpenArchive/openarchive-android/releases/tag/0.2.1-alpha-1

Please try on a few different Android variants if possible

**Comment by n8fr8** [comment]
(we are up to version 0.2.1 but back to 'alpha' state since we are adding new features)

**Comment by purvi-ranawat** [comment]
It works fine now for app version 0.2.1. Tested on Samsung galaxy A70, Samsung Galaxy J7, and Mi Note 3
