### ISSUE TITLE
Media is not getting uploaded

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#112]
I have created new project on Android device and tried to upload image (82 kb), it shows Ready to Upload and Next button. When I clicked on Next the image enlarged with upload symbol at top right. When clicked on upload symbol it took me back to the Ready to upload screen.

Tested on Samsung Galaxy a70 with Android version 9

**Comment by n8fr8** [comment]
Were you ever able to get media to upload?

**Comment by purvi-ranawat** [comment]
@n8fr8 : I was not able to upload any media yet on android device. I have uninstalled and installed the app again on my android device but still its not working

**Comment by purvi-ranawat** [comment]
@n8fr8 I'm able to upload the media on app version 0.2.1
