### ISSUE TITLE
[Android] : Camera icon is not displayed when we click on upload button to select the photos from camera

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#114]
When we click on upload button under the project, All Media Gallery is displayed on Android 9.0 where we can select the media. But Camera icon is not there to directly take the photos / videos from the camera and uploading them

Below is the screenshot :

![No camera icon](https://user-images.githubusercontent.com/8190141/61919399-1e8a7100-af73-11e9-9712-7f8579fd1f1f.jpg)

Note : This is working fine in IOS

**Comment by foundscapes** [comment]
@purvi-ranawat this is no longer a feature for either android or ios

**Comment by purvi-ranawat** [comment]
Hi Natalie,

But currently in IOS , test flight build # 35, I am able to see the camera icon when I go to select the photos from cam roll.

So, shall I open that issue in IOS?

**Comment by foundscapes** [comment]
Hi Purvi,

Thank you for finding this, I will check in with Benjamin and @n8fr8 - I believe we decided not to have this feature, but we are still able to take photos in ios to use in the app.

**Comment by purvi-ranawat** [comment]
@n8fr8 Camera icon is available on iOS not available on Android.

**Comment by n8fr8** [comment]
That's fine. It only exists on Android, as it is part of the default gallery UI.

**Comment by foundscapes** [comment]
@n8fr8 how can we use proofmode if we don't have in-app capture? This feature should map to iOS and is good/needed.

**Comment by n8fr8** [comment]
We use proofmode by signing media when we import it into SAVE. 

We made a decision that SAVE was not going to be a capture app. The only reason it is on iOS is that the system standard media picker has a camera option. The Android one doesn't.

Again, we can for third-party libraries and spend our time on UI tweaks like this, but there is a cost.

**Comment by foundscapes** [comment]
That's good to hear that it works without capture, hopefully we can fix the proofmode bug asap that crashes when trying to upload media with it on - #153. 

I know we decided that, but it's in iOS, so perhaps we need remove it from there to be consistent. I am aware of the cost, I am adding bare minimum UI tweaks, omitting many other designs at the moment to get this out of beta. This should be a feature that org's can hire us/or someone to add if needed.
