### ISSUE TITLE
Significant Content-Flag option is missing for media on preview screen.

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#115]
On preview screen only Description, Location, and Tag options are displayed. Flag or Significant content option is not getting displayed.

![Screenshot_20190726-220043_SAVE (1)](https://user-images.githubusercontent.com/8190141/61967026-eece7e00-aff1-11e9-9300-0b59c2a2c3ab.jpg)

**Comment by purvi-ranawat** [comment]
@n8fr8 Significant content flag disappears after the image is uploaded if we have selected Significant content,.
App version 0.2.1 tested on Samsung Galaxy a0 android 9

![Screenshot_20191005-130913_SAVE](https://user-images.githubusercontent.com/8190141/66251799-c1c8e500-e771-11e9-8c3a-5e577d55b44e.jpg)

**Comment by n8fr8** [comment]
fixed in next build
