### ISSUE TITLE
Does not allow to select photos and videos together for uploading 

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#116]
When we select photo and video together from All Media it displays the message "Can't select videos and images at the same time"

Tested on Samsung Galaxy A70 Android version 9.

![Screenshot_20190726-222854_SAVE (1)](https://user-images.githubusercontent.com/8190141/61968415-97caa800-aff5-11e9-9b8b-5546c9896587.jpg)

**Comment by n8fr8** [comment]
won't fix

**Comment by foundscapes** [comment]
reproduced on Moto E running Android 7.1.1
this is a big UI issue/commonly-used feature for mvp, why can't we fix it?

**Comment by n8fr8** [comment]
We have to fork the image picker library we are using. Right now, we are just using it off the shelf. The more custom UI work we do, the less time we have for reliable large uploads, tor integration, DAT support, etc.

**Comment by foundscapes** [comment]
We need to prioritize UI mapping to iOS over DAT and below consistent/reliable uploading.

**Comment by foundscapes** [comment]
Can now capture photos in-app but not videos

**Comment by foundscapes** [comment]
0.2.2-beta-3 
works on s7, 3a, and moto-g @n8fr8
