### ISSUE TITLE
Distance between project names is too long

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#118]
On top navigation distance between project names is too long .

Tested on Samsung galaxy A70 Android 9

![Screenshot_20190727-153919_SAVE](https://user-images.githubusercontent.com/8190141/61993279-e411f880-b086-11e9-88f5-d279d59f211a.jpg)

**Comment by n8fr8** [comment]
on Android we want to support the standard viewpager, swipeable model. This is different than on iOS.
