### ISSUE TITLE
Three fonts on the initial homescreen

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#12]
I can't get back to it now that I've been playing with the app, but if you look at the fonts on the homepage when you first log in, you'll notice they're all different, as well as different sizes.

**Comment by n8fr8** [comment]
Yes, going to clean this up and simplify it. From now on the home screen will be the signup/login screen only as well, since it is only needed then.

**Comment by n8fr8** [comment]
Here is the updated home screen. Plain and simple for now. I think OpenArchive should have its own icon or logo of some sort other than the IA one, but I hope the subtitle also helps with that.

![device-2016-05-16-142820](https://cloud.githubusercontent.com/assets/30851/15299465/82cd0a62-1b72-11e6-8492-4394e166445b.png)

**Comment by foundscapes** [comment]
Looks great! Love the virtual library card addition.

**Comment by n8fr8** [comment]
The "virtual library card" text is straight from the archive.org home page. Right now, OA basically is equal to IA in terms of how you login and authenticate etc. At some point in the future, could be good to reconsider that. In addition, as I mentioned, you probably shouldn't have to actually login/signup for IA until you want to publish.
