### ISSUE TITLE
Able to create project name with only special characters

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#121]
Steps to Reproduce :

1. Launch Save App in Android
2. Click on Create new project
3. Enter only special characters in the project name
4. Click on Add

Expected Result ;
 Pop up error message should be displayed stating that special characters not allowed in project name

Actual Result : 
No error message is displayed stating that special characters not allowed in project name. Instead project is created with only special characters as the project name

Below is the screenshot : 
![Screenshot_20190727-210932_SAVE](https://user-images.githubusercontent.com/8190141/61996798-433b3180-b0b6-11e9-96fa-1869321fe172.jpg)

**Comment by n8fr8** [comment]
I think the only invalid chars are / and \
