### ISSUE TITLE
Localize Android 

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#123]

**Comment by foundscapes** [comment]
With Localization Lab

**Comment by comradekingu** [comment]
Please use Weblate.

**Comment by n8fr8** [comment]
pull/integrate with the strings from Save for iOS

**Comment by tladesignz** [comment]
This was handled sometime in the last years and just recently fixed and brought up to speed. See #419

**Comment by foundscapes** [comment]
great, closing now!
