### ISSUE TITLE
Cancel and Remove media buttons are missing on Remove media pop up

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#132]
When we try to delete any media from the project the pop up for Remove media for confirmation is displayed. However the content like Remove Media and Cancel links are missing on the pop up.

![Screenshot_20191005-133850_SAVE](https://user-images.githubusercontent.com/8190141/66264323-c8626580-e820-11e9-98ad-a4e0b646ff11.jpg)

**Comment by n8fr8** [comment]
I think they are there, but the color scheme is making them invisible!
