### ISSUE TITLE
App crashes when we click on the photo, select it and then click on Add

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#134]
Steps to Reproduce :

1. Open Save App on Android
2. In the project, click on the "+" icon to select the media
3. Click on any media
4. After the media is opened, select the media and click on Add

Expected Result  : 
After click on Add, next screen which asks to upload the media is displayed

Actual Result : 
For the first time, it is working fine. But on the second try, on clicking on Add, the app crashes. This is happening only when we click on the media, (preview of media is displayed), then select the media and click on Add

**Comment by n8fr8** [comment]
cannot repro. please try again on next build.

**Comment by purvi-ranawat** [comment]
It works fine now.
