### ISSUE TITLE
Profile image for the cloud instance is not displayed

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#135]
When we enter the server details and save the connect, the server instance image should be displayed as the profile image. It is working fine in IOS, but in Android, profile image of the cloud instance is not displayed

Below is the screenshot :
![profile image](https://user-images.githubusercontent.com/8190141/66586513-584c3a80-eba6-11e9-8f70-2f75dec0a301.jpg)

**Comment by n8fr8** [comment]
Should work different and better now

**Comment by foundscapes** [comment]
I see a G on motoG!

**Comment by purvi-ranawat** [comment]
@n8fr8 The first letter of server name is getting displayed as profile logo.
