### ISSUE TITLE
App crashes when we try to upload more than 30 photos at once

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#136]
In the project, when we try to select more than 30 photos and click on Add , Save app crashes.

**Comment by n8fr8** [comment]
Are you able to capture a crash log or adb output?

**Comment by n8fr8** [comment]
also is it consistently 30?

**Comment by purvi-ranawat** [comment]
@n8fr8  : Yes. it is consistently after 30. Once the app crashes and I reopen the app, at that time, even if I select one or two photos also, the app crashes. I have fully close the app, wait for some time and then open the app and then only able to add the photos again

**Comment by purvi-ranawat** [comment]
I will try to get the crash log

**Comment by n8fr8** [comment]
just tested 32 files with the latest build and no crash. Please test again once posted. If it does crash, we need to get crash logs somehow.

**Comment by purvi-ranawat** [comment]
@n8fr8 : The issue is working fine with Samsung Galaxy A70 - Android 9 but when I tried the same with Samsung Galaxy J7 - Android 6, the app crashes.

I have attached the log for the same

[bugreport.zip](https://github.com/OpenArchive/Save-app-android/files/3869460/bugreport.zip)

**Comment by purvi-ranawat** [comment]
@n8fr8 It works fine now.
