### ISSUE TITLE
Able to create the project with duplicate name

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#138]
I am able to create the project with the duplicate name.

Below is the screenshot : 

![duplicate name](https://user-images.githubusercontent.com/8190141/66836672-68d22b80-ef7f-11e9-86a1-c6b1cd297ad6.jpg)

**Comment by foundscapes** [comment]
I recreated this issue on my 2015 motoG

**Comment by purvi-ranawat** [comment]
@n8fr8 It works fine, tested on Samsung galaxy J7 and Samsung A70

**Comment by foundscapes** [comment]
While I'm unable to create two folders with the same name, I do see two with the same name (oademo) in the app (apk 0.2.1-beta-6) although only one folder is on the server.
![twoFolders](https://user-images.githubusercontent.com/2231711/70184202-3bab1b00-169c-11ea-8d11-b3a584a11d39.png)
@n8fr8
