### ISSUE TITLE
App crashes after installation of new beta - 2 build

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#140]
After installing the "OpenArchive Android 0.2.1-beta-2" build , when I try to open the Save App, App crashes and closes down.

I have try on Samsung Galaxy A70 and Samsung J7 devices.

**Comment by n8fr8** [comment]
https://github.com/OpenArchive/openarchive-android/releases/tag/0.2.1-beta-3

**Comment by purvi-ranawat** [comment]
@n8fr8 : New Build is working fine. Save App opens fine on beta-3 build
