### ISSUE TITLE
App crashes when we do not enter the optional server name while setting up the server

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#141]
On the Login screen, when we do not enter Server name which is optional and enter all the valid mandatory details , the app crashes. When we enter Server name also, then we are able to login successfully to the server.

This is happening on Samsung Galaxy A70 and Samsung J7

Below is the screenshot of the Login screen :

![login screen](https://user-images.githubusercontent.com/8190141/66940592-d99e4400-f062-11e9-9080-7f89c8bbc2c3.jpg)

**Comment by foundscapes** [comment]
reproduced on Moto E running Android 7.1.1 - had to reinstall app to get it to work

**Comment by purvi-ranawat** [comment]
@n8fr8 : This is working fine now on Samsung Galaxy J7 - Android 6 and Samsung Galaxy A70 - Galaxy 9

**Comment by foundscapes** [comment]
@n8fr8 works on Google Pixel 3a /Android 10 as well
