### ISSUE TITLE
Welcome screens' text hidden behind images

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#142]
MotoG
OS: Android 5.1

![Screenshot_2019-10-16-21-40-12](https://user-images.githubusercontent.com/2231711/66978547-3992eb80-f05f-11e9-8b69-123a5d7f41ed.png)
![Screenshot_2019-10-16-21-40-08](https://user-images.githubusercontent.com/2231711/66978548-3992eb80-f05f-11e9-9822-69859afeea88.png)
![Screenshot_2019-10-16-21-40-19](https://user-images.githubusercontent.com/2231711/66978549-3a2b8200-f05f-11e9-9a76-23ade022d609.png)

**Comment by n8fr8** [comment]
Oh, that's an old device. Hmm. I guess we need to resize the graphics for the smaller screen. Good find!

**Comment by n8fr8** [comment]
@purvi-ranawat do you have a smaller screen device to do UI testing on?

**Comment by foundscapes** [comment]
@n8fr8 this is also happening on the Samsung Galaxy S7 from 2016 for one of our new users

Phone: Galaxy s7
OS: v. 8.0.0

![IMG_2F86D9735872-1](https://user-images.githubusercontent.com/2231711/67513563-fb1ab380-f692-11e9-9426-2ebad97f7504.jpeg)
![IMG_3CF5EA9F190E-1](https://user-images.githubusercontent.com/2231711/67513564-fb1ab380-f692-11e9-8a9d-4aefbb43ed3e.jpeg)
![IMG_3D2A5F241BC8-1](https://user-images.githubusercontent.com/2231711/67513565-fb1ab380-f692-11e9-9026-ddc8fae9e1a8.jpeg)
![IMG_80B8C426BED9-1](https://user-images.githubusercontent.com/2231711/67513566-fbb34a00-f692-11e9-8dfb-5ff7a846b860.jpeg)

**Comment by foundscapes** [comment]
reproduced on Moto E running Android 7.1.1

**Comment by purvi-ranawat** [comment]
@n8fr8 This is working fine on Samsung galaxy J7 Android 6 and Samsung a70 Android 9

**Comment by foundscapes** [comment]
@n8fr8 working on MotoG Android 5.1
![LangViewable](https://user-images.githubusercontent.com/2231711/70197722-9efb7400-16c1-11ea-88b5-a115ed838ad0.png)
![Langviewable1](https://user-images.githubusercontent.com/2231711/70197723-9efb7400-16c1-11ea-9d97-a9cff66add7f.png)
![LangViewable2](https://user-images.githubusercontent.com/2231711/70197724-9efb7400-16c1-11ea-9e83-df3555f17647.png)
