### ISSUE TITLE
Upload Status Circles go from 0-100% with no progress + No upload/second indicator

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#143]
MotoG
OS: Android 5.1

![Screenshot_2019-10-16-21-43-51](https://user-images.githubusercontent.com/2231711/66978650-9b535580-f05f-11e9-9c2c-341b3161569f.png)

**Comment by n8fr8** [comment]
With small files, sometimes the upload is so quick, it just shoots from 0 to 100. To do a callback for a UI animation for every tiny increment adds a lot of load on the UI, so we do it at certain time intervals, and if the upload happens in that time interval, then you see it go from 0 to 100.

Still, will take a look to see how to optimize for this better. You can also enable Nextcloud Chunking feature in Settings and see if that works better.

**Comment by foundscapes** [comment]
Ok....I'll do again with chunking and larger video files.

so we're not going to implement the x mb/s uploaded of / x total?

**Comment by n8fr8** [comment]
More granularity in progress display has been implemented/solved.

More to come to show progress of file data transfered

**Comment by purvi-ranawat** [comment]
@n8fr8 : Currently its becoming 0 to 100% directly and not showing any progress. Just for a micro second, it is showing some other numbers which are not readable

**Comment by n8fr8** [comment]
Was that with web-dav or archive.org uploading?

**Comment by foundscapes** [comment]
Phone: Google Pixel 3a
OS: Android 10
Server: GoodCloud
It's working for GoodCloud

![uploadprogress3a](https://user-images.githubusercontent.com/2231711/70187277-a19aa100-16a2-11ea-8166-d302f70298d8.png)

Phone: Google Pixel 3a
OS: Android 10
Server: Internet Archive
It's working for IA

![IAUploads](https://user-images.githubusercontent.com/2231711/70187577-6c428300-16a3-11ea-818c-83ad1a197085.png)

However, when I added more files they went so fast it was 0-100% very quickly, but they were smaller (kb) files, so hopefully that's the only reason?

**Comment by n8fr8** [comment]
yes
