### ISSUE TITLE
+ to add project too far to the left

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#144]
MotoG
OS: Android 5.1

It gets lost, when I try to tap it, when I try to see the "add a project" text, it takes me to the add a project page before I can read all the text/know what to do.

![Screenshot_2019-10-16-21-41-56](https://user-images.githubusercontent.com/2231711/66978681-c2aa2280-f05f-11e9-8ab8-969338814c4e.png)

**Comment by n8fr8** [comment]
Going to have to think about this. The way the UI was designed on iOS doesn't match the Android UI expectations. That said, if you swipe to the left instead of trying to tap on the + it is meant to just open the expected screen, as if you tapped the +. The text that is displayed is really just a fallback and not needed at all, but I see how you get confused by seeing a glimpse of it.

**Comment by foundscapes** [comment]
Perhaps then we need a left arrow with language to add a project to make more clear? If not, we definitely need another indicator or to remove the swipe entirely and move the clickable + over to the right and make it larger w/ more white space (which we need to do anyway)

**Comment by foundscapes** [comment]
reproduced on Moto E running Android 7.1.1

**Comment by n8fr8** [comment]
if you tap the + when it is the selected tab, open the add project screen

**Comment by roseregina** [comment]
Save 0.2.2-beta-7
motoG, GalaxyS7, Pixel3a (compared again iOS) 

As of this release, the (+) is still part of the main sideways scroll bar in android, but is fixed while the rest of the tabs (project folder names) scroll. 

Android: 
![image](https://user-images.githubusercontent.com/15040203/72223144-d101c080-3520-11ea-8d4b-c7422b9fee4f.png)

iOS: 
![image](https://user-images.githubusercontent.com/15040203/72223159-ed056200-3520-11ea-93e7-332098e201ac.png)

**Comment by n8fr8** [comment]
This is the best we can do on android
