### ISSUE TITLE
App crashes when we enter both Private server and Internet Archive credentials and then try to upload the media

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#145]
Steps to Reproduce : 

1. Open Save App
2. Enter Private Server credentials to connect to the Private Server
3. Enter Internet Archive credentials to connect to archive.org
4. Select Internet Archive and create the project
5. Click on + icon to add the media and select the media

Expected Result : 
On clicking on Add for the media, preview for the media should be displayed along with the Upload option

Actual Result : 
On clicking on Add for the media, app crashes. This is happening only when we have entered both Private Server and Internet Archive credentials. When I have entered only Internet archive credentials or Private Server credentials individually, it is working fine

This is happening on both Samsung Galaxy A70 and Samsung J7

**Comment by foundscapes** [comment]
reproduced on Moto E running Android 7.1.1:

Same problem when uploading to IA after logging into both webdav and IA trying to upload media - it crashed twice when uploading to IA, then reopened app and it uploaded. BUT, there were two other phantom uploads that were not selected as well to IA (screenshot 1)
![phatommediaIA](https://user-images.githubusercontent.com/2231711/68673626-2cfc9880-0522-11ea-90e9-7d7c65b46c47.png)


This also happened when I tried uploading to webdav goodcloud with IA logged in - app crashed twice, then nothing uploaded, and number in circle said "2" when there were 4 images also there were 2 phantom images were in queue (screenshot 3)
![PhantomMediaWebDav](https://user-images.githubusercontent.com/2231711/68673751-751bbb00-0522-11ea-85ed-3d7a3acd847e.png)

**Comment by foundscapes** [comment]
It also crashed 5 times and counting when uploading to webdav after I disconnected from IA

**Comment by n8fr8** [comment]
The next build has progress in crashing generally, and I can no longer reproduce this problem.

**Comment by purvi-ranawat** [comment]
@n8fr8 : This is working fine now. App is not crashing on uploading now when we have both IA and private server configured. 

Tried on Samsung Galaxy J7 - Android 6 and Samsung Galaxy A70 - Android 9.0

**Comment by foundscapes** [comment]
Works on Pixel 3a, Android v.10
