### ISSUE TITLE
Media is directly getting uploaded without creating the project on Internet Archive

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#146]
Steps to Reproduce :

1. Launch Save app and create the internet archive
2. Create the project on Internet archive
3. Add the media to the project
4. Access Internet Archive (archive.org) and verify the uploads on internet archive

Expected Result : 
Folder should be created on archive.org and media should under the same folder (project)

Actual Result : 
Media is uploaded on archive.org but no folder (project) is created. They are getting directly uploaded.

Also, because project is not created on archive.org, when we browse existing projects on save app, nothing is displayed

**Comment by n8fr8** [comment]
There is no concept of "project" on archive.org. I need to see what SAVE for iOS does in this case. What is your expectation based on testing iOS?

**Comment by foundscapes** [comment]
@n8fr8 and Benjamin should discuss how to map from ios to Android - may be beyond our scope

**Comment by foundscapes** [comment]
@purvi-ranawat is this still an issue?

**Comment by purvi-ranawat** [comment]
@foundscapes  : This is working same as IOS. So, closing the issue
