### ISSUE TITLE
Arrow on welcome screen is white on white

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#147]
Phone: Samsung Galaxy S7
OS: version 8.0.0

Progress arrow is white, should be teal
![IMG_A713938E8FB4-1](https://user-images.githubusercontent.com/2231711/67513780-74b2a180-f693-11e9-96b2-d27c9ed29872.jpeg)

**Comment by n8fr8** [comment]
the arrow is fixed, but still need to match the image graphics from iOS

**Comment by purvi-ranawat** [comment]
@n8fr8 Arrow and even dots in the center are white on white and not visible clearly. Tested on Samsung J7 Android 6.0.1 and Samsung A70 Android version 9

![Screenshot_20191119-191204_SAVE](https://user-images.githubusercontent.com/8190141/69151574-e1895200-0b00-11ea-8c5b-31e8ae9c46e3.jpg)

**Comment by n8fr8** [comment]
well "get started" is visible. that is what we want people to tap. what happens on the next screen?

**Comment by purvi-ranawat** [comment]
@n8fr8 : On the next screen, it is working fine. Arrows and dots are not of white color from next screen onwards

**Comment by foundscapes** [comment]
Phone: Moto G
OS: 5.1

New color not visible, same white on white issue with arrow
![WhiteArrowOnWhite](https://user-images.githubusercontent.com/2231711/70198099-b1c27880-16c2-11ea-89df-9fc02b123afe.png)

**Comment by foundscapes** [comment]
phone: motoG
OS: Android 5.1
Save 0.2.2 Beta-2

Still white on white arrow, this needs to be fixed asap since it's the first screen - Let's make it teal

![whitearrowonwhite](https://user-images.githubusercontent.com/2231711/70765375-7a317d00-1d0f-11ea-895c-7bd9d2646690.png)

**Comment by foundscapes** [comment]
Since it's clear on Google Pixel 3a, can we make sure it looks like this on all devices?

![GetStartedPixel3a](https://user-images.githubusercontent.com/2231711/71024719-6a70ba80-20ba-11ea-89cd-1e1ca3e0805e.png)

**Comment by n8fr8** [comment]
Ensure smaller screens is not using the wrong /  different layout

**Comment by foundscapes** [comment]
MUCH BETTER w. turquoise bar at bottom
