### ISSUE TITLE
end to end encryption

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#148]
Let's discuss / scope this

**Comment by n8fr8** [comment]
Options:

- OpenPGP
- Encrypted Messenger Integration (Signal, Matrix, Telegram)
- ?

**Comment by foundscapes** [comment]
Encrypted Messenger Integration!

**Comment by foundscapes** [comment]
Need to write documentation for how to make it end to end encrypted if people want, since it's possible to capture media in-app and pw-protect app / ephemeral/disappearing media - effects performance / ux when using these.

**Comment by foundscapes** [comment]
@hiromipaw this will be happening under next funding cycle 2024/2025

**Comment by hiromipaw** [comment]
I'd like to close this issue for now. We can reopen multiple issue when the time comes during the app hardening.
