### ISSUE TITLE
Add Project + should float in the circle with. more white space, unclear it's a + / add

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#149]
Device: Moto E4
OS: Android 7.1.1

more UI to change / make more like iOS - related - #144

**Comment by foundscapes** [comment]
Device: Google Pixel 3a
OS: Android 10

Still too small / closed circle too tight and too far to the left in project/folder view

![tooLeft](https://user-images.githubusercontent.com/2231711/70186404-b9712580-16a0-11ea-9d44-df796a3cee1a.png)

![toosmall](https://user-images.githubusercontent.com/2231711/70186438-cbeb5f00-16a0-11ea-9fd0-35d5c0ef56ff.png)

**Comment by foundscapes** [comment]
It's still too small on all android devices using Beta-2 - no one knows what it is. Can you make it larger like in iOS?

![iosPlusSignAddProject](https://user-images.githubusercontent.com/2231711/71023923-a30f9480-20b8-11ea-8d83-f7d1865e3e3b.png)

**Comment by n8fr8** [comment]
use the same "Add Space" floating cross in circle drawable bitmap

**Comment by foundscapes** [comment]
It's working better, but only looks ok on larger screens
