### ISSUE TITLE
Last edit for "About" page grammar

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#15]
The last paragraph should read:

OpenArchive was developed in partnership with the Internet Archive, StoryMaker, and Scal.io with generous support from the Knight Foundation.

**Comment by n8fr8** [comment]
okay. somehow the about string got mixed up a bit and didn't make it in the last update, but will fix it all now.

**Comment by foundscapes** [comment]
Awesome, I think my trying to block out the new content w/ ___'s ended up messing up the way it looked on GH too. Thank you!
