### ISSUE TITLE
GoodCloud Logo cut off in upper right

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#150]
Device: Moto E4
OS: Android 7.1.1

![upperGcutoff](https://user-images.githubusercontent.com/2231711/68674789-8a91e480-0524-11ea-9294-7ad0618fbd6f.png)

**Comment by foundscapes** [comment]
@n8fr8 
Google Pixel 3a
Android 10
this seems fixed on 3a, but the logo should be slightly lower from top / looks crunched
![LogoTooHigh](https://user-images.githubusercontent.com/2231711/70184974-ca6c6780-169d-11ea-9e54-879112f6ea1a.png)

**Comment by foundscapes** [comment]
Logo is still cut off on the moto G os: Android 5.1
![LogoCutOffMotoG](https://user-images.githubusercontent.com/2231711/70198412-a91e7200-16c3-11ea-8c2f-6edf3c02a846.png)

**Comment by foundscapes** [comment]
and still after 2.2 beta 1

**Comment by n8fr8** [comment]
This wasn't marked "please test"

**Comment by roseregina** [comment]
I think this is as good as we're getting in terms of a compromise between visibility/ font size and aesthetics as we are getting. Circle is not longer cut off and I can read the letter, so I am inclined to think this is resolved: 
![image](https://user-images.githubusercontent.com/15040203/79293334-1673b800-7e99-11ea-8136-d3f747be49f9.png)


And here it is on the GalaxyS7, showing that it still looks good on the larger screen. 
![image](https://user-images.githubusercontent.com/15040203/79293219-be3cb600-7e98-11ea-92a5-353bd54bdcf7.png)
