### ISSUE TITLE
allow "view password" option for server login

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#151]
in case of incorrect password - not pressing

**Comment by foundscapes** [comment]
Device: Moto E4
OS: Android 7.1.1

**Comment by foundscapes** [comment]
Like this so people can click no it to see the pw

![image](https://user-images.githubusercontent.com/2231711/71020479-45c41500-20b1-11ea-9936-a3f6d3d556ef.png)

**Comment by surender786** [comment]
Hello @foundscapes I am an outreachy-21.I want to contribute to openarchive projects. Please elaborate the what work I do for contributing to the projects. I am newbie
Also add me in #OpenArchive-Outreach slack channel. 
My mail surendernawalrai11@gmail.com

**Comment by foundscapes** [comment]
this is fixed in ios, @hiromipaw can you confirm it's enabled in android too?

**Comment by hiromipaw** [comment]
@purvi-ranawat can we check this is working as expected?

**Comment by purvi-ranawat** [comment]
@hiromipaw : This is working as expected now. I have entered wrong password and then clicked the eye icon. I am able to see the password.

OS : Android 11, Android 13
Device : Samsung A70, Samsung A13
Build : 0.3.0-alpha5
