### ISSUE TITLE
App crashes when proofmode enabled

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#153]
Device: Moto E4
OS: Android 7.1.1

1. enabled proofmode in app settings / data usage
2. went to active project
3. selected a photo
4. hit add(1) in lower right
5. app crashed
6. reopened app
7. deselected proofmode
8. went to active project
9. selected a photo
10. hit add(1) in lower right
11. app crashed
12. had to reinstall app

**Comment by n8fr8** [comment]
Updated proofmode library, no more crashing

**Comment by purvi-ranawat** [comment]
@n8fr8 It works fine on Samsung galaxy a70 Android 9 and Samsung J7 android 6
