### ISSUE TITLE
Change "Create a new project" to "Add Project" or map to iOS UI on first screen after connecting to server

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#154]
Device: Moto E 
OS: Android 7.1.1

or map to iOS UI which takes you directly to "add a project" screen offering the two options

People may not understand that they can choose from an existing project/folder
![createnewproject](https://user-images.githubusercontent.com/2231711/68676677-7fd94e80-0528-11ea-9a68-81617e3dd6d3.png)

**Comment by purvi-ranawat** [comment]
@n8fr8 It works fine.
