### ISSUE TITLE
Check in upper right to login to server unresponsive

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#156]
Phone: Moto E
OS: Android 7.1.1
![UpperCheckUnresponsive](https://user-images.githubusercontent.com/2231711/68684606-c2a22300-0536-11ea-87e1-25901a731a5d.png)

**Comment by purvi-ranawat** [comment]
@n8fr8  : I have tried the issue in Samsung Galaxy A70 (Android 9.0) and Samsung Galaxy J7 (Android 6.0.1) and it is working fine
