### ISSUE TITLE
App crashes when adding an image to folder when only connected to WebDav

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#157]
Device: Moto E4
OS: Android 7.1.1

1. selected photo to add to project that was already set up
2. clicked "Add(1)" in lower right
3. App Crashed
4. Reopened app and selected photo was in queue for upload and uploaded successfully 

Happened after fresh reinstall after one other photo uploaded successfully

**Comment by foundscapes** [comment]
App crashed again 10x when I added 3 photos to upload to same folder. They weren't there each time I reopened

**Comment by foundscapes** [comment]
Happened with all media, from 1 image selected - 8

**Comment by purvi-ranawat** [comment]
@n8fr8 : This is working fine in Samsung Galaxy A70 - Android 9.

But on Samsung Galaxy J7 - Android 6.0, the issue still occurs

**Comment by purvi-ranawat** [comment]
@n8fr8 It's working fine on latest build 0.2.1- Beta-5. Tested on Samsung Galaxy J7 Android 6.0 and Samsung Galaxy A70 Android 9
