### ISSUE TITLE
 Add Video/Image compression option under "Data Usage" in App Settings

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#159]
![IMG_7651](https://user-images.githubusercontent.com/2231711/70184046-dd7e3800-169b-11ea-87a8-ee51b25eeed9.PNG)

**Comment by foundscapes** [comment]
@hiromipaw where are we with this for android?

**Comment by hiromipaw** [comment]
Added this to our UX milestone for android.

**Comment by foundscapes** [comment]
resolved with save 2.0 updated ux
