### ISSUE TITLE
Show video icon for videos

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#164]
Phone: Google Pixel 3a
OS: Android 10

We added this to ios, but not sure it made it into the issues, sorry if redundant!

**Comment by n8fr8** [comment]
Can I get more detail / screenshot of what is wrong?

**Comment by foundscapes** [comment]
No video icon indicators on upload / project screens (plant was video):

![Screenshot_20191120-090159](https://user-images.githubusercontent.com/2231711/69260508-dec84480-0b74-11ea-9754-d18f279dbafd.png)
![Screenshot_20191120-090211](https://user-images.githubusercontent.com/2231711/69260509-dec84480-0b74-11ea-8953-050f767f7b0b.png)




indicators within the app are helpful to distinguish videos from photos, see ios UI:

![IMG_7601](https://user-images.githubusercontent.com/2231711/69260157-4c27a580-0b74-11ea-99db-e3cc42697776.PNG)
![IMG_7602](https://user-images.githubusercontent.com/2231711/69260159-4cc03c00-0b74-11ea-9a27-bf8e8328ada8.PNG)

**Comment by n8fr8** [comment]
Ah! got it.

**Comment by purvi-ranawat** [comment]
In Samsung Galaxy A 70 - Android 9.0, on preview screen, video icon is not displayed
@n8fr8  : 

In Samsung Galaxy J7 - Android 6.0.1 , video icon is not displayed when we add media to the project and on preview screen.

Below are the screenshots :

![A70 - previewscreen](https://user-images.githubusercontent.com/8190141/69882247-9ab40d00-12f5-11ea-8dfd-f2df53d6f23c.jpg)

![J7 - video icon missing](https://user-images.githubusercontent.com/8190141/69882266-adc6dd00-12f5-11ea-8ddc-23542df6b8e1.png)

**Comment by purvi-ranawat** [comment]
@n8fr8 It works fine now on Samsung J7 android 6 and Samsung A70 Android 9

**Comment by foundscapes** [comment]
Working on Samsung S7 and Pixel 3a
