### ISSUE TITLE
Add updated android to F-Droid (if not there already)

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#165]

**Comment by n8fr8** [comment]
Merge request for fdroid.org is in progress here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6898

Update in primary guardian project repo will be done as new releases are ready, with next beta/ RC this week.

**Comment by foundscapes** [comment]
Great!

**Comment by sunjam** [comment]
This needs attention on the F-Droid side.  It was just closed due to inactivity.

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6898#note_507524846

**Comment by foundscapes** [comment]
@ozgegn of @elric-wamugu would you be able to help with this?

**Comment by uniqx** [comment]
F-Droid is advocating against GAPPS, they likely won't accept apps with popups like this: https://github.com/OpenArchive/Save-app-android/issues/430

If the message also Mentions MicroG (a Free Software implementation of Play Services) the F-Droid packaging team might be okay with publishing the app, however in that case they will definitely tag the app with their [Non-Free Network Services Anti-Feature](https://f-droid.org/docs/Anti-Features/#NonFreeNet) warning.
