### ISSUE TITLE
On upload screen it shows Review instead of Preview

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#167]
When we select and add a media, it shows Review instead of Preview on Upload screen
Tested on Samsung Galaxy a70 android 9.0

![review](https://user-images.githubusercontent.com/8190141/69896166-03d16a00-1362-11ea-9480-3d7a572a5b67.jpg)

**Comment by foundscapes** [comment]
Same on google pixel 3a android v. 10
![498-1024](https://user-images.githubusercontent.com/2231711/70183848-6ba5ee80-169b-11ea-90ab-fc6b2e127403.png)

**Comment by n8fr8** [comment]
Should be "Preview" everywhere now
https://github.com/OpenArchive/Save-app-android/releases/tag/0.2.2-beta-1
