### ISSUE TITLE
App has reach its max limit message is displayed when we try to sign in using drop box

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#168]
When I try to use the drop box account and sign in using google, the message "This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit" is displayed

Below is the screenshot :

![Dropbox](https://user-images.githubusercontent.com/8190141/69908978-6c2f5280-1419-11ea-8950-e7ac1e30fd46.jpg)

**Comment by n8fr8** [comment]
should be fixed now!
