### ISSUE TITLE
Informational Popups for android UI

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#169]
@n8fr8 let me know if you need me to make separate issues or if this is OK. 

1) Edit Multiple Items - To edit multiple items, tap and hold each.
![IMG_7647](https://user-images.githubusercontent.com/2231711/70182911-a3139b80-1699-11ea-8a91-78adbf3831e5.PNG)

2) Flag Significant Content - When you flag an item, it is routed into a subfolder within the chosen project folder on the private server.
![IMG_7648](https://user-images.githubusercontent.com/2231711/70182968-bf173d00-1699-11ea-98ec-4aa5c5d7b92a.PNG)

3) Internet Archive - You will need to log into or create an Internet Archive account in order to send and preserve Save media at the Internet Archive
![IMG_7650](https://user-images.githubusercontent.com/2231711/70183039-e1a95600-1699-11ea-9068-a6651d876669.PNG)

4) Remove Media From Save - This item will be removed only from the Save App. It will remain on the server and in your camera roll.
![RemoveMediaPopup](https://user-images.githubusercontent.com/2231711/70199697-2c8d9280-16c7-11ea-839f-d47a0ecc9408.png)

**Comment by n8fr8** [comment]
This is fine, thanks. Getting it done.

**Comment by foundscapes** [comment]
Looking good so far on all devices

**Comment by roseregina** [comment]
Checked in 2.2-RC-1 on MotoG and SamsungS7, and both matched iOS.
