### ISSUE TITLE
Move Welcome Language Up

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#172]
Moto G
Android 5.1
OA beta 6 version
@n8fr8 while the text isn't hidden behind the images, it is too close on the wordier screens and there's plenty of space to move them up, so let's do that.

![LangViewable](https://user-images.githubusercontent.com/2231711/70197866-0a454600-16c2-11ea-9686-38d324ad740e.png)

**Comment by n8fr8** [comment]
Need to do custom layout for smaller screens

**Comment by foundscapes** [comment]
phone: motoG
OS: Android 5.1
Save 0.2.2 Beta-2

Still looks cramped on the small screen.

![langcramped](https://user-images.githubusercontent.com/2231711/70765092-836e1a00-1d0e-11ea-96d2-1931af674666.png)

**Comment by foundscapes** [comment]
Looks fine on s7 and 3a, still looks the same on this last screen for moto-g

**Comment by roseregina** [comment]
phone: motoG
OS: Android 5.1
Save 0.2.2 Beta-7


Still the same as at Beta-2

**Comment by purvi-ranawat** [comment]
@n8fr8  / @foundscapes : This is working fine now. The space between the text and the image is quite enough.

I have tested the same on Android 10 and Android 7

Attached is the screenshot :

![image](https://user-images.githubusercontent.com/8190141/84139166-04635f80-aa6d-11ea-9a9e-eccdf4957123.png)

**Comment by foundscapes** [comment]
This may only be an issue on older/smaller phones - @roseregina can you test most recent beta on motog to see if it's still cramped?

thank you!

**Comment by purvi-ranawat** [comment]
@n8fr8  / @foundscapes 

I have also tested on Samsung Galaxy J3 (2016) screen size 5.0, it works fine.
![a8dacd9f-0b53-48de-93a1-63fd94f99d35](https://user-images.githubusercontent.com/8190141/84567723-1ceab700-ad98-11ea-9b3c-0f8214dab0c7.jpg)
