### ISSUE TITLE
Clicking on Flag should turn it yellow, not bring you to metadata field

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#175]
It should map to iOS/be more intuitive since there's no more information to add when flagging.

**Comment by n8fr8** [comment]
you mean you want to be able to tap it to flag on the list screen, and not the full screen?

**Comment by foundscapes** [comment]
Yup like this
![IMG_0153](https://user-images.githubusercontent.com/2231711/70342887-c7db5080-180a-11ea-86ce-b2377dd01f88.PNG)

**Comment by foundscapes** [comment]
phone: motoG
OS: Android 5.1
Save 0.2.2 Beta-2

Tapping the flag while in bulk edit mode worked the first time, but tapping it again to undo brought me to edit screen. Then when I went back, tapping flags on any of the files in bulk edit would bring me to edit screen - it's confusing if it sometimes works and sometimes doesn't, also confusing whether or not we are in bulk edit mode or individual edit mode once metadata options show up after tapping the flag.

**Comment by n8fr8** [comment]
make tap area bigger, and test

**Comment by foundscapes** [comment]
0.2.2-beta-3 
works on moto-g, s7, 3a
