### ISSUE TITLE
Need ability to turn off licesning (Creative Commons Licensing options by Project / Folder)

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#176]
This needs to be implemented in Save for Android

![CC](https://user-images.githubusercontent.com/2231711/70199725-46c77080-16c7-11ea-94b3-74e8c96166c0.png)

**Comment by roseregina** [comment]
0.2.2-RC-1

Good Cloud

MotoG and GalaxyS7


The interface is present and I can select different options, but I cannot turn off CC licensing

1. Click on project folder under _Project Settings_ on Server main view
2. Toggle on Creative Commons 
3. Return to Server main view
4. Upload a photo
5. Check CC licensing on server 
6. Metadata json file indicates correct CC licensing 
7. Return to same view as step 2 and turn off Creative Commons licensing
8. Check CC licensing on server 
9. **Expected results** Metadata json file includes nothing about licensing
**Actual results** Metadata json file indicates CC licensing, incorrectly

I checked in iOS and I am able to turn off CC licensing successfully.

**Comment by n8fr8** [comment]
good catch!

**Comment by foundscapes** [comment]
@roseregina can you re-test this w/ 0.2.3-BETA-1?

**Comment by purvi-ranawat** [comment]
@n8fr8 / @foundscapes : Now I am able to turn off CC licensing successfully on Android 10.

But the licensing details are not getting displayed in the JSON files when CC licensing is on

Attached are the content of  json files with CC licensing on and off

CC Licensing on : 

{"collectionId":4,"contentLength":1630614,"createDate":"Jun 11, 2020 20:45:06","flag":false,"mediaHashBytes":[],"mediaHash":"4654585e8ad0645434eb382aa27733233d56faf23797b00eb0807f7e4924f75c","mimeType":"image/jpeg","originalFilePath":"file:///data/user/0/net.opendasharchive.openarchive.release/cache/20200611_204506.JPEG_20200606_220715.jpg","priority":1,"progress":1630614,"projectId":1,"selected":false,"serverUrl":"https://use01.thegood.cloud/remote.php/dav/files/purvishah.u@gmail.com/new2/2020-06-11T20:45:06GMT+05:30/JPEG_20200606_220715.jpg","status":5,"statusMessage":"","title":"JPEG_20200606_220715.jpg","updateDate":"Jun 11, 2020 20:45:06","uploadDate":"Jun 11, 2020 20:45:08","id":4}


CC Licensing off : 

{"collectionId":5,"contentLength":147400,"createDate":"Jun 11, 2020 20:46:30","flag":false,"mediaHashBytes":[],"mediaHash":"641af72372b10acdf4a64f9f0bdc3061272b0a2c04e533033d4c791bb39bd203","mimeType":"image/jpeg","originalFilePath":"file:///data/user/0/net.opendasharchive.openarchive.release/cache/20200611_204630.Screenshot_20200608-132112_eazyshyp.jpg","priority":1,"progress":147400,"projectId":1,"selected":false,"serverUrl":"https://use01.thegood.cloud/remote.php/dav/files/purvishah.u@gmail.com/new2/2020-06-11T20:46:30GMT+05:30/Screenshot_20200608-132112_eazyshyp.jpg","status":5,"statusMessage":"","title":"Screenshot_20200608-132112_eazyshyp.jpg","updateDate":"Jun 11, 2020 20:46:30","uploadDate":"Jun 11, 2020 20:46:36","id":5}

**Comment by n8fr8** [comment]
@purvi-ranawat there is a new build that I have tested this with successfully. I couldn't fully reproduce your issue, but did double check and make small modifications to the code for publishing the license value in the json.

Please test again, https://github.com/OpenArchive/Save-app-android/releases/tag/0.2.3-RC-1

**Comment by purvi-ranawat** [comment]
@n8fr8 / @foundscapes : This is working fine. I am able to see the licensing value in the json if we have enabled creative commons licensing options for project
