### ISSUE TITLE
Cannot remove batch media from project or preview screen 

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#177]
Google Pixel 3a
OS Android 10
Save v. 0.2.2-beta-1 
In project space, tap hold works, but when I go to edit pencil and select only option "remove" nothing happens and it stays in project space and continues uploading.

![DoesNotDelete](https://user-images.githubusercontent.com/2231711/70347040-86e83980-1814-11ea-91cc-f9aff36979d7.png)

The option to remove media / 3 dots in edit screen/preview mode is gone.
![NoRemovePreview](https://user-images.githubusercontent.com/2231711/70347048-8b145700-1814-11ea-88da-95cac424de9e.png)

**Comment by foundscapes** [comment]
Also when I swipe left on it, it just stays in edit circle

**Comment by foundscapes** [comment]
Samsung Galaxy s&
OS 3.2.49
Save v. 0.2.2-beta-2


Google Pixel 3a
OS Android 10
Save v. 0.2.2-beta-2

For both phones, media is removed in preview screen when clicking the trash icon, but when I click on edit pencil, and then click three dots in upper right and click "remove media" it is not removed from preview screen

**Comment by n8fr8** [comment]
Got it

**Comment by foundscapes** [comment]
0.2.2-beta-3 
works on moto-g, s7, 3a
