### ISSUE TITLE
Change first welcome screen language

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#179]
Need to find easy/fast way to mock up but it should read:

**_Save_** by OpenArchive

Share
Archive
Verify
Encrypt

**Comment by foundscapes** [comment]
Please map to font (montserrat)/hex color of the iOS from #88 except for first welcome screen - will have a mockup for that soon!

**Comment by foundscapes** [comment]
Looks MUCH better! Perhaps add a bit more space between Encrypt and "Secure Mobile Media..." to bring it lower, unbold and italicize "Secure Mobile Media...'

![576-1024](https://user-images.githubusercontent.com/2231711/71924994-ee134980-3144-11ea-8fcd-817bb3ac6860.png)

**Comment by foundscapes** [comment]
I need to make Future coolness for fonts/colors

**Comment by roseregina** [comment]
@n8fr8 In looking at this first screen in 0.2.2-beta-6 a few days ago with @foundscapes, is it possible to have a variable distance based on screen size/ percentages between the big "Share Archive Verify Encrypt" and the smaller "Secure Mobile Media Preservation" ?

**Comment by n8fr8** [comment]
sure, but moving out of this sprint to the next one

**Comment by foundscapes** [comment]
Version: Save for Android 0.2.3-BETA-1
OS: Android 10
Phone: Pixel3a
![Screenshot_20200425-130257](https://user-images.githubusercontent.com/2231711/80289791-f1cbdb80-86f5-11ea-99c7-3784b7139263.png)
Looks good. 

@roseregina can you test on the smaller screens to make sure spacing is relative?

**Comment by roseregina** [comment]
@foundscape Here is the screenshot for the motoG: 
![image](https://user-images.githubusercontent.com/15040203/80325479-edd5b180-87fa-11ea-9b6a-aa72e921f555.png)
