### ISSUE TITLE
Wrong error msg when name is incorrect on S7

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#180]
phone: Galaxy S7
OS: 3.2.49

When pw is there and username is incorrect, I get "incorrect password error" - which is incorrect - it should read: "incorrect username" over username.

![UNIncorrectS7](https://user-images.githubusercontent.com/2231711/71021103-7b1d3280-20b2-11ea-886d-e610bbae164f.jpg)

**Comment by n8fr8** [comment]
need to check, improve error message for login failure

**Comment by foundscapes** [comment]
0.2.2-beta-3 
s7, moto g, 3a
"login failed" error when incorrect username or pw are entered BUT the lag is bad  (30 seconds - 2 minutes) when either showing error OR successfully logging in on all phones

**Comment by n8fr8** [comment]
the lag issue is a separate ticket #178 so let's track that issue there
