### ISSUE TITLE
One can change the name of the project after it's been created, but not really

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#181]
Samsung Galaxy S7
OS: 3.2.49
Save version 0.2.2 Beta 2

When I change the folder name in the server screen, it does not change in the project space or on the server.

Expected Result: either I should not be allowed to change the folder name OR it should update everywhere

Actual Result: the folder name looks changed in both places, but then isn't in project workspace

![ChangeFolderNameS7](https://user-images.githubusercontent.com/2231711/71021708-c552e380-20b3-11ea-92cf-22b90e9fdb32.jpg)
![ChangeFolderName1S7](https://user-images.githubusercontent.com/2231711/71021714-c84dd400-20b3-11ea-9c17-93a9d46185be.jpg)
![FolderNameUnchangedS7](https://user-images.githubusercontent.com/2231711/71021728-cc79f180-20b3-11ea-9bd0-19e42f5dd0fe.jpg)

**Comment by foundscapes** [comment]
need to disable ability to change project names b/c new folders are made on server vs. folder names updating to new.

**Comment by foundscapes** [comment]
@roseregina is this still happening in 0.2.3-BETA-1?

**Comment by roseregina** [comment]
0.2.3-BETA-1
GalaxyS7

I can no longer change project names. Name is greyed out and nothing happens when I click on the name on the project settings screen for that project.
