### ISSUE TITLE
Confusing UI when leaving new project name blank

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#182]
Since iOS has a "done" button in upper right that is greyed out, it's more obvious that you cannot create a project with no name.

![NoNameiOS](https://user-images.githubusercontent.com/2231711/71023275-452e7d00-20b7-11ea-9431-2bdbcb8ea90c.png)

However, on Galaxy s7 and moto G / all android devices, it is less clear that you must name the project with only a back arrow. Can we add a "done" button in upper right so there isn't so much confusion?

![NoNames7](https://user-images.githubusercontent.com/2231711/71023294-4e1f4e80-20b7-11ea-8e24-ab6245d90eb8.jpg)

**Comment by n8fr8** [comment]
DONE button added
