### ISSUE TITLE
Two project folders with same name in browse, but not two on server

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#183]
Beta-2

on all android devices, there are two "oademo" folders when browsing projects:

![TwoFoldersPixel3a](https://user-images.githubusercontent.com/2231711/71025015-0ef2fc80-20bb-11ea-9fad-ab250977fa05.png)

however there is only one on the server (which means it's not a duplicate folder issue, but some other bug):
<img width="1100" alt="OneOademoServer" src="https://user-images.githubusercontent.com/2231711/71025136-4e214d80-20bb-11ea-8a67-d362e490be6f.png">

**Comment by foundscapes** [comment]
0.2.2-beta-3 
Pixel 3a, S7, Moto-G
Now there are two double projects in project list on all phones
![MotoGTwice3A](https://user-images.githubusercontent.com/2231711/71791262-3ae20d80-2fe9-11ea-94f9-3a4f43a24429.png)

**Comment by n8fr8** [comment]
related to url encoding of folder names, causing duplicate creation on the server

**Comment by n8fr8** [comment]
this issue with creating duplicate folders should be fixed now moving forward.

Before if you had a folder with spaces in it "My Test Folder", that you selected by browsing, and then you uploaded a new media file to it, it would be created again as "My+Test+Folder" on the server. We no longer do that.

Also, we now display the folder names properly, so you should see "motoG testing" and "motoG+testing" to know they are different.

**Comment by n8fr8** [comment]
Solved another part of this issue. Your account is named "oademo" and there is also a folder named "oademo" inside that account. The first "oademo" displayed is the root folder of the users home path on the server. The second is a folder inside of that so "oademo/oademo".

The bug is that we shouldn't display the user's root folder in the list of project folders. In the next build, this will be fixed.

**Comment by foundscapes** [comment]
version: 0.2.3-BETA-1
OS: android 10
phone: pixel 3a

@n8fr8 there are still two oademo folders in existing projects (can't post a screenshot as there are too many folders now between them to show them in one shot, but they're both there).

**Comment by foundscapes** [comment]
version: 0.2.3-BETA-3
OS: android 10
phone: pixel 3a

ISSUE RESOLVED!
