### ISSUE TITLE
Number in circle in upper right & Xitems cramped on S7 + discrepancy btwn #'s

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#185]
Phone: Galaxy s7
OS: Android 3.2.49
Save - Beta-2

Three issues:
1. Upload number in circle is cramped

2. Xitem(s) under "ready to upload" should have a space between number and item(s)

3. There is also a discrepancy about the number - it says 6 but there are only 5 in the queue / circle
![Spacing_and_NumberDiscrep S7jpg](https://user-images.githubusercontent.com/2231711/71026665-8d04d280-20be-11ea-9d26-f2168dd0f992.jpg)

Both look fine on Pixel 3a

**Comment by foundscapes** [comment]
map to iOS
![circleiOS](https://user-images.githubusercontent.com/2231711/71032195-b70fc200-20c9-11ea-9db3-eb7a68b1a9b1.png)

**Comment by n8fr8** [comment]
added items at different times, perhaps while one was uploading already

**Comment by foundscapes** [comment]
need to test again on all devices if adding items confuses the upload queue number in preview

**Comment by foundscapes** [comment]
0.2.2-beta-3 
looks fine (even double digits) on s7, moto-g, 3a
