### ISSUE TITLE
Dropbox login/ set up "infinte loop"

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#187]
Save 0.2.2-beta-5

Dropbox server (rr's personal account)

1. Logged in to dropbox account motoG, GalaxyS7, Pixel3a
    Pixel3a was slowish, but I suspect that it was on the dropbox side

2. Attempt to add project:
    on all

**Comment by n8fr8** [comment]
Can you provide some more details here? What was looping exactly?

**Comment by roseregina** [comment]
Sorry, this got got folded into #189 , ignore this issue
