### ISSUE TITLE
New tab bar white in dark mode on Pixel 3a

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#188]
Save 0.2.2-beta-5
![3aWhiteTabBar](https://user-images.githubusercontent.com/2231711/72023077-c2689000-3226-11ea-92ce-29c3369a256b.png)

**Comment by roseregina** [comment]
Save 0.2.2-beta-7
Pixel3a (other phones do not have a new enough OS for dark theme)

Bar is now black in dark theme (and white in standard theme)

![image](https://user-images.githubusercontent.com/15040203/72214652-65393c80-34bb-11ea-9985-e12e940efcdf.png)
![image](https://user-images.githubusercontent.com/15040203/72214683-e42e7500-34bb-11ea-991a-d97459922c63.png)
