### ISSUE TITLE
Remove Dropbox Space - Confusing process

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#189]
Save 0.2.2-beta-5

Dropbox server (rr's personal account)

1. Logged in to dropbox account motoG, GalaxyS7, Pixel3a
    Pixel3a was slowish, but I suspect that it was on the dropbox side

2. Attempt to remove from space, motoG, GalaxyS7, Pixel3a: 
a.   Expected Result: click on Circle D/ Dropbox icon on left of screen, taken to removal screen
b. Actual Result: click on Circle D/ Dropbox icon on left of screen, taken to Dropbox request for permissions page with "cancel" and "allow" as only options
 1)  if I press allow, it takes me to the drop box project spaces
 2) if I press cancel, it takes me to the DB login screen with options:  "Remove from App", as well as a 
     field for my dropbox username. 
   a) Expected result: This is where it should just allow you to remove from app directly from the server 
       space screen 
d. if I press remove, there is a popup to confirm that I want to remove it from the app. 

3. Logging in after removal: 
a.   Expected Result: on "Connect Your Space" screen, click "Dropbox", taken to a page where I am prompted for credentials

b. Actual Result: on "Connect Your Space" screen, click "Dropbox", taken to dropbox page where I am already logged in and I am asked to grant _**Save**_ access, with "cancel" and "allow" as options. 
  
I think this is happening because logging in to Dropbox for  _**Save**_  is also logging me in to dropbox in the browser. 

This raises the question on what happens if the default browser is something like Firefox Focus that clears the cookies each time it is closed.

**Comment by roseregina** [comment]
Save 0.2.2-beta-7
motoG (did not test on other phones yet, but will if helpful) 

So close! 

expected result: 
1. logged in to dropbox account motoG, GalaxyS7, Pixel3a
2. click on Circle D/ Dropbox icon on left of screen
3. taken to server removal screen (with header "Log in") 
a. click on "Remove from App" and the Dropbox server is removed from app
b. click on greyed out checkmark in upper right and either nothing happens or the Dropbox server is removed from app

actual results
1. logged in to dropbox account motoG, GalaxyS7, Pixel3a
2. click on Circle D/ Dropbox icon on left of screen
3. taken to server removal screen (with header "Log in") 
a. click on "Remove from App" and the Dropbox server is removed from app
b. click on greyed out checkmark in upper right
4. (from 3b only) taken to Dropbox _**Save**_ app permissions screen in browser
5. clicking both "Cancel" and "Allow" both return me to server removal screen (with header "Log in") 

I don't know if this really matters, but it was weird and slightly confusing when it happened.

**Comment by foundscapes** [comment]
@n8fr8 is this fixable?

**Comment by n8fr8** [comment]
removed the checkbox/done from the dropbox form, so yes, fixed!
