### ISSUE TITLE
Dropbox user name issue

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#192]
Save 0.2.2-beta-5

MotoG

Expected results: email address used to log in to Dropbox is displayed underneath "Dropbox" on the server screen and appears in the "username" field and should map to server name in **_Save_** 

Actual results: a 10 digit number is inserted of an email address. This is almost definitely a Dropbox user number since it remains stable in connection to the Dropbox account. When I tried change it through the username field that appears on the logout screen, it did not save my new input.

**Comment by n8fr8** [comment]
that field is not meant to be editable, so will disable that. otherwise, not sure how to get the actual human readable dropbox username for now.

**Comment by n8fr8** [comment]
some progress her, moving to other sprint, to see if we can get the actual username somehow eventually. for now, the user can no longer edit this field.

**Comment by roseregina** [comment]
Save 0.2.2-beta-6
identical results on motoG, GalaxyS7, and Pixel3a

Email address now displayed instead of 10 digit number

From Pixel3a as proof: 
![image](https://user-images.githubusercontent.com/15040203/72189020-9f69e780-33b0-11ea-97e9-d1c44315f050.png)

Ready to close?
