### ISSUE TITLE
Add info about rate limiting and login to org oriented documentation

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#193]
Anti brute forcing/ rate limiting measures from servers may cause issues with logging in after multiple incorrect attempts. This and similar server side settings should be at least referenced as a possible point of user difficulty in the documentation for orgs who are using _*Save*_ with their own server. 

See #178 for example

**Comment by foundscapes** [comment]
@hiromipaw to be included in updated documentation / UX for save 2.0

**Comment by hiromipaw** [comment]
@foundscapes I am confused if we want to handle the rate limiting error on the app side or just document it for users?

**Comment by foundscapes** [comment]
@hiromipaw I believe this is just for documentation and doesn't need to be in the app aside from an error that covers login issues
