### ISSUE TITLE
Dropbox logging in to wrong Dropbox account

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#194]
Save 0.2.2-beta-7
motoG and Pixel3a (did not test with GalaxyS7)

expected result: 
1. on "Connect your Space" screen click "Dropbox", be taken to Dropbox login screen in browser, put in credentials, accept sharing access with Save App, return to app, and see that I am logged in to first account
2. on "Connect your Space" screen click "Dropbox", be taken to Dropbox login screen in browser
3. enter credentials for second account
4. accept sharing access with  _*Save*_ App
5. return to app and see that I am logged in to second account in the second Dropbox server tab and the first account in the first Dropbox server tab

actual results (following assumed steps): 
1. on "Connect your Space" screen click "Dropbox", be taken to Dropbox login screen in browser, put in credentials, accept sharing access with Save App, return to app, and see that I am logged in to first account
2. on "Connect your Space" screen click "Dropbox", be taken to Dropbox login screen in browser
3. arrive on Dropbox access permissions page (_not_ Dropbox login page)
*NOTE:* if I select either "Cancel" or "Allow", I am taken back to the Dropbox server screen inside the app and it is logged in to the first Dropbox account
4. click on "Sign out" in the upper right corner, and go to main Dropbox login screen
5. enter credentials for second account
6. accept sharing access with  _*Save*_ App
7. return to app and see that I am logged in to first account in both Dropbox server tabs

actual results (workaround to sign in to a second Dropbox account): 
1. on "Connect your Space" screen click "Dropbox", be taken to Dropbox login screen in browser, put in credentials, accept sharing access with _*Save*_ App, return to app, and see that I am logged in to first account
2. open browser and log out of Dropbox in the browser
3. return to  _*Save*_ App
4. on "Connect your Space" screen click "Dropbox", be taken to Dropbox login screen in browser
5. enter credentials for second account
6. accept sharing access with  _*Save*_ App
7. return to app and see that I am logged in to second account in the second Dropbox server tab and the first account in the first Dropbox server tab

**Comment by foundscapes** [comment]
@roseregina can you reproduce this with the current build?

**Comment by roseregina** [comment]
Save 0.2.3-beta-1
GalaxyS7

actual results (workaround to sign in to a second Dropbox account):
1. on "Connect your Space" screen click "Dropbox", be taken to Dropbox "permission to access it's own folder" screen
2. Click "Sign out" in upper right of Dropbox screen
3. Enter in second account credentials
4. Click accept on  Dropbox "permission to access it's own folder" screen (where it lists the second account email address below the button) 
[Here, I confirmed that **_Save_** is still acting like I have signed in to one account twice, both by showing the first account email address on both and that when I uploaded media in what should have been the second account, it went to the first account.]
5. Click on the large teal circle circle-D icon on the left of the screen for the second Dropbox account 
6. Click "Remove from App"
7. Confirm by selecting "Remove" on pop-up
8. Click the cirlce-plus in the upper right of screen
9.  Select "Dropbox (BETA)" on "Connect Your Space"  screen
10. Click accept on  Dropbox "permission to access it's own folder" screen (where it lists the second account email address below the button) 
11. When I am taken back to the server view in **_Save_**, the second account email address is listed and media is uploaded to the second account. 

The workaround workflow is slightly different, but the core problem that it is logging in to the wrong account continues.

**Comment by foundscapes** [comment]
@roseregina please test with beta-3

**Comment by roseregina** [comment]
This is still a problem with 0.2.3-BETA-3, but I think that the issue may be coming from  Dropbox given that I don't this we ever really resolved it with iOS aside from just not allowing more than one Dropbox login at a time. 

Actual behaviour on the GalaxyS7: 
1. Successfully add dropbox account A
2. Add Dropbox via Connect Your Space page
3. Taken to Dropbox site in browser, where stilled logged in to account A
4. Log out of account A
5. Log in to account B
6. Click "Accept" for _**Save**_ access, with account B listed on the Dropbox permissions
7. **There are two Dropbox servers both listed for account A** 
8. Add Dropbox via Connect Your Space page
9. Taken to Dropbox site in browser, where stilled logged in to account B
10. Click "Accept" for _**Save**_ access, with account B listed on the Dropbox permissions
11. There are three Dropbox servers total, **two for account A and one for account B**

The effect is that it looks like the app can only log in to one dropbox account until the third Dropbox is added and that users could end up uploading to the wrong account if they don't notice that that it didn't work as expected. Is it possible/ desirable to only allow one Dropbox, as with iOS?

**Comment by foundscapes** [comment]
See #211 for a potential fix @n8fr8
