### ISSUE TITLE
Naming schema for Dropbox upload subfolders is cumbersome

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#195]
Save 0.2.2-beta-7
Dropbox
MotoG

The date format is Day of Week-Month-Day-Time-Time zone- Year in the folder name: 
![image](https://user-images.githubusercontent.com/15040203/72223632-da415c00-3525-11ea-835c-bccba7ddeec7.png)

I can sort by date modified through the Dropbox web interface: 
![image](https://user-images.githubusercontent.com/15040203/72223655-15dc2600-3526-11ea-84f6-6e6588411898.png)

I went into my dropbox account and changed the date format settings, so I think that the US style format comes from the app, not from Dropbox. 

When I changed the date format on the motoG (by going into settings and selecting English (United Kingdom, visually checking on the phone that date was displayed as 12 Jan 2020, force quitting and restarting save, then uploading a new photo), only the way the timezone was displayed changed: 
![image](https://user-images.githubusercontent.com/15040203/72223796-b1ba6180-3527-11ea-819c-c9ebf61f8f57.png)

Questions: 

1. Is this a fixed format that we want? 

2. How (if at all) will this work with localization? (given that it uses Jan instead of 1)

3. Do we know what we expect in terms of how people will interact with the uploaded media? (does this even matter?)

4. Is this something to test on other servers? (meaning, I'm noticing this because I'm seeing it in Dropbox, but is this the same case with other upload options?)

**Comment by foundscapes** [comment]
@roseregina interesting 

1. yes it's the format we decided on for all uploads
2. given that the app itself is localized into at least 4+ languages, we'll need to test in other languages to check
3. The format was decided after researching with human rights NGOs who felt date format was easiest to navigate
4. If you upload to nextcloud servers, folders are also named by date/time

**Comment by roseregina** [comment]
re:1 
It's different from the iOS app, using _YYYY_-_MM_-_DD_*T*_HH_:_MM_:_SS_*GMT*_HH_:_MM_: 
![image](https://user-images.githubusercontent.com/15040203/80289505-67d73f00-8704-11ea-9d80-1db33686fc71.png)
My question was less about using the date and time as a naming schema, but rather about what date format was desired given that the month and day of the week abbreviations aren't friendly for sorting or localization and is not the format structure favored by most of the world.

**Comment by foundscapes** [comment]
Ah gotcha. Very good catch.
We should format the date/time stamps the same was ios has, is that possible @n8fr8 

Along with localization issues, the format for android on GoodCloud has the same problem as we can't sort uploads by date b/c "name" is the only option for that column. One would have to sort by "modified" to get a chronological order.
<img width="537" alt="Screen Shot 2020-04-25 at 1 27 08 PM" src="https://user-images.githubusercontent.com/2231711/80290186-a7982980-86f8-11ea-893c-ef296bd792e8.png">

**Comment by n8fr8** [comment]
I will make sure we are using the same format on Android as on iOS. The intention was to do that, based on the spec.

Otherwise, sortability in a web UI , be it NextCloud or Dropbox, was never a requirement or feedback we received from users. The format is not controlled by the device time zone setting.

**Comment by n8fr8** [comment]
(That said, it might be desirable)

**Comment by roseregina** [comment]
0.2.3-BETA-3
GalaxyS7
Good Cloud (oademo) 

![image](https://user-images.githubusercontent.com/15040203/82766476-0ed2f780-9de5-11ea-9443-d0ac350a627f.png)
