### ISSUE TITLE
2FA for NextCloud

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#197]

**Comment by foundscapes** [comment]
@n8fr8 how is this going?

**Comment by n8fr8** [comment]
This is heavily related to #72

**Comment by foundscapes** [comment]
@n8fr8 #72 was about the IA - shall I change the title and close this issue?

**Comment by n8fr8** [comment]
Sorry for the confusion. #72 isn't something we can do for IA. However, adding the QR code support is one way to make "auto-login" easier.

That said, QR code scanning s the solution for 2FA on Nextcloud... that or manually entering in an app-specific password.
