### ISSUE TITLE
Option to add image for servers since one letter icons may be hard to identify w/ multiple backends

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#198]
![tooManyLetters](https://user-images.githubusercontent.com/2231711/72638152-ad22ee00-3917-11ea-9568-31007de0a091.png)

**Comment by n8fr8** [comment]
In the case of a nextcloud instance, the server has an icon image it provides at:
/index.php/apps/theming/image/logo?useSvg=1&v=9

so
https://cloud.guardianproject.info/index.php/apps/theming/image/logo?useSvg=1&v=9

for instance for ours.

For other services like Dropbox or Internet Archive, we should use the stock icons from those services.

**Comment by ozgegn** [comment]
Hi @n8fr8 ,
Apk is shared to test the feature.

**Comment by purvi-ranawat** [comment]
@johnhess For thegood.cloud instead of icon first letter of server URL is getting displaye
![WhatsApp Image 2022-04-25 at 11 22 57 AM](https://user-images.githubusercontent.com/8190141/165028833-30d7f0c5-bfc6-4537-95ab-59873cc64aed.jpeg)
d

**Comment by hiromipaw** [comment]
@foundscapes is this issue still valid or we can close it since it might have been taken care with the design update?

**Comment by foundscapes** [comment]
> @foundscapes is this issue still valid or we can close it since it might have been taken care with the design update?

resolved with the update, thank you!
