### ISSUE TITLE
Crashes to Android desktop when waiting

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#199]
Save 0.2.2-beta-7

Galaxy S7

Good Cloud server

When I let the galaxyS7 just sit while uploading is slow or crashed, 

1. Select and upload a bunch of images
2. Set down phone with upload screen open 
3. Wait for uploads to finish
4. **Expected Results** uploads finish and the app is still open
4. **Actual Results** uploads either do or don't finish and the Android desktop is open instead of the app

I found this while testing  stuff related to uploads and I don't have a full description, will add more details.  I don't have timing info yet and I haven't finished testing if this also happens on other screens or with other phones. This happened at least three times as described above.

**Comment by roseregina** [comment]
Save 0.2.2-RC-1

MotoG

Good Cloud server and DropBox


Crashes to desktop whenever I hit the edit button for the Uploads queue on the MotoG (but not the GalaxyS7).

**Comment by n8fr8** [comment]
Found a crash in the Dropbox SDK:

04-06 17:47:49.157 19490-19530/net.opendasharchive.openarchive.release E/ACRA: ACRA caught a NullPointerException for net.opendasharchive.openarchive.release
    java.lang.NullPointerException: src == null
        at java.lang.System.arraycopy(System.java:275)
        at java.io.PipedInputStream.read(PipedInputStream.java:344)
        at okio.Okio$2.read(Okio.java:140)
        at okio.RealBufferedSink.writeAll(RealBufferedSink.java:105)
        at com.dropbox.core.http.OkHttpUtil$PipedStream.writeTo(OkHttpUtil.java:79)
        at com.dropbox.core.http.OkHttp3Requestor$PipedRequestBody.writeTo(OkHttp3Requestor.java:358)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:69)

**Comment by foundscapes** [comment]
@roseregina please test with 0.2.3-BETA-1

**Comment by roseregina** [comment]
0.2.3-BETA-1
GalaxyS7
Guardian Project server

I think this happened at least once again, but I want to reproduce it at least once more before I say for certain that it is the same behaviour.

**Comment by roseregina** [comment]
Save 0.2.3-beta-3
Galaxy S7
Good Cloud server

Appears resolved

**Comment by foundscapes** [comment]
@roseregina please test with dropbox, then we can close, thank you!

**Comment by foundscapes** [comment]
@purvi-ranawat please test with dropbox to see if this is still an issue. Thank you

**Comment by purvi-ranawat** [comment]
@foundscapes / @n8fr8 : This is working fine. I have selected around 25 photos and kept the app open while uploading. The app doesnt crash. I have tried the same on Android 9 and Android 7
