### ISSUE TITLE
Improve video reorder drag and drop - Tried to reorder so video (in last place in queue) goes last, not first - but reordering won't work (for any items)

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#202]
Phone: Pixel 3a OS: Android 10 server: oademo (goodcloud)

**Comment by foundscapes** [comment]
Phone: Pixel 3a OS: Android 10 server: oademo (goodcloud)

Expected result: reordering successful in edit screen, no crash

Actual Result:
1. paused uploads w/edit
2. tried to reorder - would not allow any items to reorder more than one space up or down
3. resumed uploads and app crashed and took us back to android home screen

Phone: MotoG server oademoa (GC)
Expected result: reordering successful in edit screen, no crash
Actual Result:
1. paused uploads w/edit
2. tried to reorder - would not allow any items to reorder more than one space up or down
3. before closing edit screen, app crashed took us back to android home screen

phone: galaxy s7 server oademoa (GC)
Expected result: reordering successful in edit screen, no crash
Actual Result:
1. paused uploads w/edit
2. tried to reorder - would not allow any items to reorder more than one space up or down
3. before closing edit screen, app crashed took us back to android home screen

**Comment by n8fr8** [comment]
released to #203 in that the upload service pausing/editing wasn't working. next build, pressing "edit" will indeed stop all current uploads, allowing for reordering, and pressing "done" will restart uploading.

**Comment by foundscapes** [comment]
Awesome, we'll test all features!

**Comment by roseregina** [comment]
0.2.2-RC-1

MotoG and GalaxyS7


@n8fr8 Pausing is now works when it doesn't crash the app, but it is still only allowing me to move one space up or down at a time.

**Comment by foundscapes** [comment]
@roseregina can you test this with 0.2.3-BETA-1?

**Comment by roseregina** [comment]
0.2.3-BETA-1
GalaxyS7 
Dropbox and good cloud 

Drag and drop works as expected. 

Upload order was a little strange, but only after wifi connection was interrupted mid upload (once reconnected, upload went as follows: second to last, last, first, second....) and unclear if bug, but suspect is feature or feature adjacent.

**Comment by roseregina** [comment]
0.2.3-BETA-3
GalaxyS7
Dropbox

If I do not interfere, files upload bottom to top, but as soon as I interact with the edit button (even without reordering), upload order changes to top down. 

Observed behaviours (top of queue ---> bottom of queue): 

This is only true with adding files to upload all at one time in order A, B, C, D, E (numbered in upload view 1-5)
![image](https://user-images.githubusercontent.com/15040203/81986158-ee44b980-95fc-11ea-8ade-bfdf75ee5063.png)

When images are added in more than one batch, the order behaviour is much more chaotic and I have not been able to reliably figure out a pattern for upload order. 

**Without interaction:**
Initial order: 
E
D
C
B
A
Modified order: n/a
Upload order: A, B, C, D, E

**Only clicking "Edit" and "Done", no reordering:** 
Initial order: 
E
D
C
B
A
Modified order: E moved to the top of the queue when I clicked "Done", but I did not move it
Upload order: E, A, B, C, D 

**With reordering to top of queue:**
Initial order: 
E
D
C
B
A
Modified order: 
B
E
D
C
A
Upload order: B, E, D, C, A

**With reordering lower in the queue:**
Initial order: 
E
D
C
B
A
Modified order: 
E
D
B
C
A
Upload order: E, D, B, C, A

**Comment by foundscapes** [comment]
0.2.3-BETA-3
Pixel 3a
Dropbox

I've reproduced what @roseregina did and had exact same results. The drag/drop reorder is working but the queue begins uploading from bottom.

**Comment by n8fr8** [comment]
found/fixed an issue related to this: new build please test: https://github.com/OpenArchive/Save-app-android/releases/tag/0.2.3-RC-1

**Comment by ozgegn** [comment]
Tested with;

Samsung A50 Android: 10
Xiaomi Redmi 7 Android: 10

Uploads media as given order
