### ISSUE TITLE
Pausing upload crashes app half the time

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#204]
Save 0.2.2-RC-1

Dropbox server (rr's personal account) and Good Cloud server

GalaxyS7
MotoG

1. Upload multiple files
2. Click on circled number to go to Uploads view
3. Click "Edit" in upper right corner
4. **Expected result** upload pauses
**Actual result** some of the time (maybe half), it behaves as expected, but the other half of the time, the app crashes to the main android screen.

**Comment by foundscapes** [comment]
@roseregina please test with 0.2.3-BETA-1

**Comment by roseregina** [comment]
0.2.3-BETA-1
GalaxyS7 
Dropbox and good cloud

This preliminarily looks resolved, but I want to check on the motoG if possible.
