### ISSUE TITLE
Ensure > 150MB files are supported by Dropbox upload

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#205]
https://www.dropboxforum.com/t5/Discuss-Developer-API/Develop-Android-app-to-upload-large-file-to-Dropbox-Failed-all/td-p/374719

https://github.com/OpenArchive/Save-app-ios/issues/176

**Comment by n8fr8** [comment]
and sample here:
https://github.com/dropbox/dropbox-sdk-java/blob/aa70590b492bc79a47c6eaf5bc667206ab51bfdd/examples/upload-file/src/main/java/com/dropbox/core/examples/upload_file/Main.java#L70

**Comment by foundscapes** [comment]
@n8fr8 @tladesignz have we fixed this?

**Comment by n8fr8** [comment]
yes, this is implemented on Dropbox for Android at least. Not sure where we stand with Dropbox for iOS large file support.
