### ISSUE TITLE
update welcome screen image on google play

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#206]
https://play.google.com/store/apps/details?id=net.opendasharchive.openarchive.release&hl=en_US

**Comment by foundscapes** [comment]
Will add screenshot asap

**Comment by foundscapes** [comment]
![Screenshot_20200511-133829](https://user-images.githubusercontent.com/2231711/81616682-cb19d000-9398-11ea-8484-21311fe94b05.png)
if someone can format/add this soon, that'd be great

**Comment by n8fr8** [comment]
Will do it this last time, but going forward you do have full access to Google Play, and since this doesn't require coding or other special engineering skills, would be something to take on yourself.

**Comment by n8fr8** [comment]
done
