### ISSUE TITLE
Add "Share Archive Verify Encrypt" on Google Play

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#207]
So it reads:

Save (Share Archive Verify Encrypt) by OpenArchive enables you to safely preserve, organize, and share your mobile media.

Designed with and for newsrooms, human rights defenders, and archivists, Save keeps you in control of your mobile media at all times.

**Comment by n8fr8** [comment]
- please don't assign Android things to tladesignz
- again, moving forward, you have full access to manage Google Play listings, so please handle further changes there yourself

**Comment by n8fr8** [comment]
done

**Comment by tladesignz** [comment]
@foundscapes I don't have access to the Google Play Console, anyway...
