### ISSUE TITLE
Orobot prompt after Save install

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#209]
we need a popup saying: "in order to use Save over the Tor network, you will need to install orbot here" or something similar that links to orbot download

**Comment by foundscapes** [comment]
Add prompt after welcome screens?

**Comment by n8fr8** [comment]
Why not build it into the onboarding as the final step? Why would we have such a beautiful startup process only to interrupt it with an annoying, ugly popup dialog?

**Comment by foundscapes** [comment]
Sounds good to me if we can add it to an existing screen, I think we have enough and would rather not add one more. We hadn't designed any imagery for that w/ OkThanks, so didn't know that was an option. Go for it!

**Comment by n8fr8** [comment]
It doesn't fit in any existing screen. 

I will just make it a pop-up.

**Comment by foundscapes** [comment]
What would be ideal is if onboarding screens can map to our Share, Archive, Verify, Encrypt features possibly using the new graphics we will soon have on the website. Then Orbot could link from the last Encrypt onboarding screen.

**Comment by foundscapes** [comment]
For now, I think a popup is best since this won't happen until after we finish the web design work w/ OTF's learning lab.

**Comment by n8fr8** [comment]
There were issues with doing a pop-up. I have added it the onboarding, so test with a fresh install. It looks good.

In short, if you don't have Orbot, it prompts you to install it, if you do have Orbot, it prompts you to enable SAVE to use it.

**Comment by foundscapes** [comment]
Awesome, thank you! Looks fantastic!!

**Comment by foundscapes** [comment]
@roseregina make sure to test orbot on different networks (ex: ensure it auto-resumes when you go from cell to wifi)

**Comment by n8fr8** [comment]
there is a new release candidate for Orbot btw, that should be used for testing here:
https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7

it will be rolling out on Play and F-Droid soon, but isn't there yet.
