### ISSUE TITLE
Difficult to get back to app when sharing outside app

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#21]
This may be an android-specific issue and unsolvable, but it'd be great if it were possible to get back into the OA app. without having to hit the "back" arrow multiple times after media shared via other apps (twitter/fb, etc.). It's not very intuitive, would be great to have some way to get straight back to the OA app.

**Comment by foundscapes** [comment]
Oh and the other thought is that when you do go back, it takes you to the last image you uploaded, perhaps going to homescreen would be more intuitive as well.

**Comment by n8fr8** [comment]
I will see if I can tune this better but generally this is an Android thing. Hitting the back button is just part of Android life, and the behavior is different depending upon the app you are sharing with.
