### ISSUE TITLE
Dropbox login not working

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#211]
0.2.3-beta-2
MotoG
GalaxyS7

Expected Behaviour: 
1. Select Dropbox (BETA) from "Connect Your Space" page
2. Log in to Dropbox account (through browser) 
3. Select "Allow" on the Dropbox permissions page
4. Briefly, the "Log in" page within _**Save**_ is visible (barely noticeable most of the time, but I've fairly consistently seen it once I started looking) 
5. Be taken to "Add a Project" page for the Dropbox space

Actual Behaviour: 
1. Select Dropbox (BETA) from "Connect Your Space" page
2. Log in to Dropbox account (through browser) 
3. Select "Allow" on the Dropbox permissions page
4. Be taken to "Log in" page within _**Save**_
5. It just stays there forever. I timed it to 45 seconds, but I think that it will actually stay there for minutes or until the phone sleeps. 
6. The only way to leave the "log in" page is to click the back arrow in the upper left corner, which takes me back without completing the Dropbox login/ setup process.

In trouble shooting this, I found: 
* Force quitting Orbot from via Settings > Apps had no impact, nor did changing to stronger or weaker wifi. I do not think this is a connectivity issue as I am able to add Nextcloud servers successfully. 
* If I had not first set up a different server already, it takes me back to the start of the onboarding screens. 

**This means that Dropbox is unusable and all Dropbox functionality is untestable in 0.2.3-beta-2**

**Comment by n8fr8** [comment]
Regarding Orbot, did you test Dropbox without Orbot/Tor enabled as well?

**Comment by n8fr8** [comment]
I just tested Dropbox here on Pixel 3A over Wifi, without Tor enabled in Save, and I can connect, login, browser folders, upload, etc.

**Comment by n8fr8** [comment]
regarding "If I had not first set up a different server already, it takes me back to the start of the onboarding screens."

If you have no spaces setup, it will take you back to onboarding. That is the current flow if there are no spaces configured. Happy to have other guidance from @foundscapes for another alternative.

**Comment by n8fr8** [comment]
Side note - why did you force stop Orbot? Was it frozen?

**Comment by roseregina** [comment]
I forced stopped Orbot as part of trying to narrow down what was happening and because I am testing the basic functionalities without Orbot first and then making sure that they work with Orbot

**Comment by tladesignz** [comment]
Since @n8fr8 is now working on this, I guess it doesn't make a lot of sense to try to interfere here. So I'll remove myself again.

**Comment by foundscapes** [comment]
> regarding "If I had not first set up a different server already, it takes me back to the start of the onboarding screens."
> 
> If you have no spaces setup, it will take you back to onboarding. That is the current flow if there are no spaces configured. Happy to have other guidance from @foundscapes for another alternative.

I think this is the right UI for now

**Comment by foundscapes** [comment]
I have also had login issues with dropbox with the infinite loop. However, it's likely due to me having two dropbox accounts and I had no trouble logging in today.

However, I was able to add my dropbox accounts twice, which seems like a bug. Shall I make a separate issue @n8fr8? 
<img width="339" alt="Screen Shot 2020-05-18 at 3 25 50 PM" src="https://user-images.githubusercontent.com/2231711/82265475-e302ce00-991b-11ea-8805-cb8cd4fa6ad1.png">

**Comment by foundscapes** [comment]
@n8fr8 I noticed on the ios version that once you've logged into dropbox, it's no longer an option to add another dropbox server. this could work as a fix for multiple logins to same dropbox account.

**Comment by n8fr8** [comment]
We can technically support multiple Dropbox accounts. The issue is just with the browser integration.

If we want to limit it to just one Dropbox account for now, we can do that, until we are able to integrate the browser login more directly.

**Comment by tladesignz** [comment]
I don't remember much of trying to support multiple Dropbox accounts in iOS, but I think it was sort of possible. But more on the line of  logging out of Dropbox and then re-login with the other account. Didn't fit well in our model, so I now only allow one Dropbox account.

Just in case you were thinking of having that on both versions. It's possible, but will feel kinda ugly!

**Comment by n8fr8** [comment]
For now, we'll just limit it to one. I think the solution would be to use a new WebView instance that has a clean session each time, so would require a fresh login. Relying on the system web browser which persists the login is what is causing the confusion.

**Comment by purvi-ranawat** [comment]
@foundscapes  / @n8fr8 : This is working fine on Android 10 and Android 5.1 (Samsung A70 and Samsung J3)
