### ISSUE TITLE
New build constantly crashing

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#213]
Save 0.2.3.BETA-2
Phone: Pixel3a
OS: Android 10
Sever: oa.thegood.cloud

First Try:
Steps:
1. Download apk
2. Open Save 
3. Enable Orbot
4. connect to GoodCloud oa.thegood.cloud
5. click add project
6. Browse Existing
7. Crashed - report emailed to you

Second Try:
Steps:
1. Download apk
2. Open Save 
3. connect to GoodCloud oa.thegood.cloud
4. click add project
5. Browse Existing
6. 10 second blank screen then projects showed up
7. Add 3 images
8. Uploading as expected - but still from bottom of queue not top - issue #202

**Comment by foundscapes** [comment]
Save 0.2.3.BETA-2
Phone: Pixel3a
OS: Android 10
Sever: DropBox

First Try:
Steps:

1. Open Save
2. Enable Orbot
3. connect / login to DropBox
4. Create new project
5. Crashed - report emailed to @n8fr8 
6. opened dropbox login screen, was connected
7. Chose dropbox account
8. Nothing happens when I click - does not go back to Save
9. Went back to Save, was still logged into DropBox
10. successfully uploaded 3 images

@roseregina please test the following:
w/ Internet Archive with orbot enabled
all servers w/ proofmode and orbot enabled
all servers w/ proofmode and NOT orbot enable

**Comment by n8fr8** [comment]
Will review the crash report.

**Comment by foundscapes** [comment]
Save 0.2.3.BETA-2
Phone: Pixel3a
OS: Android 10
Sever: DropBox
Orbot Disabled
Proofmode Enabled



1.  Delete Orbot
2. Open Save
3. connect / login to DropBox
4. Enable Proofmode
5. Browse existing/ chose folder
6. selected 3 images
7. successfully uploaded
8. @n8fr8 - checked and files are in dropbox folder but I don't see a pgp key in the json file - added to issue #208

**Comment by n8fr8** [comment]
Created tickets #215 and #216 from crash reports

**Comment by n8fr8** [comment]
From the crash reports from you and @roseregina it seems the vast majority of the reports were showing the same issue - that a media item from a project folder that was "Removed from App" was still trying to upload in the background and getting confused.

**Comment by foundscapes** [comment]
So the projects weren't actually being removed? Is that a fix you can make?

**Comment by foundscapes** [comment]
Save 0.2.3.BETA-3
Phone: Pixel3a
OS: Android 10
Sever: oa.thegood.cloud

1. download orbot
2. open save
3. enable orbot
4. enable proofmode
5. enable upload only on wifi
6. connect to oa.thegood.cloud server
7. choose existing project (pixel3aNC)
8. upload three photos successfully
9. delete project folder
10. open another existing project - "photos"
11. upload three photos successfully - 

@n8fr8 cannot reproduce first crash w/ oa.thegood.cloud

**Comment by foundscapes** [comment]
@roseregina can you test w/ DropBox and IA with same conditions (proofmode/orbot enables, creative commons off)

**Comment by n8fr8** [comment]
> So the projects weren't actually being removed? Is that a fix you can make?

they were, but there was some lingering stuff in member. all good now.
