### ISSUE TITLE
Option under App Settings/Networking to turn on onion routing when I've deleted Orbot

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#214]
Save 0.2.3.BETA-2
Phone: Pixel3a
OS: Android 10

A fix would be - after uninstalling orbot - Save has prompt to reinstall orbot for any projects with the selected option to turn on onion routing in app settings/networking

AND if orbot isn't on phone, do not give option to turn on onion routing in app settings/networking

**Comment by n8fr8** [comment]
This is more a feature than a bug, but will do what we can.

**Comment by foundscapes** [comment]
@ozgegn would you be able to help figure out if this is doable?

**Comment by n8fr8** [comment]
@ozgegn if you look at the NetCipher library that Save is referencing, it should provide what you need to detect if Orbot is installed or not, and hide/show or disable/enable the "Route through Tor" options.

https://github.com/guardianproject/netcipher

**Comment by ozgegn** [comment]
Hi,
Pr is -> https://github.com/OpenArchive/Save-app-android/pull/253

And I added a warning string as "Please install Orbot to enable"
