### ISSUE TITLE
Unexpected permissions discrepancy between testing phones

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#219]
This is not an issue per se, but is here as part of the testing documentation. I do not believe this to be caused by _**Save**_. 

0.2.3-BETA-3
MotoG 
GalaxyS7

The requested permissions are different on the two devices, with the MotoG displaying what I would expect and the GalaxyS7 claiming that no special permissions are needed.

MotoG: 
![image](https://user-images.githubusercontent.com/15040203/81768822-93e31600-94a1-11ea-95f0-73950191763f.png)

GalaxyS7:
![image](https://user-images.githubusercontent.com/15040203/81767595-66489d80-949e-11ea-8d25-077224b7853c.png)

This is not the first time that I thought I saw this. I can't say that it has had any impact, but I find the discrepancy concerning given that this is one of the testing devices and it may mean that we are not getting as accurate testing results as were believed or that the S7 settings are configured in a way that will not mirror the experiences of expected users. I believe that I had previously seen a more expected permissions request before on the S7, but I found a mirroring of permissions request when installing F-Droid on both devices as a test earlier this evening. 

I am confident that I uninstalled the older version before installing this beta: 
![image](https://user-images.githubusercontent.com/15040203/81768735-60a08700-94a1-11ea-837f-a24026738400.png)
![image](https://user-images.githubusercontent.com/15040203/81768751-6ac28580-94a1-11ea-9d96-5f083d7d5fd4.png)

**Comment by johnhess** [comment]
@purvi-ranawat can you check that we're requesting the same permissions across phone models and close if so?

**Comment by purvi-ranawat** [comment]
@johnhess I got the same message "Do you want to install this app? Cancel, OK" and no other message was displayed.

I have tested on Samsung Galaxy -A13, M32, and A70.
