### ISSUE TITLE
Remove "Share Link" and keep "Share Media"

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#22]
This would depend on how easy it is to remove the media once sharing. Seems so on the platforms I've shared on, so that one could just send the link if they really wanted by deleting the media. I am sure this option is there to take file size / bandwith into consideration, but it'd be great if we had only one option for folks vs. two, if possible!

**Comment by n8fr8** [comment]
I think there are cases where you want to publish once to IA, and then tell people via tweet, status update, message, etc "hey i just put up this great video, go watch it". This is especially true on platforms that don't support video very well, like Twitter and WhatsApp, or where you may want to send someone an email about something you published, without a huge attachment.

Let's talk through this more at a future design session.

**Comment by foundscapes** [comment]
Thanks for the explanation!

Sure thing.

**Comment by hiromipaw** [comment]
I think this was redone as part of the design update.
