### ISSUE TITLE
Create ability for auto-tagging within organizations or more broadly?

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#221]
I'd be interested in scoping this functionality as it's come up in many conversations with community groups. Is it possible?

**Comment by johnhess** [comment]
What is auto-tagging, @foundscapes?

**Comment by foundscapes** [comment]
This is in reference to GPS / location tagging

**Comment by hiromipaw** [comment]
@foundscapes have we considered this during the design update or we should keep this issue open?

**Comment by foundscapes** [comment]
Let's close as we are not moving forward with this
