### ISSUE TITLE
Crashes when logging in to IA account

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#223]
0.2.3-Beta-3

MotoG
GalaxyS7

Internet Archive account

Expected Behaviour: 
1. Selected Archive.Org from Server Screen
2. Enter credentials and login
3. Taken to next screen

Actual Behaviour: 
1. Selected Archive.Org from Server Screen
2. Enter credentials and login
3. App crashes

As well as: 
1. Selected Archive.Org from Server Screen
2. Click login _without_ entering credentials
3. App crashes

Crash reports sent for both processes from both phones.

**Comment by ozgegn** [comment]
Pr about that issue ; 
https://github.com/OpenArchive/Save-app-android/pull/237
