### ISSUE TITLE
Not able to upload the media sometimes in Beta 4 build in Android

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#224]
Steps to Reproduce : 

1. Stop the Orbot
2. Install the Save and Enable for Onion Routing
3. Create new private server for good cloud (Onion Routing is already enabled)
4. Create new project
5. Add Media to the project 

Note : As Orbot is stopped, media will not be uploaded

6. Now again go to Server and disable Onion Routing
7. Go to Project and upload the media

Expected Result  : 
As Orbot is stopped and Onion routing is disabled, media should be uploaded successfully

Actual Result : 
If the Orbot is stopped and Onion routing is disabled, media is not uploaded. Instead the error is displayed in the upload screen.

Attached is the screenshot : 
![image](https://user-images.githubusercontent.com/8190141/84346724-40fa9c80-abce-11ea-9aab-0f3682bc8ba2.png)

.

**Comment by n8fr8** [comment]
This has to be related to Tor network issues.

**Comment by foundscapes** [comment]
@elric-wamugu please test

**Comment by elric-wamugu** [comment]
Resolved on Android 11. Tested with Google Pixel 4a and Save app version 0.2.3-RC-1

**Comment by purvi-ranawat** [comment]
@foundscapes This is working fine now. tested on Samsung Galaxy A70, Android 11.
