### ISSUE TITLE
Photos hang when importing to Save

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#225]
Person tried to upload a photo from camera roll and took a photo within app - both attempts hung on “importing” for over 10 minutes when using - did not resolve over extended time. This was done in the MENA region if relevant.

Server: oa.thegood.cloud 
Cell service: 4G
Phone: Pixel 2 
OS: Android 11
<img width="402" alt="Screen Shot 2020-11-11 at 11 43 06 AM" src="https://user-images.githubusercontent.com/2231711/98856869-129a1b00-2413-11eb-93a9-d71ecb1aef64.png">

**Comment by foundscapes** [comment]
updated photo

**Comment by foundscapes** [comment]
We tried to reproduce the issue above - but it resolved :)

It's uploading media today but we have a UX issue - there is no indication that media has been uploaded. We need a UX fix to show the status for most recent uploads since it shows time/date of prior uploads below but only once you add new media and it does not show date stamps for new items.
Please see video below:

[signalvid.mp4.zip](https://github.com/OpenArchive/Save-app-android/files/5617938/signalvid.mp4.zip)

**Comment by ozgegn** [comment]
Hi @n8fr8 , @foundscapes 

Pr is added ; 
https://github.com/OpenArchive/Save-app-android/pull/238

We can talk about a UI improvement to move this to a progress bar or notification.
