### ISSUE TITLE
Incorrect title for NextCloud/GoodCloud/DropBox folders. Picking upload date instead of date of capture/creation

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#226]
#### Issue description

Folders in NextCloud/GoodCloud/DropBox are named with the upload date of the file instead of the date of capture/creation.

This has happened to one of our community partners across Android and iOS versions so will add to iOS issues as well.

Phone: Google pixel 2
OS: Android 10

#### Steps to reproduce the issue
1. Upload any file from an Android or iOS device to either of the connected cloud services i.e NextCloud/GoodCloud/DropBox.
2. Open the cloud service where the file was uploaded to, and check the name of the parent folder where that file has been saved.

#### What is the expected result?
Folders should be titled by date of capture which should be picked from the file's metadata, not by date of upload

#### What's the actual result?
The title of the uploaded file's parent folder is picking the date of upload instead.

#### Additional details / screenshot
![metadataissue3](https://user-images.githubusercontent.com/2231711/102421405-3542c500-3fb9-11eb-82d3-98cb1ab45c87.jpeg)
[metadataissue1.pdf](https://github.com/OpenArchive/Save-app-android/files/5706151/metadataissue1.pdf)
[metadataissue.pdf](https://github.com/OpenArchive/Save-app-android/files/5706153/metadataissue.pdf)

**Comment by helyxchase** [comment]
heres a photo displaying the incorrect dropbox file name and creation date in JSON metadata file - along side the correct metadata pulled from the image file using Media Info
![Screen Shot 2020-12-22 at 1 59 08 PM](https://user-images.githubusercontent.com/50552020/102923594-fe0f6080-445d-11eb-971b-ddcc9214d577.png)
the above image file was created on 2020-11-07 but is listed in the SAVE metadata as created on 2020-11-23 which was the date of upload into dropbox via SAVE app

**Comment by foundscapes** [comment]
We need to test this for Internet Archive, but it will likely be the same naming issue

**Comment by foundscapes** [comment]
We also need to make sure folders have capture date after upload for ios as well @tladesignz

**Comment by tladesignz** [comment]
There's already a lengthy discussion about this here:
https://github.com/OpenArchive/Save-app-ios/issues/182

Please make sure to answer all the open questions first. I will not start implementing before.

**Comment by foundscapes** [comment]
Will do @tladesignz

**Comment by ozgegn** [comment]
Fixed with https://github.com/OpenArchive/Save-app-android/pull/240/files
