### ISSUE TITLE
Arrow on last welcome screen is not visible

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#227]
phone: Google pixel 2
OS: Android 10 

A community partner said that the arrow on the last welcome screen is not visible, so people don't know to continue to "add project"

will add screenshots asap

**Comment by ozgegn** [comment]
Button color on last welcome page is updated as white regarding to used library. PR ;
https://github.com/OpenArchive/Save-app-android/pull/232

**Comment by ozgegn** [comment]
Tested on Pixel 2 API 29

<img width="389" alt="Screen Shot 2021-03-22 at 23 14 06" src="https://user-images.githubusercontent.com/7272389/112052597-5a207880-8b64-11eb-856e-418b490b25e4.png">
