### ISSUE TITLE
Incorrect value for the `createDate` field in the uploaded file's metadata JSON file

### ISSUE THREAD

**Issue by elric-wamugu** [OpenArchive/Save-app-android#228]
#### Issue description

The file's creation date that is populated in the uploaded file's metadata JSON is incorrect. The value seems to be the file's upload date instead of the actual capture/creation date.

#### Steps to reproduce the issue

1. Upload any file from an Android or iOS device to either of the connected cloud services i.e NextCloud/GoodCloud/DropBox.
2. Open the cloud service where the file was uploaded to
3. Open to view the corresponding metadata JSON file of the uploaded file
4. Check the `createDate` value and compare it to the actual creation date of the file in your device.

#### What's the expected result?

The `createDate` value in the uploaded file's metadata JSON file is the actual date of creation/capture

#### What's the actual result?

The `createDate` value in the uploaded file's metadata JSON file is its upload date timestamp.

#### Additional details / screenshot
![102923594-fe0f6080-445d-11eb-971b-ddcc9214d577](https://user-images.githubusercontent.com/2143671/106060826-38bf8500-60fd-11eb-95bc-36c2879a9fcf.png)
[metadataissue.pdf](https://github.com/OpenArchive/Save-app-android/files/5706153/metadataissue.pdf)

**Comment by suryanshsangwan** [comment]
Hi can i pick up this issue

**Comment by elric-wamugu** [comment]
Hello @suryanshsangwan Yes please.

**Comment by suryanshsangwan** [comment]
App crashes every time i click on **dropbox** and on the **check** button after putting internet archive keys.

**Comment by suryanshsangwan** [comment]
I tried it on enmulator as well as on a physical device.

Any solution??

**Comment by ozgegn** [comment]
Hi ,

PR is https://github.com/OpenArchive/Save-app-android/pull/240

Cc: @foundscapes
