### ISSUE TITLE
Hashes not matching original file hash

### ISSUE THREAD

**Issue by elric-wamugu** [OpenArchive/Save-app-android#229]
### Issue description

Hashes not matching original file hash

### Steps to reproduce the issue

1.  
2. 

### Additional details / screenshot

**Comment by elric-wamugu** [comment]
@foundscapes Any additional info on this issue?

**Comment by elric-wamugu** [comment]
@foundscapes I found a reference of the same issue but on iOS devices here: https://github.com/OpenArchive/Save-app-ios/issues/182

Maybe we can think of and come up with a way to curate all the issues from both platforms under one unified repository for easier triage across the project. Let's discuss.

**Comment by foundscapes** [comment]
@elric-wamugu good idea - all I have is in https://github.com/OpenArchive/Save-app-ios/issues/182

**Comment by ozgegn** [comment]
Hey @foundscapes ,
As far as I understand from linked issue, it must be resolved with filename fix. Could you please test ?

**Comment by elric-wamugu** [comment]
@ozgegn re-testing this on both platforms

**Comment by foundscapes** [comment]
Thanks @elric-wamugu for testing and @ozgegn for helping!

**Comment by foundscapes** [comment]
@elric-wamugu what was the outcome of this test?

**Comment by foundscapes** [comment]
@ozgegn is creating a new apk for myself and @elric-wamugu  to test - Ozge - please add a link here as well as our slack distro channel. thank you!

**Comment by elric-wamugu** [comment]
Both issues are resolved on Android 11. Tested with Google Pixel 4a and Save app version `0.2.3-RC-1`
