### ISSUE TITLE
Archive.org account setup crash

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#234]
REPORT_ID=0a822078-62dc-48a2-9d47-68ad1ecb3318
APP_VERSION_NAME=0.2.3-RC-1
APP_VERSION_CODE=20321
ANDROID_VERSION=10
PHONE_MODEL=POCO F1
PACKAGE_NAME=net.opendasharchive.openarchive.release
CRASH_CONFIGURATION=assetsSeq=0
	colorMode=9
	densityDpi=440
	fontScale=1.4
	hardKeyboardHidden=HARDKEYBOARDHIDDEN_YES
	keyboard=KEYBOARD_NOKEYS
	keyboardHidden=KEYBOARDHIDDEN_NO
	locale=en_IN
	mcc=405
	mnc=857
	navigation=NAVIGATION_NONAV
	navigationHidden=NAVIGATIONHIDDEN_YES
	orientation=ORIENTATION_PORTRAIT
	screenHeightDp=737
	screenLayout=SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO
	screenWidthDp=392
	seq=52
	smallestScreenWidthDp=392
	touchscreen=TOUCHSCREEN_FINGER
	uiMode=UI_MODE_TYPE_MASK+UI_MODE_NIGHT_YES
	userSetLocale=false
	windowConfiguration={ mBounds=Rect(0, 0 - 1080, 2246) mAppBounds=Rect(0, 89 - 1080, 2116) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0}
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at net.opendasharchive.openarchive.services.archivedotorg.ArchiveOrgLoginActivity$UserLoginTask.onPostExecute(ArchiveOrgLoginActivity.java:244)
	at net.opendasharchive.openarchive.services.archivedotorg.ArchiveOrgLoginActivity$UserLoginTask.onPostExecute(ArchiveOrgLoginActivity.java:208)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

APPLICATION_LOG=N/A
BUILD=BOARD=sdm845
	BOOTLOADER=unknown
	BRAND=Xiaomi
	CPU_ABI=arm64-v8a
	CPU_ABI2=
	DEVICE=beryllium
	DISPLAY=QKQ1.190828.002 test-keys
	FINGERPRINT=Xiaomi/beryllium/beryllium:10/QKQ1.190828.002/V11.0.9.0.QEJMIXM:user/release-keys
	HARDWARE=qcom
	HOST=c3-miui-ota-bd152.bj
	ID=QKQ1.190828.002
	IS_DEBUGGABLE=false
	IS_EMULATOR=false
	MANUFACTURER=Xiaomi
	MODEL=POCO F1
	PERMISSIONS_REVIEW_REQUIRED=true
	PRODUCT=beryllium
	RADIO=unknown
	SERIAL=unknown
	SUPPORTED_32_BIT_ABIS=["armeabi-v7a","armeabi"]
	SUPPORTED_64_BIT_ABIS=["arm64-v8a"]
	SUPPORTED_ABIS=["arm64-v8a","armeabi-v7a","armeabi"]
	TAGS=release-keys
	TIME=1593988890000
	TYPE=user
	UNKNOWN=unknown
	USER=builder
	VERSION.ACTIVE_CODENAMES=[]
	VERSION.BASE_OS=Xiaomi/beryllium/beryllium:10/QKQ1.190828.002/V11.0.8.0.QEJMIXM:user/release-keys
	VERSION.CODENAME=REL
	VERSION.FIRST_SDK_INT=27
	VERSION.INCREMENTAL=V11.0.9.0.QEJMIXM
	VERSION.PREVIEW_SDK_FINGERPRINT=REL
	VERSION.PREVIEW_SDK_INT=0
	VERSION.RELEASE=10
	VERSION.RESOURCES_SDK_INT=29
	VERSION.SDK=29
	VERSION.SDK_INT=29
	VERSION.SECURITY_PATCH=2020-06-01
IS_SILENT=false
USER_CRASH_DATE=2020-10-04T10:14:20.415+05:30

**Comment by n8fr8** [comment]
If spaceId is null, it must have been deleted, and this was some kind of background task race condition. 

You should just complete the task without a NPE.

**Comment by n8fr8** [comment]
the bigger question is why this is possible... perhaps before deleteing a space, we should keep track of all asynctasks and make sure they are canceled?

this could also be addressed by moving to Kotlin and use a coroutine tied to the lifecycle of the Activity.

**Comment by ozgegn** [comment]
I've got this error on register. Any delete isn't operated I guess. It seems like the Space isn't initialized at all.

**Comment by ozgegn** [comment]
Hi @n8fr8 ,

About that issue ; https://github.com/OpenArchive/Save-app-android/pull/237
