### ISSUE TITLE
Unable to acquire keys for the IA - button not responsive

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#246]
Two people, same issue:

Phone: Redmi Note 7 Pro 
OS: Android 10
&
Phone: Galaxy A10
OS: Android 9
 
These two people had trouble acquiring keys for the IA:
The Redmi Note 7 Pro person: When I am trying to login via Internet Archive, it doesn't show up the option to login or sign up to Internet Archive, video here: https://files.slack.com/files-pri/T01RRRK31BM-F01T36YHPJR/save 

The Galaxy person: when I proceeded to  acquire the keys of the Archive account, the button simply did't work when I touch it.
![Screenshot_20210402-084732_Save](https://user-images.githubusercontent.com/2231711/115087971-1bac7e00-9ec4-11eb-89d7-01b2e7249e06.jpg)

**Comment by ozgegn** [comment]
Hi,
Pr is opened for this issue; https://github.com/OpenArchive/Save-app-android/pull/252
