### ISSUE TITLE
Create New Project Functionality is Erratic on Save App 

### ISSUE THREAD

**Issue by Ghranty** [OpenArchive/Save-app-android#248]
## Prerequisites:

Orbot is enabled

## Case:
A Project is previously created, select add button on the top left of the screen, then select Create New Project

## Expected result:
The application brings up a screen to type new project name

## Actual result:
Application opens a blank page and no further response

## Notes:
Reproduced on Huawei Y9s, Android 10 version

Issued moved from [here](https://github.com/OpenArchive/open-archive.org-Website-2019/issues/35)

**Comment by purvi-ranawat** [comment]
@foundscapes @n8fr8 

Unable to reproduce the issue on Samsung A70 android 11.
