### ISSUE TITLE
Moving an Item/Upload up the Queue is not Functional on the App

### ISSUE THREAD

**Issue by Ghranty** [OpenArchive/Save-app-android#249]
## Prerequisites:
Orbot is enabled

## Case:
Create a project and select items for upload, then click on upload. Open the upload queue and drag an item or items up the queue

## Expected result:
The new item on top of the queue gets upload priority

## Actual result:
Item kept moving all the way down again.

## Notes:
Reproduced on Huawei Y9s, Android 10 version

Issue moved from [here](https://github.com/OpenArchive/open-archive.org-Website-2019/issues/36)

**Comment by elric-wamugu** [comment]
@foundscapes works as expected on:
Device: Google Pixel 4a
App version: 4.1
Android version: 11

**Comment by purvi-ranawat** [comment]
@foundscapes 
Working as expected., tested on Samsung Galaxy A70, Android 11.
