### ISSUE TITLE
Browse Existing Projects is not Functional on Save App

### ISSUE THREAD

**Issue by Ghranty** [OpenArchive/Save-app-android#250]
## Prerequisites:
Download Save by OpenArchive on PlayStore
Orbot is enabled

## Case:
Create a project or couple of projects and make uploads. Click on the icon on the top left of screen. Select "Browse Existing Projects"

## Expected result:
See a list of existing projects and make a selection

## Actual result:
The app opens a blank page and nothing else happens

## Notes:
Reproduced on Huawei Y9s, Android 10 version

Issue moved from [here](https://github.com/OpenArchive/open-archive.org-Website-2019/issues/37)

**Comment by elric-wamugu** [comment]
@foundscapes works as expected.
Tested on:
App version: 4.1
Device: Google Pixel 4a
Android version: 11

![Screenshot_20210525-115004](https://user-images.githubusercontent.com/2143671/119469284-e0695e80-bd4f-11eb-87cd-cd020eaf13a6.png)

**Comment by purvi-ranawat** [comment]
@foundscapes @n8fr8 

Able to reproduce the issue on Samsung A70 android 11. Please find below the video link:

https://drive.google.com/file/d/1MUJrA-EybLdgh90jx7Tx8pVlxcP7MZcn/view?usp=sharing

**Comment by elric-wamugu** [comment]
@purvi-ranawat Please check on the above device if it's working for Dropbox

**Comment by purvi-ranawat** [comment]
@elric-wamugu The app is getting crashed when trying to access drop box. Please see the video:

https://drive.google.com/file/d/1MkWTmC7T26E1pkZ8JxUJ6RMuCwZY3eUo/view?usp=sharing

**Comment by purvi-ranawat** [comment]
@elric-wamugu I have downloaded from Google Playstore and not facing the above mentioned issues with Dropbox.

**Comment by purvi-ranawat** [comment]
@elric-wamugu Can reproduce the issue on latest apk. Also getting Bad request error with Dropbox. I have attached the screenshot dropbox.JPG for the same.

![dropbox](https://user-images.githubusercontent.com/8190141/122040048-01741b00-cdf5-11eb-9b50-5f3452a6263d.jpg)

**Comment by elric-wamugu** [comment]
Getting the above error too with the latest .apk file @ozgegn

**Comment by n8fr8** [comment]
Confirmed as well for WebDAV/Nextcloud, as well as crash when trying to add Dropbox.

**Comment by ozgegn** [comment]
Hi,
PR is created.

https://github.com/OpenArchive/Save-app-android/pull/264
