### ISSUE TITLE
Next Step after Creating an Account on Internet Archive to Acquire Keys is not Intuitive enough on Save App

### ISSUE THREAD

**Issue by Ghranty** [OpenArchive/Save-app-android#251]
## Prerequisites:
Download Save by OpenArchive on PlayStore
Orbot is enabled

## Case:
Select Internet Archive. Click on Acquire Keys, then select the signup option and sign up for an account. Verify email after signup

## Expected result:
Application takes you to the acquired keys screen or shows a button to click

## Actual result:
Application takes one to the homepage where it was unclear what to do next 

## Notes:
I had to go back and sign-in the account I created which then automatically took me to the generated keys screen
Reproduced on Huawei Y9s, Android 10 version

Issue moved from [here](https://github.com/OpenArchive/open-archive.org-Website-2019/issues/38)

**Comment by foundscapes** [comment]
More of a feature than a bug - I think we just need better UX - a popup? to explain to folks how to get back to Save once logging in and acquiring keys on the IA site

**Comment by n8fr8** [comment]
I would only use the "PLEASE TEST" label once new code has been pushed and needs testing.

**Comment by foundscapes** [comment]
I made a tag "please reproduce" for situations like these - does that make sense @n8fr8?

**Comment by purvi-ranawat** [comment]
@foundscapes @n8fr8 

For Internet Archive after creating account, I got the link which says Click here to login, on clicking that link I got Acquire key screen, on clicking on the tick mark on Acquire key screen it takes me to the home page. Below is the video link for the same:

https://drive.google.com/file/d/1MGZf6NyphocUHrOTK1mujDOVmLt7vV3F/view?usp=sharing

Tested on Samsung A70 android 11

**Comment by elric-wamugu** [comment]
Confirmed to be also working as expected on Android 11 on Google Pixel 4a

**Comment by foundscapes** [comment]
Great news - can we close @elric-wamugu ?
