### ISSUE TITLE
Main screen project grid view is cut-off

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#259]
**Describe the bug**
The top line of text, either showing "# items(s) upload" or "Ready to upload" is cut-off from view 

**To Reproduce**
1. Get latest build from DEVELOPMENT
2. Open main screen to a project
3. Add items

**Expected behavior**
"Ready to upload" should be visible.

**Screenshots**
It is not visible!

**Environment (please complete the following information):**
 - OS version: Android 10
 - Device: Pixel 4A
 - App Version : Latest DEV branch build

**Comment by Ananyaas** [comment]
Hi, Can I work on this issue ? Thanks.

**Comment by ozgegn** [comment]
Hi,
PR is created
https://github.com/OpenArchive/Save-app-android/pull/263
