### ISSUE TITLE
Sharing App's Ordering

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#26]
For the archivers/peeps:

twitter
whatsapp
instagram
facebook
gmail
email
drive
picasa
messaging (? not sure what this refers to ?)
direct message
bluetooth
hangouts

**Comment by n8fr8** [comment]
This isn't something you can control. Android generates the share menu automatically based on what the user has installed and what they have recently used.

**Comment by foundscapes** [comment]
Ah, cool, thanks!
