### ISSUE TITLE
Error is displayed when we upload the media and it is shown as 100%

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#266]
Summary : After selecting the media and clicking on Upload, after uploading is 100% complete, "Error" text is shown for the media uploaded

1. Go to Save App
2. Click on "+" icon in the project to select the media
3. Select any photo or video and click on upload

**Expected behavior**
Photo / Video should be uploaded successfully

Actual Result : 
After the media uploading is 100% complete, it shows "Error" text

Below are the screenshot

![Error](https://user-images.githubusercontent.com/8190141/141303980-31215384-cb0c-4073-a617-deba7422116f.jpeg)

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy A70
 - App Version : 0.2.4-RC-2

Note : I have tried this on GoodCloud login for Save

**Comment by ozgegn** [comment]
Hi @purvi-ranawat ,
Can we see the error ? Or is media uploaded to the space that wanted ?

**Comment by johnhess** [comment]
@purvi-ranawat can you see if this is still happening on 0.2.4-RC-5?

**Comment by purvi-ranawat** [comment]
This is working fine. Now once the media is uploaded, it is removed from Upload pane and once all the media are uploaded, Upload Pane is empty
