### ISSUE TITLE
Even after the media is shown as 100% uploading, the text "uploading: is only displayed

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#268]
Summary :  
After selecting the media for uploading, once the media is uploaded , it is shown as "100%" but the text still shows as "Uploading". Instead it should convert to "Uploaded" else user might get confused if the media is still uploading or not

Steps to Reproduce : 

1. Open Save App
2. Click on + icon for selecting the media for uploading'
3. Select the media and click on Upload
4. Click on the number (total number of media remaining to be uploaded) and see the media upload status

Expected Result : 
When the media is 100% uploaded, the text should change to "Uploaded" besides the media

Actual Result : 
Even when the media is 100% uploaded, the text still displays "Uploading" which confuses the user if it is still uploading or uploaded fully

Below is the screenshot  : 
![image](https://user-images.githubusercontent.com/8190141/141612285-e9540a49-8309-4832-99d0-e3c690a89968.png)

**Comment by ozgegn** [comment]
Hi @purvi-ranawat , @n8fr8 
The condiitons says if the status of media is 4 or 5 update the status text as "Uploading". Should it be updated for 5 ?
STATUS_UPLOADING = 4
STATUS_UPLOADED = 5

**Comment by purvi-ranawat** [comment]
@ozgegn  : I think once the uploading of the media is 100% completed, the status should be shown as "Uploaded" so the user does not gets confused between which media is uploaded and which is still uploading.

@n8fr8 : Can you confirm the same?

**Comment by tladesignz** [comment]
On iOS, we remove items, which are done.
There's also the common status displayed in the title bar:

![Simulator Screen Shot - iPhone SE1 @ iOS 15 - 2022-04-08 at 14 07 38](https://user-images.githubusercontent.com/117089/162432461-df62a148-14bc-4a2e-a7a3-f7c885c4a067.png)
 
I suggest to adapt the Android version to the behaviour of the iOS version, including brushing up the styling (e.g. more space between elements)

**Comment by tladesignz** [comment]
@johnhess is that an acceptable plan?

**Comment by johnhess** [comment]
Love it.  Solves the problem and consistency!  Let's go with that.

**Comment by tladesignz** [comment]
Ok, I had a little time here in a very boring conference, so I started off with Android development.
Cleaned up code, fixed lint warnings and improved UI a little.

Now stumbled across the fact, that the problem is not, that done items aren't filtered, but obviously done items are not set to status `UPLOADED`. Will need more time to investigate, as there seems to be code in the middle of conversion from Java to Kotlin resulting in 2 listener objects which should set the status but obviously not doing it.

Additionally, is there any knowledge on how the localization workflow is in this project? I changed 2 strings, so will need to push to localization platform. (Transifex?)

**Comment by johnhess** [comment]
> there seems to be code in the middle of conversion from Java to Kotlin

Do you have a sense of whether this is an isolated issue or if there seems to be a lot of WIP/duplication elsewhere in the project?

> Additionally, is there any knowledge on how the localization workflow is in this project?

Not with me.  @n8fr8 could you give us the cliffs notes on translation for Save Android?

**Comment by pkhivesara** [comment]
@purvi-ranawat Should be fixed in latest release.

**Comment by purvi-ranawat** [comment]
@johnhess  / @pkhivesara : This is working fine now. Now once the media is uploaded, it automatically gets removed from the Upload Pane
