### ISSUE TITLE
When we add dropbox as the server, after allowing the Save app to access the media, dropbox id is displayed as blank

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#269]
Summary : When we add dropbox as the server and allows the Save app to access the media, dropbox id is displayed as blank. Only when we click on back and click on dropbox server, the dropbox id is displayed

Steps to Reproduce : 

1. Go to Save app
2. Click on '+" icon to add the space
3. Select dropbox for the space
4. Click on Sign in with Google option for drop box
5. Select Allow for Save app access to the phone media
6. Verify the dropbox id

Expected result : 
Google id for the dropbox should be displayed

Actual Result : 
Blank is displayed as the dropbox id after we click on allow for Save app access to the phone media. Only after click on back button and click on dropbox id, google id is displayed as the dropbox id

Below is the video link : 
https://drive.google.com/file/d/1JFtnt9i2GmnXeud_OCOoisieE6eu3A4_/view?usp=sharing

**Environment 
 - OS version:  Android 11
 - Device: Samsung Galaxy A70
 - App Version : 0.2.4-RC-2

**Comment by ozgegn** [comment]
PR; https://github.com/OpenArchive/Save-app-android/pull/276

**Comment by purvi-ranawat** [comment]
This is working fine . Hence closing the issue
