### ISSUE TITLE
Closing a project which is no longer required could take fewer clicks

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#271]
Summary : When we have several projects open for the space and if we wish to close the project, there is no way that we can close the project. There should be "x" icon besides each project so that user can close the project which are no longer required

Steps to Reproduce : 

1. Go to Save App
2. Open multiple projects for any of the space
3. Try to close the project which are no longer in use for any of the space

**Expected behavior**
There should be "x" icon besides each and every project name to close the project which are no longer in use

Actual Result : 
No "X" icon is besides any of the project to close the project. 

Below is the video link : 

https://drive.google.com/file/d/1JuOuyr26YHUN5ErypW_SsGB53r5u40PD/view?usp=sharing

**Environment 
 - OS version: Android 11
 - Device: Samsung Galaxy A70
 - App Version : 0.2.4-RC-2

**Comment by n8fr8** [comment]
If you tap on the space icon, and then see "Project Settings" and then tap on the name of a project there, you will be given the "Remove from App" option.

Was the "X" icon something you expected from a design reference, or is this more a feature request from you?

**Comment by ozgegn** [comment]
Hi @n8fr8 @purvi-ranawat  ,
Any comments or decision about that issue ?

**Comment by purvi-ranawat** [comment]
@n8fr8 / @ozgegn : I think this can be a feature request as it will be easier for the user close the project instead of going through few steps
