### ISSUE TITLE
Blank screen is displayed when we click on Browse Existing Project for the dropbox space

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#273]
Summary : When we click on Browse Existing Projects for the dropbox, blank screen is displayed even though we have several projects with the media in the dropbox

1. Go to Save App
2. Select Dropbox space which already have several projects (with already uploaded media) added to it
3. Click on + icon on the space to select / create the project
4. Click on Browse Existing Project

**Expected behavior**
If the projects already exists with media in dropbox, it should be available for selection in Browse Existing project

Actual Result : 
Browse Existing project is blank for dropbox

Below is the video lilnk : 
https://drive.google.com/file/d/1N8D8GsI2kDONapZn7HCH2Q4zh_kxj7Al/view?usp=sharing

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy A70
 - App Version : 0.2.4-RC-2

**Comment by LordDewi** [comment]
This same problem occurs with an Internet Archive project.

OS: Android 11
Device: Motorola G Power 2020
App Version: 0.2.3-RC-1 (From Play Store on 12/06/21)

**Comment by ozgegn** [comment]
PR is opened ; https://github.com/OpenArchive/Save-app-android/pull/275

**Comment by purvi-ranawat** [comment]
@ozgegn  : The issue still exists. Still I am getting Blank screen when I click on Browse Existing Projects for dropbox space even though there are few existing projects

**Comment by ozgegn** [comment]
Sorry my bad, I sent the wrong package. I will update it asap @purvi-ranawat

**Comment by purvi-ranawat** [comment]
It works fine.
