### ISSUE TITLE
Proof is not uploaded

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#277]
**Describe the bug**
Despite having Proofmode installed, running in the background, with maximal permissions, and turning on proofmode in Save, no proof appears in Dropbox.

**To Reproduce**
1. Install Save
2. Install and enable proofmode with all permissions
3. Enable proofmode within save
4. Take a photo in save and upload it to an existing project

**Expected behavior**
Upload to storage (dropbox) would include a proof.

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung A21
 - App Version 0.2.4-RC-1

**Additional context**
This _may_ be related to [a bug in Proofmode](https://github.com/guardianproject/proofmode/issues/88).  The same images that did not upload a proof did not have a contemporaneous proof generated according to Proofmode.

However, even when I manually generate proof before attempting to upload in Save, the proof does not appear in Dropbox on upload.

**Comment by n8fr8** [comment]
Proofmode app is not required since Proofmode Lib is built into Save. Why it’s not being uploaded is a question tho.

**Comment by tladesignz** [comment]
Is this only not working in Dropbox? It seems the respective code is in a class specific to Dropbox. Without getting in the weeds now, this smells heavily like there is a refactoring necessary.

**Comment by pkhivesara** [comment]
> Is this only not working in Dropbox? It seems the respective code is in a class specific to Dropbox. Without getting in the weeds now, this smells heavily like there is a refactoring necessary.

It turns out proof upload fails for private server as well on Android. Should I fix and refactor for that as well @johnhess ?

**Comment by johnhess** [comment]
I have no reason to believe this is isolated to Dropbox.  I mention what I did just so folks can replicate.

**Comment by pkhivesara** [comment]
@purvi-ranawat Was this resolved in the new build?

**Comment by purvi-ranawat** [comment]
@pkhivesara  : 

a) This is not yet resoved. Enabling / Disabling of proofmode in Save app does not impact the upload in dropbox. ,I am not able to see the proof when I upload in dropbox even though proofmode is enable in Save app.

b) I can upload the proof manually created by me through proofmode app.

**Comment by purvi-ranawat** [comment]
@pkhivesara It works fine for Dropbox and Nextcloud. However, proof or asc. files are not uploaded on Internet Archive

Tested version 0.2.4-RC-7.84eb59d

**Comment by tladesignz** [comment]
> @pkhivesara It works fine for Dropbox and Nextcloud. However, proof or asc. files are not uploaded on Internet Archive
> 
> Tested version 0.2.4-RC-7.84eb59d

Yeah, no. Internet Archive is very different from Dropbox and Nextcloud. It isn't a file storage, but an asset storage where assets also contain metadata. We need to look into the spec, and see if we could somehow add the Proofmode metadata.

https://github.com/vmbrasseur/IAS3API/blob/master/metadata.md

**Comment by purvi-ranawat** [comment]
It works fine for Save version 0.2-4-RC-8.6775082
