### ISSUE TITLE
"Done" button in onboarding slideshow is invisible

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#279]
**Describe the bug**
Upon install, the user is presented with a set of slides explaining the app.  The last slide explains that the user can "Save over Tor" and has a button "Enable".  There's also a button in the bottom right for those not inclined to "Enable" that says "Done", but the text of that button is the same color as the background (blue green).

The button should be visible. 

**To Reproduce**
1. Install Save App (or uninstall then reinstall)
2. Page through onboarding slideshow
3. On last slide, observe there is no ">" or "Done" button visible.

**Expected behavior**
The button is visible.

**Screenshots**
![Screenshot_20220412-151834_Save](https://user-images.githubusercontent.com/1799120/163037744-480a896b-4404-49e5-8cbe-40a1ee00cb61.jpg)

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy A21
 - App Version: 0.2.3-RC-1

**Additional context**
Ozge merged [a fix for this](https://github.com/OpenArchive/Save-app-android/pull/232).  This appears code complete, but not fixed in our production release.

**Comment by pkhivesara** [comment]
This seems to be fixed on master. Let me know if there is anything else to be done on this ticket @johnhess
