### ISSUE TITLE
warn user about risks of embedded metadata

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#28]
> 1) Given that their original media will be available, will users be aware
> of what metadata they are embedding in their video before they upload it?

At this point, there is no analysis of the media they are importing. I think we could perhaps have a popup to let them know about apps like ObscuraCam or just a gentle reminder about metadata, privacy, and the like.

**Comment by foundscapes** [comment]
@hiromipaw this is something we're doing for the current audit, right? Please close if redundant. ty!

**Comment by hiromipaw** [comment]
@foundscapes we are not warning the users. This is something you could do through training maybe or add it to our documentation?
