### ISSUE TITLE
Image not uploaded to NextCloud

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#280]
**Describe the bug**
Images are not uploaded to NextCloud.  A folder for the image is created but neither the image file nor the metadata file appear on the server, nor does the app reflect the upload succeeded.

**To Reproduce**
1. Install Save
2. Provide valid creds for NextCloud Server
3. Create new project
4. Select a single file and upload it.

**Expected behavior**
The file is uploaded to NextCloud and the image gray-out goes away.

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy A21
 - App Version: 0.2.3-RC-1

**Additional context**
No error is presented to the user.  The image remains gray for those who know what that means and you can select the image and click "upload" but it never uploads.

If we have trouble replicating this and we suspect it has to with the specifics of my NextCloud, I'm happy to share the NextCloud creds I'm using (it's just a free Tab one).

**Comment by pkhivesara** [comment]
@tladesignz @johnhess Seeing some rather interesting behavior. ``PUT`` request via OkHttp3/Sardine seems to fail on physical devices, but not on the emulator. I tried uploading a 7KB image through the device, and the connection is reset half way through from the server. Its almost as it the connection is dropped because of some server config.

The file in question: ``WebDAVSiteController.kt#transferred(bytes:Long)``

Keep seeing the following error:
> Failed primary media upload: https://sam.nl.tab.digital/remote.php/dav/files/pk@oaktreeapps.com/ff/2022-05-25T12:52:39GMT-04:00/20220524_191253.jpg: stream was reset: NO_ERROR

If either one of you has any insights into this, that would be much appreciated!

**Comment by tladesignz** [comment]
No idea why that happens. Some ideas for debugging, though:

- Use your own Nextcloud server and have a look at the logs there.
- Check the reference lifetime of the OkHttp / Sardine objects. There might be differences in the Garbage Collector which removes unreferenced objects earlier on the device than in the simulator, which might lead to a sudden transfer stop.

**Comment by johnhess** [comment]
@purvi-ranawat could you share the OA goodcloud login with @pkhivesara so we can see if there's something particular about tab.digital?  Alternatively, perhaps just test against that and let us know what you get.  That would let us rule out tab.digital as the cause.

**Comment by purvi-ranawat** [comment]
@pkhivesara @johnhess I use the following credentials for OA,thegood.cloud
server: oa.thegood.cloud
username: OA_Tester
pw: gogo2021_$

**Comment by tladesignz** [comment]
> @pkhivesara @johnhess I use the following credentials for OA,thegood.cloud

That was not a good idea. This website is world-readable and indexed by search engines. Please change password immediately and only share credentials via private messaging. Encrypted messaging, at best!

**Comment by pkhivesara** [comment]
@purvi-ranawat Should be fixed in latest release.

**Comment by purvi-ranawat** [comment]
@johnhess @pkhivesara 

Uploading to OA.thegood.cloud was successful, however, not able to upload on nextcloud (sam.nl.tab.digital). It keeps on processing.

Tested on Android 11 for Save version 0.2.4-RC.5

**Comment by pkhivesara** [comment]
@purvi-ranawat The uploading of the image on NextCloud takes some time. I believe on an average of 10-11 seconds. Of course, the bigger the image, the more time it needs. Could you retest this and let me know what do you see?

**Comment by purvi-ranawat** [comment]
@pkhivesara It keeps on processing but never uploads, I tried with 1.3 MB size and waited for few minutes.  The issue is with sam.nl.tab.digital, it works fine with OA.THEGOOD.CLOUD

Attached the screenshot. 


![WhatsApp Image 2022-06-16 at 11 13 15 PM](https://user-images.githubusercontent.com/8190141/174133673-f982c719-802a-488c-bc24-9c9a19867a13.jpeg)

**Comment by pkhivesara** [comment]
I am seeing a different behavior as seen in the video. Am I missing something here?

https://user-images.githubusercontent.com/6237488/174150040-f6f485a6-5cb0-42e1-abc1-e948fb47039a.mov

**Comment by purvi-ranawat** [comment]
@pkhivesara After reinstalling the app, images are showing as uploaded in mobile device, but still the folder is not created in nextcloud (sam.nl.tab.digital)

**Comment by pkhivesara** [comment]
@purvi-ranawat I have attached a video to this link which shows the file being uploaded and the same being visible within nextcloud: https://we.tl/t-Wj7pX13lMr

Can you perhaps share a recording of what is the behavior on your end

**Comment by purvi-ranawat** [comment]
@pkhivesara : Please find attached the video for the same.


https://user-images.githubusercontent.com/8190141/174332841-de78d43c-c556-481d-afd0-291c5fa1a54f.mp4

**Comment by pkhivesara** [comment]
@johnhess @purvi-ranawat NextCloud has two identifiers for its users, email and username. The WebDav upload URLs are based off the username, not email. Using the username/password combo to login fixes this issue.

**Comment by purvi-ranawat** [comment]
@johnhess Images are getting uploaded when using the Username instead of email for NextCloud.

**Comment by johnhess** [comment]
@pkhivesara is there a way we can validate that a user isn't feeding an email-which-is-not-a-username into that form or, one better, identify the username regardless of whether or not they've used it or their email-which-is-not-a-username?

Mostly, I'd just like to take the sharp edges off.

**Comment by johnhess** [comment]
Moving this over to in progress.  If the above comment is already addressed/mooted, feel free to move it back.  Otherwise, let's fix the trapdoor of being able to log in with something that'll break downstream.

[Shameless plug to my preferred mental model for these kinds of issues](https://en.wikipedia.org/wiki/Poka-yoke)

**Comment by pkhivesara** [comment]
@johnhess So I looked into the possibility of getting a username from a login. I dont see any such fields in Sardine right now. And I dont see anything in webdav APIs for nextcloud either. Any suggestions?

**Comment by johnhess** [comment]
2 non mutually exclusive options:

1. We create a new ticket with a title that describes the issue (username v. email causes failures) until we can identify a way to self-correct the issue (e.g. detect the username based on the email).
2. [Half-solution] Implement a self test that lets a user know at login that uploads aren't working and says something along the lines of "make sure you're logging in with your username which may be different than your email address."

1 would change from high priority (a failure users can't fix for themselves) to low priority (annoying UX to be told "no, try again") if 2 were implemented.

I'll close this ticket, but reference it in the new ones for 1 & 2.
