### ISSUE TITLE
On Onboarding last slide, Start / Open button should be there for Orbot if it is already installed

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#282]
Describe the bug : 
 Pre-requisite : Orbot is already installed before Save App

When we have already installed Orbot and then install and access Save App for the first time, on last slide of Onboarding, for Orbot (Save over Tor), Install is displayed for Orbot. But as we have already installed Orbot before Save, it should either say "Start" to start the orbot or anything relative if orbot is already started.

**To Reproduce**
1. Install Orbot first
2. Install Save App after Orbot installation
3. Access Save App
4. Move to last onboarding slide

**Expected behavior**
If Orbot is already installed, on last onboarding slide, for Orbot, instead of "Install" , it should display "Start" or anything relative to the status of Orbot if Orbot is already started

Actual Result : 
 Even if Orbot is installed, on last onboarding slide, it is displayed Install for Orbot

Below is the screenshot :  

![image](https://user-images.githubusercontent.com/8190141/163923389-9c69e037-235e-4e43-afce-a90abd8903a8.png)

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy M32
 - App Version : Save 0.2.3-BETA-3

**Comment by pkhivesara** [comment]
@purvi-ranawat Should be fixed in latest release

**Comment by purvi-ranawat** [comment]
It works fine for Save 0.2.4-RC-5

**Comment by johnhess** [comment]
[Release](https://github.com/OpenArchive/Save-app-android/tree/0.2.4-RC-6) sent to internal testing [download APK](https://play.google.com/apps/test/net.opendasharchive.openarchive.release/20436)
