### ISSUE TITLE
Upload not stopping when editing/resorting the upload list

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-android#283]
Currently, the `UploadService` is stopped, but that doesn't do it most of the times.
There needs to be a flag in the database, which controls pausing.

Refer to iOS version, how it's done there.

**Comment by johnhess** [comment]
@tladesignz you've assigned this to yourself.  Do you intend to handle this one personally?

**Comment by johnhess** [comment]
From what I can gather from the title of this issue, I'm not sure that's a bug.  Is it that the upload doesn't stop _during_ the resorting?  Or that once resorted, the top most item is not uploading because the previously top most item is continuing?

**Comment by tladesignz** [comment]
Well, my idea was to adapt to the behaviour we have in iOS, but you talked me into implementing something else:

https://github.com/OpenArchive/Save-app-ios/issues/202#issuecomment-1142534597

So, this issue needs to adapt, too, I guess.

The reason why I am assigned is, yes, I planned on doing this, but this was back then when there was no Pratik.

**Comment by johnhess** [comment]
Blocked waiting on iOS reference implementation

**Comment by tladesignz** [comment]
Expected behaviour now:
- Keep finished uploads around until user leaves management scene.
- Remove finished uploads on *leave* **and** on *enter* of management scene. (To make up for situations, where a user never leaves the scene, but the app gets killed instead.)
- Don't stop uploading when reordering.
- Allow reordering of *all* uploads, regardless of their state.

**Comment by johnhess** [comment]
Next step is for our incoming interaction designer to take a look (hopefully give the 👍, then implement a matching behavior on Android.
