### ISSUE TITLE
Login UI needs to be cleaned up to highlight server url field

### ISSUE THREAD

**Issue by pkhivesara** [OpenArchive/Save-app-android#284]
**Describe the bug**
The login UI on Android app does not highlight the fact that server url field is a editable one.

**Steps to reproduce the behavior**
   - Install Save     
   - Walk through the initial onboarding screens
   - Select 'Private Server' option
   - Observe the ``WebDAV/Nextcloud Server`` field

**Expected behavior**
 The field needs to be appear consistent with the other fields on the login page. The current field makes it appear as if its uneditable.

 **Environment (please complete the following information)**
   - OS version: Android 11
   - Device: Samsung Galaxy S20
   - App Version: 0.2.4-RC-1

**Comment by johnhess** [comment]
Could you share a screenshot @pkhivesara?

**Comment by johnhess** [comment]
AFAICT, both @pkhivesara and I struggled the first time we tried to login to the NextCloud, mistaking "server name" for a URL field.

We eventually clued into the correct field usage (which, yes, is *technically* clear on what's what), but it seems like a potential stumbling block we can remove.

**Comment by pkhivesara** [comment]
@purvi-ranawat Should be fixed in latest release.

**Comment by purvi-ranawat** [comment]
It works fine for Save 0.2.4-RC.5
attached the screenshot:



![Image](https://user-images.githubusercontent.com/8190141/174050616-cc6bdd9e-46f6-417d-9597-63449d402ea7.jpeg)

**Comment by johnhess** [comment]
[Release](https://github.com/OpenArchive/Save-app-android/tree/0.2.4-RC-6) sent to internal testing [download APK](https://play.google.com/apps/test/net.opendasharchive.openarchive.release/20436)
