### ISSUE TITLE
App closes when we click on Add a Project text

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#290]
When we install the app and configure Dropbox, Internet Archive or any other server, and click on Add a Project text, app closes.

Steps to reproduce:
1. Install the app 
2. Configure Internet Archive or Drobox
3. Click on Add a Project text

**Expected results**
Add a Project screen should be displayed with options like Browse Existing Projects, and Create New Project

**Actual results**
App closes and home screen of the mobile gets displayed

 - OS version: Android 11
 - Device:  Samsung Galaxy M32
 - App Version 0.2.4-RC-4

Note it works fine when we click on Plus (+) sign

https://user-images.githubusercontent.com/8190141/171838403-721d581e-d25e-4ebb-8b43-ef3d1086ccfa.mp4

**Comment by purvi-ranawat** [comment]
@pkhivesara The issue still exist for Dropbox and Goodcloud, whenever the app is installed and configured with this servers. Tested on android 11 for Save: 0.2.4-RC.5

**Comment by pkhivesara** [comment]
@purvi-ranawat This was fixed 2 days ago I believe. Will be available in the upcoming build.

**Comment by purvi-ranawat** [comment]
It works fine for Save 0.2.4-RC-6-3ba7fdb
