### ISSUE TITLE
App freezes on "uploads" pane

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#299]
When Uploading multiple files and clicking the circled number (to go to the "Uploads" list view), the percentages never change.  In my replications, they all remained at 0%.  After a while, when clicking "Edit" to resort, I get the message that the app is not responding.  

**To Reproduce**
1. Select several photos to upload
2. Click the circled number at the top right to see the upload pane
3. Wait (I waited ~30seconds)
4. Attempt to click "edit"

**Expected behavior**
I can resort the list of uploads by clicking edit.  The progress reflected for each image is accurate.

**Actual behavior**
App Freezes.  Progress remains at 0% even though some images have been uploaded. 

**Screenshots**
![Screenshot_20220613-214352_Save](https://user-images.githubusercontent.com/1799120/173475952-0c0895a5-3b4f-4fe9-a9d5-7d3b1f38c6a8.jpg)

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy A21
 - App Version 0.2.4-RC-5

**Comment by purvi-ranawat** [comment]
This is working fine now. I have tried uploading more than 10 images and videos at once and it haven't freezed. It uploaded successfully. 

Environment : 

OS Version : Android 11
Device : Samsung Galaxy M32
App Version : 0.2.4-RC-6

**Comment by johnhess** [comment]
Glad to hear it's fixed.

@purvi-ranawat I *just* built and pushed up 0.2.4-RC-6 up to internal testing.  I suspect we might have a naming collision here with the release you used and the "real" one that's tagged in the repository/uploaded to the play console's internal testing track.

If this isn't a typo, @pkhivesara can you be sure to name dev builds with reference to their commit hash so there's not collisions in the future?  I feel like if this were broken in 0.2.4-RC-6 and fixed in 0.2.4-RC-6 we'd all go a bit mad.
