### ISSUE TITLE
The same dropbox space can be added twice

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#300]
**To Reproduce**
1. Add Dropbox Space to app 
2. [If necessary, add IA space to app]
3. Add new dropbox space to app using same credentials

**Expected behavior**
A de-duplicated set of spaces is presented.  Possibly an informative message would say that I've already got a space with these credentials.

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy A21
 - App Version 0.2.4-RC-5

**Comment by purvi-ranawat** [comment]
@johnhess : Currently I am not able to add the dropbox twice. Once we have added the dropbox, I am not seeing the dropbox option again. Is this fine?

**Comment by johnhess** [comment]
No, I think it should allow you to add a (different) dropbox.  It just shouldn't let you create the same space (e.g. spaces with identical creds)

**Comment by johnhess** [comment]
bouncing this one over to assigned/adopted so that multiple non-identical dropbox spaces can be allowed.

**Comment by pkhivesara** [comment]
Fixed. Will be made available in the next build in RC7.

**Comment by purvi-ranawat** [comment]
It works fine now.

Tested version 0.2.4-RC-7.84eb59d
