### ISSUE TITLE
Proof *.csv.asc is sometimes not uploaded

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#307]
While proofmode is enabled, sometimes, the .asc file is not also uploaded.  

**To Reproduce**
1. Enable proofmode
2. Upload one or more files (I used an existing nextcloud project)

**Expected behavior**
one proof .csv and one .csv.asc are uploaded for each file I've uploaded.

**Actual behavior**
Sometimes, the .csv.asc is missing.  In one multi-file upload, a single .csv.asc was missing (but one .csv.asc, both images, both meta.json, and both .csv files were uploaded).

 - OS version: Android 11
 - Device: Samsung Galaxy A21
 - App Version 0.2.4-RC-5
 - NextCloud service: sam.nl.tab.digital

**Comment by purvi-ranawat** [comment]
@pkhivesara It works fine for Dropbox and Nextcloud. However, proof or asc. files are not uploaded on Internet Archive

Tested version 0.2.4-RC-7.84eb59d

**Comment by purvi-ranawat** [comment]
It works fine for Save version 0.2-4-RC-8.6775082
