### ISSUE TITLE
IA Sign In time-out issue - intermittant

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#31]
It's happened twice today and I've been able to log in once:

Screen goes white when I try to log in, then I get the following error:

"webpage not available" the "webpage at link could not be loaded because net::ERR_TIMED_OUT

When I can log in, it seemed to lag a bit, perhaps about 15 seconds

**Comment by n8fr8** [comment]
Not something we can really control. We just open a browser to the IA, and if the connection is bad, then so it goes. Now, in the future, we should figure out a better way to login, sign-in, etc that doesn't require a web page, and has more of a visual feedback.
