### ISSUE TITLE
Get ready for Android app red team audit

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#313]
This is a tracking ticket for work we'll want to do before handing an APK over to the OTF red team auditors.  Please comment here (or create a new issue and comment about it below) if there are things we'll want to fix or consider fixing before then.

**Comment by johnhess** [comment]
**Some current concerns raised in scrum mtg w/ @pkhivesara:**

* Permission `READ_EXTERNAL_STORAGE`
    * We are reading external storage, would an attacker decompiling our APK be able to make use of this permission?
* Legacy permission flag `requestLegacyExternalStorage`
    * Circumvents new model which better protects the user
    * Might be at risk of deprecation (was going away in Android 30; developers fought that)
* GPS Location fine
    * Would we rather a different model, and what do we need for Proof generation?

**Comment by johnhess** [comment]
Leaving in backlog for now since we may not want to move on this ticket until the iOS audit comes back.

**Comment by hiromipaw** [comment]
We are already half way through the android audit. Closing.
