### ISSUE TITLE
Media uploaded successfully on previous day shown as processing when we access the app next day

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#318]
**Describe the bug**

1. Access Save App on first day
2. Upload few media on Save App
3. Access Save App on next day

Expected behavior : 
Media uploaded on the previous day should be visible correctly on the next day when we access the Save App if we have not deleted the same.

Actual Result : 
Media uploaded successfully on previous day keeps on processing when we access the Save App on Next day.

Screenshots : 

![image](https://user-images.githubusercontent.com/8190141/177148790-7c993eb8-03c0-4f56-a8d9-094c3041e332.png)

Environment 
 - OS version: Android 11
 - Device: Samsung Galaxy M32
 - App Version : 0.2.4-RC-6

**Comment by pkhivesara** [comment]
@purvi-ranawat I am not able to recreate this. Can you please provide a video recording of the issue.

**Comment by purvi-ranawat** [comment]
@pkhivesara It happens mostly with Dropbox. 


https://user-images.githubusercontent.com/8190141/178216911-f0529276-0efa-4822-ba40-29e88a952993.mp4

**Comment by pkhivesara** [comment]
Can this be combined with https://github.com/OpenArchive/Save-app-android/issues/265. Seems to be the same.

**Comment by purvi-ranawat** [comment]
@pkhivesara : Yes. We can combine this issue with #265. It was for the media which were not uploaded. 
 
This is happening for images and videos both on dropbox

**Comment by johnhess** [comment]
John to replicate/tag

**Comment by johnhess** [comment]
Set this up and will check in a day to see how it looks.  Worked fine surviving quits/reboots.

**Comment by johnhess** [comment]
I'm also unable to replicate (Samsung Galaxy A21, Android 11, 0.2.4-RC-8).

Let's mark this as blocked until we can find another device that replicates the same issue.  To the future replicator: please comment here with details, remove the "blocked" tag, and assign this issue to myself or to @pkhivesara.

**Comment by johnhess** [comment]
Closing this as #265 has been closed.
