### ISSUE TITLE
About Page language update/refinement

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#32]
OpenArchive is a free, open-source mobile application dedicated to maintaining the privacy, provenance, and preservation of your media. It enables you to add metadata and Creative Commons licensing to your audiovisual media and then send it to the Internet Archive over Tor. Thus offering more agency over your media, while protecting civil liberties and increasing interoperability for those who want to find and reuse/remix it in the future.

OpenArchive is developed in partnership with the Internet Archive, StoryMaker, Scal.io, and Guardian Project, with generous support from the Knight Foundation, and founded by Natalie Cadranel.

**Comment by n8fr8** [comment]
How about

"OpenArchive is developed in partnership with the Internet Archive, StoryMaker, Scal.io, and Guardian Project.

The project was founded by Natalie Cadranel with the generous support of the Knight Foundation's Prototype Fund".

**Comment by foundscapes** [comment]
Perfecto!

**Comment by foundscapes** [comment]
Ok final language:

OpenArchive is a free, open-source mobile application dedicated to maintaining the privacy, provenance, and preservation of your media. It enables you to add metadata and Creative Commons licensing to your audiovisual media and then send it to the Internet Archive over Tor; thus offering more agency over your media, while protecting civil liberties, and increasing interoperability for those who want to find and reuse/remix it in the future.

OpenArchive is developed in partnership with the Internet Archive, StoryMaker, Scal.io, and Guardian Project. The project was founded by Natalie Cadranel with the generous support of the Knight Foundation's Prototype Fund.

**Comment by foundscapes** [comment]
Ok final FINAL language:

OpenArchive is a free, open-source mobile application dedicated to maintaining the privacy, provenance, and preservation of your media. It enables you to add metadata and Creative Commons licensing to your audiovisual media and then send it to the Internet Archive over Tor; thus offering more agency over your media, while protecting civil liberties, and increasing interoperability for those who want to find and reuse/remix it in the future.

OpenArchive is developed in partnership with the Internet Archive, StoryMaker, Scal.io, and Guardian Project. The project was founded by Natalie Cadranel with generous support from the Knight Foundation's Prototype Fund.

**Comment by foundscapes** [comment]
Oh no, THIS is actually the FINAL language. that "thus" was really bothering me. Hopefully I did not misuse that semi-colon!

OpenArchive is a free, open-source mobile application dedicated to maintaining the privacy, provenance, and preservation of your media. It enables you to add metadata and Creative Commons licensing to your audiovisual media and then send it to the Internet Archive over Tor; offering more agency over your media, while protecting civil liberties, and increasing interoperability for those who want to find and reuse/remix it in the future.

OpenArchive is developed in partnership with the Internet Archive, StoryMaker, Scal.io, and Guardian Project. The project was founded by Natalie Cadranel with generous support from the Knight Foundation's Prototype Fund.
