### ISSUE TITLE
Implement a self-test to poka-yoke username-based login

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#322]
[See #280 from which this issue and #321 were forked]

When a user logs in to WebDAV servers using their email and password (where their email != their username), uploads can subsequently fail.  This took our team a whole day to debug so we can reasonably expect most users will not be able to fix this for themselves without some assistance.

Let's implement a self-test to check if the user can make API calls against storage (likely a write/read/delete) and serve them an error message with helpful text (e.g. "You wont be able to upload with these credentials, make sure you're logging in with your username instead of your email.") and take them back to the create workspace page.

As we implement, let's be mindful that this is an 80% solution and we hope to one day tear it out (e.g. if we can detect a username from a successful email).

**Story**
As a user, I'd like an indication that my credentials are insufficient for uploading when I log in to WebDAV/Next Cloud so that I can correct them.

**Comment by purvi-ranawat** [comment]
@johnhess  When user tries to login with email,  the following message gets displayed: 
 "Login failed. Please try logging in with your usrname instead of ... "

**Comment by johnhess** [comment]
@purvi-ranawat that's intended. 

While it stinks that they can't log in both ways and have it just work, we'd rather they log in using a method that ensures they'll be able to upload.  I would say this is WAI

**Comment by johnhess** [comment]
Will release!
