### ISSUE TITLE
Update fails when we try to update on the previous build

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#324]
Pre condition : Save app from the previous build should already be installed

Steps to reproduce : 
1. Download the latest Save installer
2. Install Save app from the latest build on the previous build Save App

Expected behavior : 
Save app from the latest build should be updated on the previous build

Actual Result : 
On Installing the latest build on the previous build, it says "App not installed"
Note : Latest build is successfully installed if we uninstall the save app from the previous build and then  install the latest version
Below is the video : 

https://user-images.githubusercontent.com/8190141/177473694-758c2d7b-d5e3-417a-a9f0-fe5096266991.mp4

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy M32
 - App Version : 0.2.4-RC-7

**Comment by pkhivesara** [comment]
@purvi-ranawat This is more of a device issue than an app issue. There might be settings on the device that might be causing. Closing.
