### ISSUE TITLE
On Enabling the Proofmode, wrong permission pop up is displayed

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#325]
1. Go to Save App for the first time
2. Click on space name on top
3. Click on Metadata under App Settings
4. Enable ProofMode

Expected behavior : 
Permission pop up should not be displayed and proofmode should be enabled successfully

Actual Result : 
"Allow Save app to make and manage phone calls?" permission pop up is displayed even though phone calling is not the functionality of Save app

Below is the screenshot : 

![image](https://user-images.githubusercontent.com/8190141/177775940-c274a039-e53d-4729-89a0-9ba3a626db9e.png)

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy M32
 - App Version : 0.2.4-RC-7

**Additional context**

**Comment by pkhivesara** [comment]
@purvi-ranawat That permission is required to be able to generate proof and all its associated files successfully. Without that permission, the app will only generate the proof file but not the csv and the asc.csv files.
