### ISSUE TITLE
Batch Edit Protip is not displayed when multiple photos and videos are being uploaded

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#334]
While uploading, when we select multiple photos and videos, batch edit protip should be displayed . But currently on Android, the protip is not displayed

Below is the video link :  

https://drive.google.com/file/d/1YnfqjWoc2MkCcHH7gFqnnAvVh8cPzOf2/view?usp=sharing

Environment (please complete the following information) : 
 - OS version: Android 11
 - Device: Samsung Galaxy 32
 - App Version : 0.2.4-RC-9

**Comment by pkhivesara** [comment]
@purvi-ranawat Can you provide a screenshot of the protip that you see on iOS? Shall try to match the same UI.

**Comment by purvi-ranawat** [comment]
@pkhivesara Please find attached the screenshot of protip on iOS



![Image](https://user-images.githubusercontent.com/8190141/181672887-202ff35e-d721-439d-bd22-888ec1cd06b4.jpeg)

**Comment by pkhivesara** [comment]
@purvi-ranawat I am seeing the protip on Android. Note that this appears only the first time.



![Image](https://user-images.githubusercontent.com/6237488/182864205-c303ad6e-0cb4-447d-a7d8-c038446c4c7b.png)

**Comment by purvi-ranawat** [comment]
This is working fine now

OS : Android 11
Device : Samsung Galaxy M32
Build : 0.2.4-RC-12
