### ISSUE TITLE
Save "mysteriously" requests permission to manage phone calls when enabling proofmode.  Add context!

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#337]
When enabling proofmode in the Metadata section of settings on 0.2.4-RC-8 for the first time, the app requests permission to manage phone calls.  Our users are privacy conscious.  Assuming this is required for some of the metadata lib_proofmode gathers, can we at least offer some context to the user about why we're asking?  The same context should also explain what happens if you deny permissions.

**Comment by pkhivesara** [comment]
@johnhess Unlike iOS which lets you add some context to the permissions that you are asking, Android does not let you do so. I suppose we would need to figure out some UI/UX here, perhaps at the launch of the app to educate the users on the what permissions and why do we need them.

Is there someone who specifically does design work?

**Comment by johnhess** [comment]
There's not someone at this very moment, but there will be.

**Comment by johnhess** [comment]
@pkhivesara can you please go through all our permissions and add context to our readme?  Eg this one is for Proofmode, etc.  the more the better (eg location is for Proofmode and our metadata and if denied x will happen w each)

**Comment by n8fr8** [comment]
We've updated our libProofMode-Android library and provided improved documentation and sample code here:
https://gitlab.com/guardianproject/proofmode/libproofmode-android-sample

In addition, there is improved UX in the primary ProofMode app related to exposing, sharing, prompting for specific permissions.

**Comment by tladesignz** [comment]
@hiromipaw, what exactly do you want me to do?

**Comment by hiromipaw** [comment]
@tladesignz I think for now we can leave this unassigned. The idea was to do nothing at the moment but to revisit this later when we will review the app UX.

**Comment by n8fr8** [comment]
The libProofMode android library API now offers the ability to set which sensor types are used, and which permissions are requested. There is also UI that can be added to explain why a specific permission is being requested.

In this case, the Android system permission UX Is a bit confusing, since what ProofMode actually needs is access to information about the cellular network your device is connected to. It is not interested in managing or making calls, but there is no granular way to request a lesser permission, unfortunately.

With the ProofMode app, we don't by default enable this feature, and so the user then has to decice to opt-in to it. This provides us time / UX to explain the request to users.

**Comment by foundscapes** [comment]
Thanks for the assist @n8fr8 - the UX is very confusing, it sounds like we may have to disable this by default and do the same thing if there is nothing we can do to remove it entirely without compromising the efficacy of the sensor data collection, is that right? Thoughts @hiromipaw @tladesignz?

**Comment by n8fr8** [comment]
I would just disable it that specific option for now. It isn't essential data for ProofMode.

**Comment by hiromipaw** [comment]
I would say we can disable it. At the same time we should explain the following:

_If you enable this option Android would request permission to manage phone calls on your device on behalf of ProofMode. Note that ProofMode only needs access to information about the cellular network. We are not interested in managing phone calls, but Android doesn't offer an option yet to request more granular permissions._

@tladesignz I'll put this in the pipeline for after the audit.

**Comment by foundscapes** [comment]
Thanks everyone!

**Comment by foundscapes** [comment]
Can we close this now that we created workaround language in **_Save_** 2.0? @hiromipaw
