### ISSUE TITLE
Black screen is displayed on clicking on Preview button on Select Media screen

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#341]
Description of the bug : 

On Select Media screen, after selecting few media and clicking on Preview on bottom left button, Black screen is displayed. Instead the preview should be displayed for the media selected 

Below is the video : 

https://drive.google.com/file/d/1RZm4wKqCdPZmZf6t0AGx2wfWq-KZXdeo/view?usp=sharing

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy M32
 - App Version : 0.2.4-RC-10

**Comment by purvi-ranawat** [comment]
The issue still exists. Black screen is still displayed on clicking on Preview button on Select Media screen

Environment : 

OS Version : Android 11
Device : Samsung Galaxy M32
App Version : 0.2.4-RC-11

**Comment by pkhivesara** [comment]
Yes, this has not been deployed yet. Will be fixed in the next build.

**Comment by purvi-ranawat** [comment]
It works fine for Save 0.2.4-RC-14-1837D48
