### ISSUE TITLE
Images kept on refreshing after selecting every image on Project screen

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#345]
Bug Description : 

After few media selection, without uploading, when we go back to the project screen and select the image / video one by one, everytime, the rest of the images / videos are refreshed and displayed again. Instead it should remain as it is and not refresh again and again

Below is the video :  

https://user-images.githubusercontent.com/8190141/182400299-122278a6-515c-483a-9f66-cbfb775971fb.mp4

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy M32
 - App Version : 0.2.4-RC-10

**Comment by pkhivesara** [comment]
@purvi-ranawat Not able to reproduce this

**Comment by johnhess** [comment]
I am also unable to replicate this (0.2.4-RC-13, Galaxy A21, Android 11), though there is some funny behavior around trying to select-then-upload that I'll file in another ticket.
