### ISSUE TITLE
Upload button should be on project screen whenever media yet to be uploaded are still there and selected on the project screen

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#346]
When there are several media present on the project screen which are yet to be uploaded, then on selecting them, upload button should be available on the project screen itself for better experience instead of clicking on Edit and then clicking on the three dots and then click on upload.

Only if the user wants to update any information, then only they had to go to Edit and update the information and we can have upload there also

Below is the video : 

Uploading WhatsApp Video 2022-08-02 at 8.01.34 PM.mp4…

**Comment by johnhess** [comment]
@pkhivesara please let me know if you think is straightfoward enough to do, and if mimicking iOS is a sufficient solution.  If so, please pursue it.  If it's not, let's tag it as requiring design and pop it on the backlog.

**Comment by pkhivesara** [comment]
@purvi-ranawat can you provide the video for this request.

**Comment by purvi-ranawat** [comment]
@pkhivesara Please find the attached link for the video, let me know if you need any other details.

https://drive.google.com/file/d/1SsUVQxUXtCftj6Gd5tvZmrxf079PKkL6/view?usp=sharing
