### ISSUE TITLE
Document Location Permissions used by Save App

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#350]
In order to republish our app, we need to document the ways in which we use sensitive permission.  Today, the Play Store identifies 3 such permissions in 0.2.4-RC-11 (see `git tag` of the same):

```
android.permission.ACCESS_BACKGROUND_LOCATION
android.permission.ACCESS_COARSE_LOCATION
android.permission.ACCESS_FINE_LOCATION
```

For each of these, they want an explanation including a youtube video showing how it's used.

The scope of this ticket is to document how we use each of those 3 permissions in README.md.  I have an educated guess on how, but I want to be sure we understand precisely how the app and our dependencies are using this data.

One specific question in addition: Why is `ACCESS_BACKGROUND_LOCATION` still shown by Play Store as used by 0.2.4-RC-11 when that no longer appears in the manifest?  Is that a result of a dependency, or do we need to make changes elsewhere?

**Comment by pkhivesara** [comment]
Closing for now.
