### ISSUE TITLE
Select All option should be available if the user wishes to upload all the available images / videos in the folder

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#355]
On Select Media screen, when we select one photo / video, select all option should also be available in case user wants to upload all the media available in the folder. Currently, user have to select the media by clicking on each and every photo / video and it can be tiresome for them.

**Comment by johnhess** [comment]
Which use cases would there be where users want to upload, for example, a whole camera roll?  Are there workflows where people are generating folders of their own on their device they'll then want to upload?

**Comment by johnhess** [comment]
@purvi-ranawat can you respond to the comment above?  I think we talked about it on our calls, but don't want to misstate what you said :-)

**Comment by purvi-ranawat** [comment]
@johnhess : Regarding the Select all button, if the user creates the folder and move all the images / videos there which he wishes to upload later, then on Select Media screen, user just needs to select the folder and then click on Select all checkbox and click on upload. This will be easier for the user to select all the media at once
