### ISSUE TITLE
Find webDAV protocol API to calculate available storage

### ISSUE THREAD

**Issue by pkhivesara** [OpenArchive/Save-app-android#357]
**Describe the bug**
This is an extension of https://github.com/OpenArchive/Save-app-android/issues/319. The current fix only works for NextCloud accounts. Now that we have Hetzner as one of the providers as well, we need to find a way on the webDAV protocol level to calculate available storage before commencing any uploads.

**Comment by johnhess** [comment]
When this is done, a ticket should be created for iOS linking to the PR so that similar logic can be applied there as well.

**Comment by pkhivesara** [comment]
Unable to find an API that works on webDAV level.

**Comment by johnhess** [comment]
Merging with #319
