### ISSUE TITLE
enabling easy setup of Tor onion site for sharing

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#36]
implement easy onion site sharing the same way CameraV support it
- talk with Orbot to get hidden service setup
- run internal HTTP server
- generate simple gallery that allows others to browser, sync, your content

**Comment by foundscapes** [comment]
@n8fr8 is this still an issue?

**Comment by foundscapes** [comment]
@hiromipaw isn't this part of our current roadmap? Can we close or integrate with more relevant issues (across android/ios)?

**Comment by hiromipaw** [comment]
We do not support onion services at the moment. We support so to speak "clearnet" backends. We could think to implement this but maybe first it would be interesting to know if our community needs it.

I think if we enabled the onion from the mobile itself, then the objective of putting the data somewhere safe in case the mobile is taken or stolen is lost. If one wanted to share the file over onion service they could use onionshare instead.

Closing for now.
