### ISSUE TITLE
App Hangs when we click on Browse Existing Projects for Hetzner NextCloud

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#365]
Bug Description :  

When we login into Hetzner NextCloud and click on Browse Existing Projects, app hangs. Instead it should open already existing projects list.

Below is the video : 

https://user-images.githubusercontent.com/8190141/184478536-a2a809d9-54c3-4a1c-af93-e9981b445311.mp4

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Samsung Galaxy A13, Samsung Galaxy M32
 - App Version : 0.2.4-RC-14

**Comment by johnhess** [comment]
Unable to replicate on RC-13, Android 11, Samsung A21
