### ISSUE TITLE
Uploading multiple images on-the-delay causes a crash

### ISSUE THREAD

**Issue by johnhess** [OpenArchive/Save-app-android#368]
**Describe the bug**

**To Reproduce**
1. Select multiple images to upload (I am using nextcloud/hetzner)
2. Rather than hit upload, hit the back arrow next to preview.  The images are now staged for upload on the project page.
3. Click on several staged images so they are selected in blue.  Select the edit pencil.
4. Select the "..." at the top right, then "Upload".  

**Expected behavior**
Uploads

**Actual behavior**
Crash

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy A21
 - App Version: 0.2.4-RC-13

**Comment by purvi-ranawat** [comment]
Unable to reproduce for app version 0.2.4-RC-14. Tested Samsgung A13, Samsung M32.
