### ISSUE TITLE
Need eye icon to view pw when setting up backends (nextcloud/dropbox)

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#369]
**Describe the bug**
Unable to view pw when logging into backends via app 

**To Reproduce**
1. Go to: Private server/set up new server
2. Enter login credentials

**Expected behavior**
There should be an eye icon to click on the PW field in order to ensure you entered the pw correctly

**Actual behavior**
There is no eye/no ability to view password entered. This is especially important If login fails and it is bc of an incorrect pw, there is no way to view password

**Screenshots**
![AndroidPWunviewable](https://user-images.githubusercontent.com/2231711/184719759-90c995ce-16c1-4191-b784-b21bca129cd6.jpeg)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Samsung Galaxy S10
 - App Version: 0.2.4-RC-13

**Additional context**

**Comment by purvi-ranawat** [comment]
Eye icon is getting displayed now to see the password .

Tested on Android 12, Samsgung Galaxy A13. App version 0.2.4-RC-15
