### ISSUE TITLE
Add IA search, display, browse

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#37]
OA should have an integrated search, fav, save, browse user interface for accessing, downloading other content that other OA users have uploaded

**Comment by foundscapes** [comment]
@hiromipaw this would be amazing if we can implement, but given that Save is a write-only app, it may not be our way forward, let's discuss

**Comment by hiromipaw** [comment]
I think this will require us to think about what the user can do with save. Maybe this goes more into the direction of managing what has been archived. I wonder if this is a feature for mobile or something for an admin/desktop application?
