### ISSUE TITLE
Logging into hetzner taking too long or not working

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#372]
**Describe the bug**
I entered correct login information for OA_Admin and NC accts on Hetzner nextcloud and it has now been 7 minutes and counting and I am still seeing the "logging in..." message at the bottom with no login.

**To Reproduce**
1. Choose to connect to private server
2. add credentials (server name, server, username, pw
3. click checkmark to connect in lower right
4. no error listed, it just doesn't log in

**Expected behavior**
It should've logged me in within a few seconds

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS version: OS Android 12
 - Device: Google Pixel 3a
 - App Version: Save 0.2-4-RC-13

**Additional context**
 Note - I was able to login fine with DropBox so this seems to be a hetzer issue usernames/pw's were correct and checked for both multiple times.

**Comment by pkhivesara** [comment]
Can I get login credentials to this? I am not able to reproduce this on my end

**Comment by pkhivesara** [comment]
Seems to be working fine on my local.
![image](https://user-images.githubusercontent.com/6237488/186495277-4d08dd4b-461b-4575-9c3d-f14a0ecb19ea.png)
