### ISSUE TITLE
Add stamp.io bitcoin hash publishing

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#38]
Prove that you had this file and published it a certain time and place, using the blockchain.

http://docs.stampery.com/?shell#introduction

**Comment by elric-wamugu** [comment]
The service seems to be suspended for maintenance for an undefined time, since October 25, 2019. Source: https://telegra.ph/Stampery-Services-Currently-On-Maintenance-10-25

cc @n8fr8 @foundscapes

**Comment by foundscapes** [comment]
@hiromipaw we need to investigate to see if this is still relevant/useful

**Comment by hiromipaw** [comment]
@foundscapes I think we can investigate this via the filecoin research project?
