### ISSUE TITLE
Refactor SugarORM foreign key usage 

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-android#391]
Currently, the SugarORM usage is only half-assed:

Foreign keys are actually declared as `int`s, not as other SugarORM objects.

Therefore, SugarORM has no idea of the relationships and also didn't create any database structures for that. All related objects fetching and handling has to be done by foot.

This already lead to the security issue, that deleting a space didn't delete historic information for that space. This is also a memory-leaking database problem. (See https://github.com/OpenArchive/Save-app-android/pull/388#issuecomment-1371310170)

This has to be done-right(tm) to avoid any future issues of that kind esp. when the code is handed off to another developer.

**Comment by hiromipaw** [comment]
@tladesignz is this still valid?

**Comment by tladesignz** [comment]
Oh, yeah. In the meantime, I added manual code which does deletion of dependent entities and also getter methods, which give you the dependent entities to some of the classes, but this should be really set right.

In other words: there's always going to be more important things to do, so this will never happen. ;-)
