### ISSUE TITLE
Move all networking logic to a single centralized class that generates all HTTP client and WebView objects.

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#399]
We want to refactor how we handle all http clients and webview objects so that is easier to check and enforce networking settings on the app.

**Comment by tladesignz** [comment]
I actually did this recently while refactoring to remedy the Orbot problem.

Here it is: https://github.com/OpenArchive/Save-app-android/blob/master/app/src/main/java/net/opendasharchive/openarchive/services/SaveClient.kt
