### ISSUE TITLE
Reset Your Password Layout

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#40]
Missing Padding

**Comment by n8fr8** [comment]
Maybe we should just launch the full web browser external to the app?

**Comment by foundscapes** [comment]
We should offer PW resets, let's discuss how the UI would look

**Comment by n8fr8** [comment]
We don't manage passwords, so we cannot reset them.

**Comment by foundscapes** [comment]
What I mean is make it easy to change PW in-app - from the server - I assume it's all through the server?

**Comment by n8fr8** [comment]
Let's talk about this in real time today.
