### ISSUE TITLE
Check that Orbot is installed and active if the app is set to upload media through tor.

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#400]
If the app is globally configured to use Tor, failure to detect Orbot should result in a prominent error message explaining that the user should either reinstall Orbot or reconfigure the Save app to use direct HTTP connections.

**Comment by tladesignz** [comment]
Hu? Why is closed?

**Comment by hiromipaw** [comment]
Sorry this was a mistake. I thought we had a duplicate issue, but that's clearly in another repository.

**Comment by tladesignz** [comment]
Fixes contained in latest open testing release:
https://play.google.com/apps/testing/net.opendasharchive.openarchive.release

There's no UI, yet, telling you to install Orbot, if it's unavailable.

The upload seems brittle in situations, where we need to wait for Tor to start. This will only change, after the whole upload infrastructure got an overhaul.

**Comment by tladesignz** [comment]
UI improvements with upcoming build 20528 / version 0.2.5-BETA-7.

**Comment by tladesignz** [comment]
@purvi-ranawat, I'll do another release today. Please test this, if possible also under hard conditions like not-started Orbot or slow connection. Thank you!

**Comment by purvi-ranawat** [comment]
This is working fine.

But there are few issues related to upload media for which I will be opening new issues

Version : Save 0.2.6
