### ISSUE TITLE
Not able to login to dropbox  from Save App

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#413]
Describe the bug : 

On Save App, when we try to login to drop box using the option Continue with Google or manually entering the email id and password, the pop up is displayed asking "OpenArchieve Save would like to access to its own folder. Apps > OpenArchive Save, inside your Dropbox" with Allow and Cancel button. On clicking on Allow, the screen is refreshed and displayed again with the same text and options. Instead, it should successfully allow us to login. 

Below is the link to the video : 

https://drive.google.com/file/d/1_HUmv6xLO7bp_7nbgPN3ckhnncsmD9mi/view?usp=sharing

**Environment (please complete the following information):**
 - OS version: Android 13
 - Device: Samsung Galaxy A13
 - App Version : 0.2.5-RC-15.01bbe9b

**Comment by foundscapes** [comment]
@tladesignz aha I think the issue is that the video doesn't play on Safari, it works fine on Firefox, try that?

**Comment by foundscapes** [comment]
Same happened for me

OS version: Android 12
Device: Google Pixel 3a
App Version : Save 0.2.5-BETA-5

**Comment by hiromipaw** [comment]
@tladesignz can we check why this is happening?

**Comment by tladesignz** [comment]
This will be fixed in versions **after** 0.2.5-BETA-6. Will take a few days until that gets released.

**Comment by tladesignz** [comment]
Currently in open testing: https://play.google.com/apps/testing/net.opendasharchive.openarchive.release

**Comment by purvi-ranawat** [comment]
Just an update. Tested in 0.2.5-BETA-7 but the issue still exists

**Comment by tladesignz** [comment]
Urgh. You used the dropbox.com website for authorization, didn't you? I used the app during development, that work. 

But I just checked: using the website didn't, until now.

Unfortunately, this bug was introduced with a security vulnerability mitigation. Had to take it back partially.

Should work in the next build!

**Comment by purvi-ranawat** [comment]
This is working fine. Tested with dropbox app and website and it works fine for both

Version : 0.2.6
