### ISSUE TITLE
Audio controls different from video and photo

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#42]
Actual: there are "discard" and "done" buttons for audio and x and checkmark for Photo/video

Expected: all would have x and checkmark

**Comment by n8fr8** [comment]
These are handles by external apps on your phone. They differ and vary depending upon which camera or audio recording app you have installed.

In the future, we can look at building in our own media capture tools, but that is beyond the scope right now.

**Comment by foundscapes** [comment]
Makes sense, thank you for clarifying!
