### ISSUE TITLE
Proofmode is not getting enabled for Android 13 (Samsung Galaxy A13)

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#420]
**Describe the bug**
Proofmode is not getting enabled for Android 13 (Samsung Galaxy A13) . When we try to enable Proofmode, the toggle turns to green and then immediately revert back to off mode

1. Open Save App
2. Open any Server (Internet Archive / Private Server)
3. Click on Meta Data and enable Proof Mode

Expected behavior
Proof Mode should be enabled turning the toggle to green

Actual Result : 
Proof Mode is not getting enabled. When we turn on the toggle, it turns on and then again it reverts back to off mode

  Environment 
 - OS version: Android 13
 - Device: Samsung Galaxy A13
 - App Version : 0.2.5-BETA-6

Additional context : 

This is happening on Android 13 only. When I have tried on Android 11 (Samsung Galaxy A70)  , this is working fine

**Comment by tladesignz** [comment]
Hm. That's difficult.
It works on Android 13 on my Nothing Phone(1).

I checked the Play Store crash reports, but the two available there are not from your device. (No surprise, actually, as you don't say that the problem crashes the app, but now I'm running out of options...)

I'm afraid, this is one of these typical Samsung-only issues.
Of course I don't have such a device.

@purvi-ranawat, would you be able to extract a log from the device where this situation is happening?

Are you able to handle [`adb logcat`](https://developer.android.com/tools/logcat) from your computer? Or Android Studio and copy the log from there? (You will, of course, need to [make that device a development device](https://developer.android.com/studio/debug/dev-options).)

**Comment by tladesignz** [comment]
And please test with the latest release I'm going to do today!

**Comment by purvi-ranawat** [comment]
@tladesignz It works fine for Save version 0.3.0- alpha 2. Tested on Samsung Galaxy A3, Android 13
