### ISSUE TITLE
Nextcloud upload chunking seems broken

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-android#421]
Needs deeper trace and comparison with iOS code.

**Comment by tladesignz** [comment]
Should be fixed with upcoming build 20528 / version 0.2.5-BETA-7.

**Comment by purvi-ranawat** [comment]
@tladesignz  / @hiromipaw 

This is blocked due to the following issue : 

https://github.com/OpenArchive/Save-app-android/issues/422

**Comment by purvi-ranawat** [comment]
It works fine.

Android version : Android 11 (Samsung Galaxy A70)
Android verson : Android 13 (Samsung Galaxy 13)

Build Version  : 0.3.0-akpha5
