### ISSUE TITLE
Not able to select the image/video  for uploading 

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#422]
bug Description : 

After adding the server (any of the servers), when we create or browse the folder and click on "+" icon to add the image, blank screen is displayed with Save title at the top. So, not able to select any image for uploading

Steps to reproduce the behavior : 
1. Add the server
2. Add / browse any folder on the server
3. Click on "+" icon to add the image / video

**Expected behavior**
Images / Videos (media) should be available  for selection for uploading

Actual Result : 

Blank screen is displayed when we click on "+"  icon  to upload the image / video and only Save Title is displayed

Below is the video link : 

https://user-images.githubusercontent.com/8190141/227187152-eb8dba29-72d0-4af0-a679-bb3895dd9be0.mp4

**Environment (please complete the following information):**
 - OS version: Android 13
 - Device: Samsung Galaxy A13
 - App Version :  Save 0.2.5-BETA-6

**Comment by purvi-ranawat** [comment]
@hiromipaw : The issue still exists on the version Save 0.2.5-BETA-7

**Comment by tladesignz** [comment]
Will be contained in releases **after** build 20528.

**Comment by purvi-ranawat** [comment]
This is working fine.

Version : 0.2.6
