### ISSUE TITLE
Should we use transifex sdk for localization?

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#428]
How are we currently handling localization? Are we using PO files and translating them to xml? Would it make sense to move to transifex sdk? 

https://developers.transifex.com/docs/native

This is also a valid question of iOS btw.

**Comment by tladesignz** [comment]
All there already:
https://app.transifex.com/otf/SAVE/dashboard/

Sorry, might have confused you, because I was confused myself.

https://github.com/OpenArchive/Save-app-android/blob/master/.tx/config
https://github.com/OpenArchive/Save-app-ios/blob/master/.tx/config
