### ISSUE TITLE
Upload screenshots on the apps stores

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#431]
We should upload screenshots to the apps stores (android and iOS). We should first decide which screenshots we would like to have featured.

**Comment by foundscapes** [comment]
Graphics for stores are here! https://www.figma.com/file/iP2hjShJrOYh4RsxZ6UCQB/SAVE-App-Store-Screens?type=design&node-id=61-883&mode=design&t=zkpbnOQu3CMnKDpF-0

**Comment by tladesignz** [comment]
- Android phone intro screen has a translucent finger.
- Many of the screens don't export their green background
- Android phone files are actually 1 pixel too big. Instead of their proclaimed 2160 x 3840 pixels, they are actually 2160 x 384**1** pixels. Google Play Console doesn't like that.

Please let that get fixed, @hiromipaw! Thank you!

**Comment by foundscapes** [comment]
@hiromipaw do we need to circle back with Isha again? We'll need these ready by October 5th to put on play store. thanks

**Comment by hiromipaw** [comment]
@foundscapes I have shared the images with @uniqx last week and he will let me know.

**Comment by foundscapes** [comment]
@hiromipaw I shared Benjamin's feedback with Isha (you are on that email), please follow up if she doesn't respond promptly. thanks

**Comment by foundscapes** [comment]
@tladesignz Isha reformatted the [play store images](https://www.figma.com/file/iP2hjShJrOYh4RsxZ6UCQB/SAVE-App-Store-Screens?type=design&node-id=61-883&mode=design&t=zkpbnOQu3CMnKDpF-0) to those specs, please let me know if there are any other reasons they can't go up on google play and, if not, please get them up asap.

Thanks!

**Comment by uniqx** [comment]
I've cropped (by 1 pixel, so that should be a not noticeable change) the images supplied to me by Silvia and uploaded them to Google Play, and submitted to review.

**Comment by foundscapes** [comment]
wonderful!

**Comment by foundscapes** [comment]
@uniqx I see they're up! For some reason old designs are showing up on the video (although aren't in the actual video), see photo:
![Screenshot_20231013-094949](https://github.com/OpenArchive/Save-app-android/assets/2231711/2314bfd0-ecce-4cd1-824a-2a01543c042c)


Can you move this to the farthest right so the new screens are the first ones people see? We'll be updating the videos soon anyway, but it'll be nice to showcase Isha's good work.

Thanks!

**Comment by uniqx** [comment]
@foundscapes wrote:
> Can you move this to the farthest right so the new screens are the first ones people see?

That's not supported by Google Play

**Comment by foundscapes** [comment]
> @foundscapes wrote:
> 
> > Can you move this to the farthest right so the new screens are the first ones people see?
> 
> That's not supported by Google Play

Oh Darn, can you remove it please? We'll have new videos once the 2.0 designs are finished :) ty!

**Comment by tladesignz** [comment]
I think I removed the video. Might take a few hours up to a day until live. Please confirm tomorrow.

**Comment by foundscapes** [comment]
The video is still there @tladesignz

**Comment by tladesignz** [comment]
> The video is still there @tladesignz

I can't see it anymore on https://play.google.com/store/apps/details?id=net.opendasharchive.openarchive.release

Where would I see it?

**Comment by foundscapes** [comment]
That's great, but it's still showing up on the play store on android
![Screenshot_20231023-123240](https://github.com/OpenArchive/Save-app-android/assets/2231711/cdcb9c1d-b422-4ed0-b8f0-0cfc28d37455)

**Comment by tladesignz** [comment]
Caching issue?

Maybe, US datacenter needs to replicate changes, first.

![Screenshot_20231025-145812](https://github.com/OpenArchive/Save-app-android/assets/117089/77ee1825-07af-4d11-a5e6-a6ff07b2e368)

**Comment by foundscapes** [comment]
sounds like it, thanks!
