### ISSUE TITLE
Implement new getting started screen

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#433]
The new getting started screen will offer 3 options (nothing new here)

- Weddav
- Dropbox 
- Internet archive

![Get Started Screen](https://github.com/OpenArchive/Save-app-android/assets/1177650/e6e3204b-ccd9-479b-9337-bf5eafdf5c66)

The progress bar indicates the three steps in the setup process of each backend.

**Comment by tladesignz** [comment]
@uniqx: Progress header is still missing. Please add this and your final touches.

**Comment by hiromipaw** [comment]
The getting started screen changed a bit: 

![Get Started Screen](https://github.com/OpenArchive/Save-app-android/assets/1177650/229dcb29-f2b5-4190-9a43-845f49ea27ee)

**Comment by uniqx** [comment]
fixed by 4debad2 (merged into master but not tagged/released yet)

**Comment by uniqx** [comment]
Will be released in 0.3.0-alpha8

**Comment by hiromipaw** [comment]
@purvi-ranawat can you test this?

**Comment by purvi-ranawat** [comment]
@hiromipaw : Currently the build version is 0.3.0-alpha7. I will be testing on 0.3.0-alpha8 release as mentioned above. Because in the current version, the little changes mentioned above is not there

**Comment by hiromipaw** [comment]
@purvi-ranawat release is out :)

**Comment by purvi-ranawat** [comment]
@uniqx / @tladesignz : 

1. In the requiremnet screenshot, there is "," after "In Settings" text but in the app, "," is missing.
2. In the requirement screenshot, Under the Private Server label, it is written "Send to webdav Server" while in the app, under Private Server , it is written "Send directly to a private server"
3. In the requirement screenshot, Under the Internet Archive label, it is written "Upload to the IA", while in the app, under Internet Archive label, it is written "Upload to the Internet Archive"




App : 


![Image](https://github.com/OpenArchive/Save-app-android/assets/8190141/b1080c28-bf41-4bab-8777-75bdac884cbe)


Environment : 

OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build Version : 0.3.0-alpha8

**Comment by uniqx** [comment]
fixed by f31a085
will be released in 0.3.0-alpha9

**Comment by foundscapes** [comment]
is this fixed in 0.3.0-beta1 @purvi-ranawat ?

**Comment by purvi-ranawat** [comment]
This is working fine.

Below is the screenshot : 

![get started](https://github.com/OpenArchive/Save-app-android/assets/8190141/fda05ecb-4795-4737-a245-a243bdeda1d0)

Environment : 

OS : Android 11, Android 13
Device : Samsung Galaxy A70, Samsung Galaxy A13
Build ; 0.3.0-beta1

**Comment by foundscapes** [comment]
great, ty!
