### ISSUE TITLE
Implement internet archive setup

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#436]
Internet archive setup is implemented in 3 steps:

![Internet Archive - Log In](https://github.com/OpenArchive/Save-app-android/assets/1177650/50b34bef-a665-4953-839f-7323926da098)

![Internet Archive - Keys Aquired](https://github.com/OpenArchive/Save-app-android/assets/1177650/df98c147-e7bf-4160-a043-fab6cc3f7386)

![Internet Archive - Success](https://github.com/OpenArchive/Save-app-android/assets/1177650/7e44163e-e474-44b2-a6a2-4dc581756f51)

![Icon-2](https://github.com/OpenArchive/Save-app-android/assets/1177650/2bded59d-e363-48b3-b813-a07ac7c04c77)

Figma:
https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

![Group 431-2](https://github.com/OpenArchive/Save-app-android/assets/1177650/718e5e59-810b-4209-a866-0e9a6d5237e1)

**Comment by tladesignz** [comment]
@uniqx, since the activity is the same as in  #447, I already worked towards this, too.
However, you're definitely the one who's more knowledgable around Android styling, so I let you the progress header and the last scene and general brushing and making sure that colors work in dark mode... :-)

**Comment by hiromipaw** [comment]
We should add the new instructions on how to acquire keys:
![IA Guide - Step 1](https://github.com/OpenArchive/Save-app-android/assets/1177650/6227dd44-3425-4191-b29c-d0325f11a83f)

![IA Guide - Step 2](https://github.com/OpenArchive/Save-app-android/assets/1177650/732a2cb6-2279-4dcb-a8b0-c50c5213738c)

![IA Guide - Step 3](https://github.com/OpenArchive/Save-app-android/assets/1177650/350c04c9-6c01-4367-ae17-ce0c3121480e)

![IA Guide - Step 4](https://github.com/OpenArchive/Save-app-android/assets/1177650/40ecce46-d59b-4a06-a077-d65835c8fe58)

![IA Guide - Step 5](https://github.com/OpenArchive/Save-app-android/assets/1177650/ccae1e67-78c4-4e07-8c69-9d9413ae9c7a)

**Comment by uniqx** [comment]
blocked by: https://github.com/OpenArchive/Save-app-android/issues/496

I can't log into internet archive accounts, so I can't really make any changes to the setup and guarantee that everything is still working as desired.

**Comment by hiromipaw** [comment]
@purvi-ranawat could you test this?

**Comment by uniqx** [comment]
blocking: https://github.com/OpenArchive/Save-app-android/issues/465

**Comment by foundscapes** [comment]
@uniqx are you saying you can't implement these designs into the app bc of the internet archive new account login issues we're facing? If not, can @purvi-ranawat please test bc she has an older account. 

thanks all

**Comment by foundscapes** [comment]
@uniqx I can also send you my older creds as well if need be!

**Comment by uniqx** [comment]
@foundscapes wrote:
> @uniqx I can also send you my older creds as well if need be!

Well, I could try to get a working IA account/credentials and implement/fix the new styling.

However, if this issue (https://github.com/OpenArchive/Save-app-android/issues/496) surfaces for me during development, there is a considerable chance this also happens for Save users. So fixing it is important, right? And fixing it first and afterwards applying the styling will save me the effort to look for credentials. But since you've got some credentials that work, feel free to hook me. :)

**Comment by foundscapes** [comment]
> @foundscapes wrote:
> 
> > @uniqx I can also send you my older creds as well if need be!
> 
> Well, I could try to get a working IA account/credentials and implement/fix the new styling.
> 
> However, if this issue (#496) surfaces for me during development, there is a considerable chance this also happens for Save users. So fixing it is important, right? And fixing it first and afterwards applying the styling will save me the effort to look for credentials. But since you've got some credentials that work, feel free to hook me. :)

Yes it will continue to be a problem for all Save users and we'll need the IA to fix it...I think if we can at least implement the new screens while we wait on the IA to help us fix this, that would be ideal, even if it means we have to go back to fix it later (given that it's been over a month and they have not responded to us). Will send creds asap :)

**Comment by foundscapes** [comment]
@purvi-ranawat this is implemented for us, can you make sure this is done? thanks

**Comment by purvi-ranawat** [comment]
@foundscapes : This is working fine as per the requirement.

Environment : 
OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build Version : 0.3.0-beta5
