### ISSUE TITLE
Add a new folder to a backend

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#437]
The arrow (in theory) should animate.

![Home - First time user](https://github.com/OpenArchive/Save-app-android/assets/1177650/1a233ae6-842c-42a3-be1d-b027c9702343)

![Home - First time user no project](https://github.com/OpenArchive/Save-app-android/assets/1177650/9c03eaf3-51c0-4f0e-bf3b-e60088827bc3)

![Add a Folder pop up](https://github.com/OpenArchive/Save-app-android/assets/1177650/1cbf4203-e8db-4f49-9ae1-6552d98f5953)

Typography:
```
font-family: Montserrat;
font-size: 24px;
font-weight: 700;
line-height: 29px;
letter-spacing: 0em;
text-align: center;

font-family: Montserrat;
font-size: 36px;
font-weight: 700;
line-height: 44px;
letter-spacing: 0em;
text-align: center;
```

Figma: https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

**Comment by hiromipaw** [comment]
@tladesignz can we close this issue? I think it was implemented.

**Comment by tladesignz** [comment]
@purvi-ranawat, this is contained in the latest betas.

**Comment by purvi-ranawat** [comment]
This is working fine.

As per communication with benjamin, the redesign will be handled in later release. But functionality is working fine.

Tested on 0.3.0-alpha5 build.

OS : Android 11, Android 13

Device : Samsung Galaxy A70, Samsung Galaxy A13
