### ISSUE TITLE
Implement new hamburger menu

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#438]
The new hamburger menu implements both a view for the current backend and all the configured backend.

![Home - Menu Dropbox](https://github.com/OpenArchive/Save-app-android/assets/1177650/d550fecf-5610-4cdd-8112-39bcd90212f1)

![Home - Menu](https://github.com/OpenArchive/Save-app-android/assets/1177650/662720b2-7d29-4a9c-a3f0-c22b01868241)

**Comment by tladesignz** [comment]
Will be contained in version 0.3.0 onwards.

**Comment by tladesignz** [comment]
@purvi-ranawat, please keep in evidence until next (beta) release.

**Comment by purvi-ranawat** [comment]
@tladesignz @hiromipaw Hamburger menu is getting displayed correctly, however, opened a new issue for server name displayed in hamburger menu

https://github.com/OpenArchive/Save-app-android/issues/454
