### ISSUE TITLE
Implement new bottom menu

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#439]
Implement new bottom menu 

![Bottom Menu - Selection](https://github.com/OpenArchive/Save-app-android/assets/1177650/9268a2aa-1d80-45c8-9627-04a32310e95e)

![Bottom Menu](https://github.com/OpenArchive/Save-app-android/assets/1177650/33ce5588-5396-41fb-8ac5-6876023eee76)

![Home 2](https://github.com/OpenArchive/Save-app-android/assets/1177650/5e614f6c-f202-4ea9-867e-ea55b1ec7b54)

**Comment by tladesignz** [comment]
Long taps cannot be captured in `BottomNavigationView`s. Hence this functionality is not possible.

This is somewhat duplicated in #440. Let's follow up there.
