### ISSUE TITLE
Sharing a recorded audio file to the Open Archive app does not work

### ISSUE THREAD

**Issue by orschiro** [OpenArchive/Save-app-android#44]
Dear all, 

Another issue. 
1. I used HighQ MP3 Recorder to record an mp3 file. 
2. From within that app, I selected share and shared it with Open Archive. 
3. It opens the Open Archive app but only shows the home screen with `Click the + button...`.

No further action occurs. 

Warmly,

~Robert

**Comment by n8fr8** [comment]
Thanks. You should try the "import media" option in OpenArchive and browser to the mp3 file.

We will look into the issue here with sharing into the app

**Comment by orschiro** [comment]
Import media does work! However, a bit less convenient.

Thanks,

Robert
