### ISSUE TITLE
Implement bottom bar menu

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#440]
The bottom bar menu has some new interactions:

![Home 2](https://github.com/OpenArchive/Save-app-android/assets/1177650/45641480-54d7-46e3-bcf7-df6c80ba4f47)

On the + button:

Single tap = native image gallery
Press and Hold = Bottom Menu selection to chose between photos and files browsing

![Bottom Menu](https://github.com/OpenArchive/Save-app-android/assets/1177650/f9f8d900-74b0-44ed-b243-399de4e7c0b1)

If you browse through photos you will see them all in grid:

![Single Tap - Select Image](https://github.com/OpenArchive/Save-app-android/assets/1177650/d4370450-518c-4f10-accd-6e95d2af0247)

If you browse through files you might see the contained folders:

![Folder](https://github.com/OpenArchive/Save-app-android/assets/1177650/d5984e95-4829-4eed-b0e6-bee4fe51d200)

Figma: 
https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

**Comment by tladesignz** [comment]
https://m3.material.io/components/navigation-bar/specs

**Comment by tladesignz** [comment]
Added bottom menu, reworked top bar as per design.

1. Re long tap: As mentioned in #439, this is not possible with a `BottomNavigationView`. Simplest way would be to add another menu button. 5 are possible in total.
2. We don't do our own media picker. We can maybe use another one, happy to hear suggestions/opinions about other open source libraries or using system provided picker. @hiromipaw, @uniqx - create own ticket about it, if wished.
3. @uniqx, since I'm not really grasping the theming, yet - can you take care of the coloring?

**Comment by foundscapes** [comment]
It's a shame the long-tap won't work @tladesignz, but I've asked our interaction designer to mock up an alternative design for this interaction as we don't want the bottom bar to be too cluttered. Will share here asap.

**Comment by foundscapes** [comment]
@tladesignz see solution below, can we do better? The alternate solution was the screen below. When the user taps the "+" button, this modal gets brought up and then they can select whether they want to upload from their photo gallery or from files. The only downside is - if a user is only interested in using the photo gallery then they have an extra step each time they want to upload. 

<img width="328" alt="Screen Shot 2023-10-09 at 9 24 57 PM" src="https://github.com/OpenArchive/Save-app-android/assets/2231711/b1e4e915-3785-4338-92da-7d47d5f83f13">

**Comment by tladesignz** [comment]
>  The only downside is - if a user is only interested in using the photo gallery then they have an extra step each time they want to upload.

That's why I tell you time and time again: Do 2 add buttons. One tap, all the options.

**Comment by foundscapes** [comment]
@tladesignz from a ux perspective, the long tap would've been preferable. Since we can't do that, let's implement the alternative design. thanks!

**Comment by tladesignz** [comment]
Hm. Actually, when I last looked at the code it seemed like @uniqx has replaced the mentioned `BottomNavigationView` with a custom built menu. Maybe we can add a long-tap there?

Anyway, after I did the initial development, @uniqx took over for UI fine-tuning. so I let it to you two to continue this discussion.

**Comment by uniqx** [comment]
@tladesignz wrote:
> Maybe we can add a long-tap there?

long-tap should be easily feasible with the changes I did, since it's a normal `Button`-View now. However I'd recommend against it, because this is not a common user interaction pattern on Android. @foundscapes up to you.

**Comment by foundscapes** [comment]
Oh wow, thanks for implementing @uniqx ! Given that we're implementing it to reduce the number of steps users need to take to add media, we were hoping it would work well for our communities. Once it's implemented, we can playtest it and get feedback to see if this is the case. We can leave this open until that happens. Thanks!

**Comment by tladesignz** [comment]
@uniqx, I added the add menu which shows up on long-tapping the "+". It needs more styling. Can you please take care of that? Thank you!

**Comment by tladesignz** [comment]
(Note: Some devices don't have a document picker. It won't show in that case!)

**Comment by foundscapes** [comment]
Need to pause on this issue while we finish critical pathway work, focus on this once that is done.

steps to solve: 
first need to decide on which picker
implement picker

**Comment by uniqx** [comment]
Apparently a most of the test devices in our team don't come with a file picker. Since the app doesn't respond to long-clicks for them.

I suspect it's this check:
```
        if (Picker.canPickFiles(this)) {
```

So we'll need to look into getting a file-picker working that works everywhere.

**Comment by foundscapes** [comment]
great! @uniqx please work on this after finishing two issues: 1: integrating GDrive #511  and then getting Save on Fdroid #320 ty!

**Comment by foundscapes** [comment]
@uniqx the long-press is working for all of us on various versions of android, is there anything else you need to do to close this issue? ty!
