### ISSUE TITLE
Implement new general settings screen

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#445]
New general settings are divided between:
- general
- space
- folder

![Dropbox-1](https://github.com/OpenArchive/Save-app-android/assets/1177650/98c8ad58-3ac2-4c9c-85fe-95e7a18b25fb)

The general settings screen contains options about the app itself:

![General](https://github.com/OpenArchive/Save-app-android/assets/1177650/454c351a-fe68-4ad6-ad66-70461383ec64)

There are two other panels that can be opened. For proofmode and media compression.

![ProofMode](https://github.com/OpenArchive/Save-app-android/assets/1177650/3303b25b-bf51-40f7-98fd-b28057420350)

![Compression](https://github.com/OpenArchive/Save-app-android/assets/1177650/da46f845-b696-4765-bf99-d738fa2bfa9d)

**Comment by tladesignz** [comment]
@purvi-ranawat, this is ripe for QA/done.

Everything should actually be contained in the last alpha release.

Please consider the following:
- The design sketches use a mixture of Android and iOS. We're not burden ourselves with trying to mimic one platform on the other, so the look on Android is a little different.
- Some options are just not available on the platform (e.g. 3rd party keyboard control) So things are a little different on Android compared to the sketches.

**Comment by purvi-ranawat** [comment]
This is working fine.

Below is the details : 


OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
App version : 0.3.0-alpha6
