### ISSUE TITLE
Implement creative commons bulk folder settings

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#446]
Settings for folders show active and archived folders depending on what the user has:

![All types](https://github.com/OpenArchive/Save-app-android/assets/1177650/28f6b633-f195-4aa2-b53c-baeb7e36c7cc)

![Active Projects Only](https://github.com/OpenArchive/Save-app-android/assets/1177650/33bc3d2e-1700-4c0f-858e-ec888380b43d)

![Active Projects Only-1](https://github.com/OpenArchive/Save-app-android/assets/1177650/ebf298a2-7b7c-43a4-8fb5-821cccb47b20)

You can pick name and license type for the full folder or all folders and you can also delete a folder:

![Projects-1](https://github.com/OpenArchive/Save-app-android/assets/1177650/fcc94989-2f48-4cac-a593-f8e82f991b5f)

![Projects](https://github.com/OpenArchive/Save-app-android/assets/1177650/644ca089-1779-411f-86e0-7a31c3d4a45d)

When a folder is deleted a confirmation popup is displayed:
![Remove Space](https://github.com/OpenArchive/Save-app-android/assets/1177650/94577695-1a4a-424c-b36f-ffb7a20d146c)

**Comment by tladesignz** [comment]
🤔 Hmmmm. @hiromipaw, what should happen when a user changes the license for the whole server (aka. space)?

a) Does it overwrite the license setting of all (active, non-archived) projects aka. folders?

- Might be confusing, when the user sets something in a project and something different for the space. First setting will be overwritten.

b) Does it act as a fallback, if nothing more specific is set?

- Might be confusing, when the space shows a certain license, but the folder shows none?

c) Does it disable per-folder settings?

- Might be confusing, when the setting is gone.


BONUS: Changes are never reflected onto the server. It always only affects new uploads.

**Comment by hiromipaw** [comment]
@foundscapes can you help us with this?

**Comment by foundscapes** [comment]
@tladesignz @hiromipaw - people should be able to bulk add cc licensing without it changing prior choices....which I think is solved for by not being able to edit media that's already been uploaded to the server...but does likely overwrite any folder-specific cc settings for future uploads, so I don't think that's a problem...did I get this right?

**Comment by tladesignz** [comment]
@foundscapes  Ok, so when a user sets a CC license for the whole space, folder-specific settings are ignored, do I get that right?

I guess the best UI solution is to show the licensing of the space on the folders, too, but disable all toggles there, so they cannot change anything.

Agreed? Or rather hide it completely?

**Comment by foundscapes** [comment]
> @foundscapes Ok, so when a user sets a CC license for the whole space, folder-specific settings are ignored, do I get that right?

@tladesignz yes bc the prior settings are preserved on servers.

> 
> I guess the best UI solution is to show the licensing of the space on the folders, too, but disable all toggles there, so they cannot change anything.

Do you mean to show licensing on each server vs. folder? Please clarify
> 
> Agreed? Or rather hide it completely?

**Comment by tladesignz** [comment]
> > I guess the best UI solution is to show the licensing of the space on the folders, too, but disable all toggles there, so they cannot change anything.
> 
> Do you mean to show licensing on each server vs. folder? Please clarify

When the server has CC licensing set, it overrides folder settings. I made it now, so that the licensing is *shown* on the folder (so the user understands that the folder will get that license), but not editable, as long as there is a *server* CC license set (so there's no confusion to the user, which setting now counts).

Have a look at it yourself, when it's released. Then decide if you like it or if you want changes.

**Comment by tladesignz** [comment]
@purvi-ranawat, this will be contained in version 0.3.0-alpha9, build 20538 and later probably available next week!

**Comment by foundscapes** [comment]
> > > I guess the best UI solution is to show the licensing of the space on the folders, too, but disable all toggles there, so they cannot change anything.
> > 
> > 
> > Do you mean to show licensing on each server vs. folder? Please clarify
> 
> When the server has CC licensing set, it overrides folder settings. I made it now, so that the licensing is _shown_ on the folder (so the user understands that the folder will get that license), but not editable, as long as there is a _server_ CC license set (so there's no confusion to the user, which setting now counts).
> 
> Have a look at it yourself, when it's released. Then decide if you like it or if you want changes.

I see it in the beta1 - Oh that's cool, thanks for solving for the discrepancy @tladesignz !

**Comment by tladesignz** [comment]
@foundscapes, @purvi-ranawat just pointed out an inconsistency to me:

When going to Hamburger Menu -> New Folder -> Create a New Folder

...then there's no CC selection. (Also not when doing "Browse Existing Folders", of course.)

Should we put it there, too?

**Comment by foundscapes** [comment]
> @foundscapes, @purvi-ranawat just pointed out an inconsistency to me:
> 
> When going to Hamburger Menu -> New Folder -> Create a New Folder
> 
> ...then there's no CC selection. (Also not when doing "Browse Existing Folders", of course.)
> 
> Should we put it there, too?

sorry I missed this - yes it should show up wherever people create new folders.

**Comment by tladesignz** [comment]
@purvi-ranawat, this will be contained in version 0.3.0-beta5

**Comment by foundscapes** [comment]
@tladesignz this process in beta5 doesn't match the designs above, can you reconcile them to be more similar?

**Comment by foundscapes** [comment]
current issues from this update documented in #520
