### ISSUE TITLE
Issue with spacing with different orientation

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#455]
@uniqx discovered a few issues with spacing with different orientation when implementing the getting started flow.

![image](https://github.com/OpenArchive/Save-app-android/assets/1177650/4e6a194e-5e8c-4558-8280-458b683f79f5)

![image](https://github.com/OpenArchive/Save-app-android/assets/1177650/6b8fc463-5b44-4893-bd48-5a17606d11df)

![image](https://github.com/OpenArchive/Save-app-android/assets/1177650/e4c81b82-14df-4931-b1b7-ba262ae6c1ad)

Should we arrange the elements differently according to the visual space available?

**Comment by hiromipaw** [comment]
These were both "tablet" and "unfold" mode in android. @uniqx do you have the exact size available?

**Comment by uniqx** [comment]
Those sizes are not exact. eg. A fold-able phone from Samsung will have different dimensions that a fold-able from a competing manufacturer. Additionally Android uses a scale-able unit called `dp` for measuring dimensions. (Scaling is an accessibility feature for vision impaired users.) Additionally its worth noting that users on Android resize app "window"-dimensions arbitrarily.

Here's Androids official documentation on screen sizes: https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes

I'm testing with Android emulator from Android-Studio.

**Comment by foundscapes** [comment]
@hiromipaw do we need to work with Isha to resolve?

**Comment by foundscapes** [comment]
@tladesignz please advise how to move forward, is this something @purvi-ranawat can test?

**Comment by tladesignz** [comment]
Since @uniqx implemented this and is way better with Android styling, and since I don't even really understand what the problem was, I suggest you follow @uniqx' advice.

**Comment by uniqx** [comment]
I think this is implemented and shipped. Please open followup issues should anything come up
