### ISSUE TITLE
Issue with arranging elements based on localised languages

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#456]
@uniqx noticed that some buttons will take considering more space when localised in certain languages. Ex:

![image](https://github.com/OpenArchive/Save-app-android/assets/1177650/a69c63cf-bcfe-45c3-909d-e56ce3da7064)

The "skip" button in German will be way larger and might take too much space in the sidebar.

Another issue we should consider is if we want to move the menus (like the sidebar) on the other side depending if the language is LTR or RTL.

@foundscapes what do you think?

**Comment by uniqx** [comment]
fixed by fda01f3
