### ISSUE TITLE
Remove tagging options in media

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#457]
In previous versions of Save we add more tagging options when adding metadata to images.
Now we only have:
- Location
- Name for the media
- Notes

![Single Media Info](https://github.com/OpenArchive/Save-app-android/assets/1177650/3f6b0799-dce2-4dcc-80c3-9800d666aca6)

**Comment by tladesignz** [comment]
Don't forget the flagging option! (Top right corner.) 

At least on iOS, this is implemented as a special tag named "Significant Content" and tags are output with all other metadata. Additionally, it actually moves the content in a subdirectory called "Significant Content".

(This behaviour needs to be copied in Android, if not completely done so, yet.)

**Comment by hiromipaw** [comment]
@foundscapes could you confirm on Benjamin's comment?

**Comment by foundscapes** [comment]
Yes, we absolutely are keeping the flag icon as well, is there something else you need my input on? thanks for catching that @tladesignz !

**Comment by foundscapes** [comment]
@hiromipaw  - again, this scene isn't in alpha8, so I haven't seen any of the design updates yet

**Comment by tladesignz** [comment]
@purvi-ranawat, this is implemented in the latest release.

**Comment by purvi-ranawat** [comment]
This is working fine on Version 0.3.0-beta4.
Tested on Android 11 and Android 13 on Samsung Galaxy A13, and Samsung Galaxy A70.
