### ISSUE TITLE
Add new space in new design

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#458]
From the menu the user can click the dropdown to switch spaces. If they click into "Private Server" and if they have not signed that space yet, it will take them to the sign-in screen, a similar layout to the get-started screens but without the progress bar at the top. And then it will take them to the "Home" screen of that space.

![image](https://github.com/OpenArchive/Save-app-android/assets/1177650/f73c99e0-8e60-49cf-abbf-fc4e51567b08)

**Comment by tladesignz** [comment]
Yeah. No. Users can have as much WebDAV servers, as they like. They technically could use as many Internet Archive accounts, as they like, but we currently don't allow that for no real reason. The only limitation is Dropbox: The Dropbox SDK can't handle more than one login.

**Comment by hiromipaw** [comment]
Also the getting started view has changed a bit:

![Screenshot 2023-07-25 at 1 01 42 PM](https://github.com/OpenArchive/Save-app-android/assets/1177650/eb605fd1-a653-4f14-b35c-6835af263f01)

**Comment by tladesignz** [comment]
All nice and dandy, but what about https://github.com/OpenArchive/Save-app-android/issues/458#issuecomment-1648084338?

**Comment by hiromipaw** [comment]
Got a reply just today:

> Once the user signs into IA or a private server, there would be another dropdown action indented that says "Add Another account" to allow the user to add multiple. 

![image](https://github.com/OpenArchive/Save-app-android/assets/1177650/83ba1ddc-7989-4cf4-9ae7-1d0cc2758665)

**Comment by tladesignz** [comment]
@purvi-ranawat, I'll release a new alpha version for testing containing this later today!

**Comment by purvi-ranawat** [comment]
@hiromipaw / @tladesignz : All the requirements mentioned above are working fine except for the Getting Started View. Getting Started when we install the app is still the same as before and not the screenshot mentioned by @hiromipaw above.


Save Version : 0.3.0-alpha5
Phone : Samsung Galaxy A13
Android 13

**Comment by hiromipaw** [comment]
Moving the changes to the getting started screen to a separate issue. That was my bad.
