### ISSUE TITLE
Improve media upload list UI

### ISSUE THREAD

**Issue by onejgordon** [OpenArchive/Save-app-android#460]
**I Like...**

- Being able to see a list of media, and adding annotations, prior to committing to upload.

**I Wish...**

- The UI was more legible, and action icons and affordances were more clear

Specifically: 

1. the header "Preview --- Upload" appears black on a dark gray background, which is hard to read.
2. The 4 icons on the media tile are confusing. The first 3 open a detail annotation view, despite having different icons, and the fourth (flag) appears to take the action of flagging the entry. I generally expect different icons to do different things, and to not have redundant actions in a single view. 
3. Using the back arrow from the annotation screen goes to the main screen, rather than the prior list view, it is unclear how to return to.
4. The upload action, which is the primary action, is hidden in a more menu

**What If...**

- Perhaps all 4 icons could be collapsed into an "annotate" action, which comes to the annotation view.
- The upload action always appeared in the top bar

**Environment:**

OS version: Android 13
Device: Pixel 7
App Version: 0.3.0-alpha4

**Comment by hiromipaw** [comment]
1. Preview Media should be in white and upload should be in teal against the dark background, see design below.
2. There should be only one icon on the media tile which is the edit icon and that's only if the user has added annotations to that image.
3. From the annotations screen, the back arrow should take them back to the "preview media"
4. The upload action should be in the top right at all times, not hidden in the more menu. 

![image](https://github.com/OpenArchive/Save-app-android/assets/1177650/ed63909d-9ff7-424f-ba1e-67e9298e77b0)

![image](https://github.com/OpenArchive/Save-app-android/assets/1177650/8d997feb-4761-4ff7-82cb-3d3ac3f2e518)

**Comment by hiromipaw** [comment]
This is related to: https://github.com/OpenArchive/Save-app-android/issues/457

**Comment by foundscapes** [comment]
@onejgordon the updated designs for media uploading have not yet been implemented in the alpha, I will send our tester group the version that includes ALL ux updates for you to re-test, it should solve your problem. thanks!

**Comment by foundscapes** [comment]
@hiromipaw those images are from figma, not yet implemented in the version that Jeremy was using.

**Comment by tladesignz** [comment]
@purvi-ranawat, this is actually implemented now in the latest release.

**Comment by purvi-ranawat** [comment]
This is working fine.

Environment : 
OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build version : 0.3.0-beta7
