### ISSUE TITLE
Refresh button not visible when acquiring Internet Archive keys

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#461]
**Describe the bug**
When I login to Internet Archive for acquiring keys for adding IA server on Save app, the refresh button isn't visible. The keys get acquired after I refresh by drag and drop method or wait for 10-15 seconds. 

**To Reproduce**
1. Go to the tab to add new account
2. Click on Internet Archive
3. Log in with the credentials
4. The log in is successful but the refresh button isn't visible
5. The keys get acquired after a wait of 10-15 seconds.

**Expected behavior**
The expected behaviour was to encounter a refresh button which on click will fetch keys

**Video with the error produced**
https://drive.google.com/file/d/18seAzPBTxdYRpyr8G4QI8VMcWO5Ecm6S/view?usp=sharing

**Environment (please complete the following information):**
 - OS version: Android 13
 - Device: Poco X3 Pro
 - App Version: 0.3.0-alpha 4

**Additional context**
The previous version of Save app for which the tutorial is available had the refresh button so it was expected that the beta version will also have a similar feature.

**Comment by tladesignz** [comment]
Fixed with a97ab318. I added a toolbar with a refresh button.

@purvi-ranawat, this will be contained in an *upcoming* alpha release which I'm going to do later today!

**Comment by purvi-ranawat** [comment]
This is working fine.

Environment : 

OS Version : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
App Version : 0.3.0-alpha6
