### ISSUE TITLE
"About Save" needs to link to Save page not about OA

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#464]
**Describe the bug**
A clear and concise description of what the bug is. The "About Save" link needs to go here: https://open-archive.org/save (not to the OA about)
Sorry to pile on, but can we make sure that "Save" is bold/ital/teal here?

**To Reproduce**
1. Go to Settings 
2. Click on "About Save"
3. it directs one to: https://open-archive.org/about

**Expected behavior**
I should go to this link: https://open-archive.org/save not the one there

**Screenshots**
![IMG_7904](https://github.com/OpenArchive/Save-app-android/assets/2231711/47b8bb42-c6a4-459d-80a8-16c090e24816)

**Environment (please complete the following information):**

 - OS version: Android 12
 - Device: Google Pixel 3a
 - App Version 0.3.0-alpha5

**Additional context**
Just need to fix the link and font and we're good

**Comment by uniqx** [comment]
fixed by https://github.com/OpenArchive/Save-app-android/commit/fe81219576c06d216f6103a980df62991aaa82ef
this change will be in the 0.3.0-alpha8
