### ISSUE TITLE
Next button overlaps pw field for nextcloud login

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#465]
**Describe the bug**
Next and back buttons overlaps pw field

**To Reproduce**
1. Go to private server login
2. Add creds
3. "next" and "back" buttons overlap the pw field

**Expected behavior**
need more padding so they would fit below the login / pw fields

**Screenshots**
![IMG_7903](https://github.com/OpenArchive/Save-app-android/assets/2231711/12e53c62-f73c-4fc6-9a98-e795b23eb8a4)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device:  Google Pixel 3a
 - App Version: 0.3.0-alpha5

**Comment by foundscapes** [comment]
This also happens for the IA, need to test Dropbox
![Screenshot_20230822-132030](https://github.com/OpenArchive/Save-app-android/assets/2231711/39a3d316-4fdb-4601-9428-4aecc313eb61)

**Comment by uniqx** [comment]
fixed in 0.3.0-alpha7

(fixed for nextcloud and dropbox for sure, might still be an issue with internet archive but I'll clean that up with https://github.com/OpenArchive/Save-app-android/issues/436)

**Comment by uniqx** [comment]
fixed by 07231f0
available in 0.3.0-alpha7

**Comment by foundscapes** [comment]
@purvi-ranawat can you verify this is fixed? it worked for me in alpha8 - ty!

**Comment by purvi-ranawat** [comment]
@foundscapes  / @hiromipaw : This is fixed for next cloud and dropbox But for Intenet Archive, the issue still exists.

Below is the screenshot : 

![image](https://github.com/OpenArchive/Save-app-android/assets/8190141/6836183d-dd81-4494-b761-132be6a1588d)

**Comment by foundscapes** [comment]
Thanks so much for testing @purvi-ranawat! Please fix asap @uniqx
