### ISSUE TITLE
My Media screen should be displayed with status uploading when we click on Upload after selecting the media

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#466]
Description : 

After selecting the media, when we click on Upload, the upload screen does not disappear. It looks like on clicking on upload, nothing happens. But in reality the upload is happening. So, on clicking on upload after selecting the media, Upload screen should disappear and My Media screen should be displayed with the status of the media uploading or uploaded

1. Open Save App and select few images / videos
2. After selecting the images/ videos, click on Upload

**Expected behavior**
Upload screen should disappear and My Media screen should be displayed showing the status of the media uploaded

Actual Result : 
On clicking on upload, the upload screen does not disappear and it also doesnt shows the status of the media being uploaded

**Environment (please complete the following information):**
 - OS version: Android 11 , Android 13
 - Device: Samsung Galaxy A13, Samsung Galaxy A70
 - App Version 0.3.0-alpha5

**Comment by hiromipaw** [comment]
Once the user taps "Upload" it should bring them back to the home page where they can see the upload status of the media they just added, see design below.

![image](https://github.com/OpenArchive/Save-app-android/assets/1177650/53e6c2a7-ac49-4b41-a30a-cf8a234c3b3e)

**Comment by foundscapes** [comment]
@hiromipaw again - the ux designs are not currently in the alpha releases so Purvi isn't seeing what you are posting. @purvi-ranawat please wait until the app is finalized with the updated ux before testing new features since they are not yet implemented in the app. thanks

**Comment by tladesignz** [comment]
There seems to be a duplicate in #475 which was just resolved.

@purvi-ranawat, please reopen if that was a misunderstanding. Thanks!
