### ISSUE TITLE
Button in settings to enable dark or light mode

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#467]
**I Wish...**
There was a button in settings where you could switch from dark to light mode. Currently, for Android at least, you can only go into dark mode if your phone as a whole is set to dark mode.

Thoughts? Is this possible? Too complicated?

**Comment by hiromipaw** [comment]
Yes we will have light and dark mode available.

**Comment by foundscapes** [comment]
isn't this implemented, can we close @tladesignz ?

**Comment by ceylana** [comment]
There is still no button in setting where I can switch it from light to
dark mode. I think it is currently based on phone settings for android

**Comment by foundscapes** [comment]
@tladesignz @uniqx So this is implemented, but two issues:
1. the language needs to be updated per issue #505 and
2. after changing the theme, it should keep user in settings and not take you back to the onboarding screens and it also seems to have disconnected me from the servers I had already logged into :/


https://github.com/OpenArchive/Save-app-android/assets/2231711/9dc7333d-5b22-435c-9f81-6bce8a6b06a1



once fixed, we can close

**Comment by neeldoshii** [comment]
> @tladesignz @uniqx So this is implemented, but two issues:
> 
> 1. the language needs to be updated per issue [Word choice & spelling issue on General Settings page #505](https://github.com/OpenArchive/Save-app-android/issues/505) and


Fixed this issues


> 2. after changing the theme, it should keep user in settings and not take you back to the onboarding screens and it also seems to have disconnected me from the servers I had already logged into :/



Working on this issue.

**Comment by neeldoshii** [comment]
@foundscapes @ceylana Can you assign me?

**Comment by tladesignz** [comment]
This will be better in version 0.3.0-alpha4, although there's still a bug where the settings page isn't properly shown until it's scrolled in and out of 2 times.
I'll let this for @uniqx to fix when he's overhauling the whole thing including the upload.

**Comment by foundscapes** [comment]
@uniqx this is fixed for us, can you please close these issues once you've resolved and had Purvi test them? thanks!

**Comment by foundscapes** [comment]
@vanichitkara can you test this and close if it's working for you? Thanks!

**Comment by foundscapes** [comment]
working in beta7
