### ISSUE TITLE
Uninstalling the app clears any folder created from the home screen, but not in the screen displayed after selecting "+" and 'Browse Existing Folders'

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#469]
**Describe the bug**
Uninstalling the app clears any folder created from the home screen, but not in the screen displayed after selecting "+" and 'Browse Existing Folders'

**To Reproduce**
1. Uninstall the app after having created some folders
2. Reinstall the app
3. Click on '+' to create your first folder
4. Select 'Browse Existing Folders'
5. The app will displayed the folders that were present on the app before the uninstallation

**Expected behavior**
Either the folders should be fully preserved, or they should be fully deleted.

**Screenshots**
![Screenshot_20230823-093509](https://github.com/OpenArchive/Save-app-android/assets/4558756/77f851b3-bf00-4b35-8385-ee51bb01dd34)
![Screenshot_20230823-093513](https://github.com/OpenArchive/Save-app-android/assets/4558756/e7bea947-7c99-4ce5-8c3e-ece4dfa29caf)
![Screenshot_20230823-093519](https://github.com/OpenArchive/Save-app-android/assets/4558756/f0346184-0c5f-4042-a78b-d480957a84e7)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Comment by tladesignz** [comment]
This is actually user confusion. Works as intended. What you see in "Browse existing folders" are the destination folders on the server. Save doesn't delete anything on the server. But this feature is there so the destination server operators can guide you to do the right thing. Or so you can pick up easily where you left off.
