### ISSUE TITLE
When editing the metadata of one media during the upload process of multiple media, clicking on the back arrow icon takes back to the folder, and not the list of media in the process of being uploaded

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#470]
**Describe the bug**
When editing the metadata of one media during the upload process of multiple media, clicking on the back arrow icon of the 'edit metadata' screen takes back to the folder, instead of the list of media in the process of being uploaded.

**To Reproduce**
1. Select multiple media to be uploaded
2. Select one to edit its metadata
3. Click on the back arrow
4. The app show the folder, and not the list of media, which is the actual previous screen

**Expected behavior**
Users should be taken back to the preview/list of the batch of media they selected for upload.

**Screenshots**
![Screenshot_20230823-094923](https://github.com/OpenArchive/Save-app-android/assets/4558756/0908f378-1e48-4cef-80a1-3d72d0ec3834)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Comment by tladesignz** [comment]
@purvi-ranawat, I fixed this recently while reworking the whole workflow as per new design specs.

**Comment by purvi-ranawat** [comment]
This is working fine now.
 Environment : 
OS : Android 11, Android 13
Device : Samsung Galaxy A70, Samsung Galaxy A13
Build Version : 0.3.0-beta3
