### ISSUE TITLE
'Remove Media' does not work

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#471]
**Describe the bug**
After having selected a media for upload, it is impossible to remove it. 'Remove Media' has no effect.

**To Reproduce**
1. Select media to be uploaded
2. Cancel upload journey
3. View media not yet uploaded
4. Click on the 'three dots' icon, select 'Remove Media'
5. The media hasn't been removed in any screen

**Expected behavior**
The media should be removed from the app.

**Screenshots**
![Screenshot_20230823-095630](https://github.com/OpenArchive/Save-app-android/assets/4558756/3256a67c-f0e5-41f2-8c89-62c57775dbab)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Additional context**

**Comment by foundscapes** [comment]
@uniqx can you ensure this is resolved with the new designs?

**Comment by tladesignz** [comment]
@purvi-ranawat, this is already resolved with recent changes.

**Comment by purvi-ranawat** [comment]
This is working fine now.
Environment :
OS : Android 11, Android 13
Device : Samsung Galaxy A70, Samsung Galaxy A13
Build Version : 0.3.0-beta3
