### ISSUE TITLE
“No application can handle this request. Install a web browser” message when trying to 'Open Link' of a media uploaded (on Dropbox)

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#472]
**Describe the bug**
“No application can handle this request. Install a web browser” message when trying to 'Open Link' of a media uploaded (on Dropbox)

**To Reproduce**
1. Fully upload a media on Dropbox
2. Select media
3. Click on the share icon
4. Select 'Open Link'
5. “No application can handle this request. Install a web browser” is displayed

**Expected behavior**
The link should open in the default web browser.

**Screenshots**
![Screenshot_20230823-100313](https://github.com/OpenArchive/Save-app-android/assets/4558756/37d365c2-8cc8-4e70-b4eb-69e7b32c909f)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Comment by tladesignz** [comment]
This whole scene was reworked completely. That feature isn't available anymore.

It was actually a remnant from the very first version of the app, where it solely worked with Internet Archive. This doesn't make sense in any other circumstance.
