### ISSUE TITLE
The indents of options under ‘General Settings’ is too strong.

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#473]
**Describe the bug**
The indents of options under ‘General Settings’ is too strong.

**To Reproduce**
1. Go to General Settings

**Expected behavior**
The options should be aligned on the left edge, like other screens.

**Screenshots**
![Screenshot_20230823-100454](https://github.com/OpenArchive/Save-app-android/assets/4558756/a7d8721e-41b1-4784-8c24-fdafb9001d08)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Additional context**

**Comment by tladesignz** [comment]
Won't fix. This scene uses Android-provided infrastructure for settings. This is what Android wants scenes doing these kind of things should look like.
