### ISSUE TITLE
Clicking on Upload for one single media upload doesn’t provide any user feedback. User needs to click on the back arrow to confirm the media was uploaded.

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#475]
**Describe the bug**
Clicking on Upload for one single media upload doesn’t provide any user feedback. User needs to click on the back arrow to confirm the media was uploaded.

This doesn't happen if 'Upload' is clicked on in the 'edit metadata' screen. In this case the app transitions back to the folder, which shows the media is being uploaded via a spinner animation.

**To Reproduce**
1. Select one media to be uploaded
2. Click 'Upload'
3. The app remains on the same screen

**Expected behavior**
Something should confirm the media was or wasn’t uploaded, or the app should transition bacl to the folder as it does when 'Upload' is clicked on in the 'edit metadata' screen.

**Screenshots**
![Screenshot_20230823-102415](https://github.com/OpenArchive/Save-app-android/assets/4558756/5ffc722f-8163-44b2-900f-3c7679ebe8ba)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Additional context**

**Comment by uniqx** [comment]
fixed by c9bc23d
available in 0.3.0-alpha8

**Comment by purvi-ranawat** [comment]
This is working fine now.

Once we click on Upload, it takes us directly to My Media screen where the uploading status is shown along with the spinner

Environment : 

OS : Android 11, Android 13

Device : Samsung Galaxy A13, Samsung Galaxy A70

Build version : 0.3.0-alpha8
