### ISSUE TITLE
App is visually jittery when in the process of uploading media

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#476]
**Describe the bug**
App is visually jittery when in the process of uploading media

**To Reproduce**
1. Upload media
2. While the upload is happening, click on another media's thumbnail
3. The app glitches and jitters back to the folder

**Expected behavior**
An upload should not affect the UX.

**Screenshots**
https://github.com/OpenArchive/Save-app-android/assets/4558756/36034653-fb55-4f2f-b922-ee533f6af5d4

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Comment by foundscapes** [comment]
@purvi-ranawat can you test this? ty

**Comment by foundscapes** [comment]
@vanichitkara please test and close if this is not happening for you, it's not happening for Alex or I, ty!

**Comment by purvi-ranawat** [comment]
@foundscapes : This is working fine for me

Environment : 
OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build Version : 0.3.0-beta6

**Comment by foundscapes** [comment]
great, thanks @purvi-ranawat
