### ISSUE TITLE
App can't seem to open some folders while uploading

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#477]
**Describe the bug**
App can't seem to open some folders while uploading.

**To Reproduce**
1. Upload a media in a folder
2. While the upload is in process, open the right-hand side navigation panel
3. Select another folder
4. The app won't display the folder, but the choice between 'Create New Folder' and 'Browse Existing Folder'

**Expected behavior**
The app should display the folder selected.

**Screenshots**
https://github.com/OpenArchive/Save-app-android/assets/4558756/9b9d7578-802b-4515-bb01-7eb8a1cec284

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Additional context**

**Comment by uniqx** [comment]
fixed by 8d0d779 (merged into master, but not tagged/released yet)

**Comment by uniqx** [comment]
will be released in 0.3.0-alpha8

**Comment by purvi-ranawat** [comment]
This is working fine. 

When we select the media for uploading in one folder and while the media is still uploading, if we select another folder, the second folder is opened.

Environment : 

OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Version : 0.3.0-alpha8

**Comment by foundscapes** [comment]
@hiromipaw so we can close this, yes?
