### ISSUE TITLE
Visual glitch when uploading media across multiple folders

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#478]
**Describe the bug**
The content (thgumbnails of media uploaded) of the folder/screen is displayed in odd positions.

**To Reproduce**
1. Create multiple folders and upload media in each

**Expected behavior**
The thumbnails should be consistently displayed.

**Screenshots**
![Screenshot_20230823-110325](https://github.com/OpenArchive/Save-app-android/assets/4558756/ebf7196c-c03f-4aea-b446-def81a128ddc)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Comment by tladesignz** [comment]
These parts where completely overhauled in the meantime. We'll track any problems in new issues.
