### ISSUE TITLE
Creating a new folder doesn’t take the user to the newly created folder, but to the folder they were viewing beforehand

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#479]
**Describe the bug**
Creating a new folder doesn’t take the user to the newly created folder, but to the folder they were viewing beforehand

**To Reproduce**
1. View Folder A
2. Create Folder D
3. The app shows Folder A

**Expected behavior**
The app should display the newly created folder.

**Screenshots**
https://github.com/OpenArchive/Save-app-android/assets/4558756/bcbe8cfa-9292-47ab-a6b4-0d54282666f0

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Comment by tladesignz** [comment]
Thanks for that hint!

@purvi-ranawat, will be contained in new alpha release which I'll do right after this.

**Comment by purvi-ranawat** [comment]
This is working fine.

OS Version : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
App Version : 0.3.0-alpha6
