### ISSUE TITLE
Upload process remains a bit unclear

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#480]
**Describe the bug**
For instance, canceling the upload of a batch of media, and then deciding to upload other media shows the media that were previously selected for the first upload, together with what has just been selected for the second upload.

In this case, it does make sense that clicking the back arrow doesn't cancel the upload, but this is not significantly signposted to the user. A user might need to have an upload queue, but might equally want to cancel the uploading of a media definitely.

I would be useful to title the screen that lists _all_ the media selected for upload something like 'Upload Queue,' and clearly signpost that selecting a media adds it to this Upload Queue.

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Comment by tladesignz** [comment]
@purvi-ranawat: Cancelled uploads will now be properly deleted. Will be released in version 0.3.0-beta5.

**Comment by foundscapes** [comment]
@purvi-ranawat can you test to make sure this is working for you? it's fine for us

**Comment by purvi-ranawat** [comment]
This is working fine now. Cancelling the uploads now deletes the media.

Environment : 
OS : Android 11, Andriod 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build Version : 0.3.0-beta7
