### ISSUE TITLE
‘Ready to upload’ media within folders each have a ‘Ready to upload’ title, instead of all being under a single rubric ‘Ready to upload’

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#481]
**Describe the bug**
‘Ready to upload’ media within folders each have a ‘Ready to upload’ title, instead of all being under a single rubric ‘Ready to upload’

**To Reproduce**
1. Upload mutiple media in the same folder

**Expected behavior**
The screen should be a grid view, and have one single rubric "ready to upload," and a single rubric "uploaded."
Right now it combines the worst aspects of both grid and list view.

**Screenshots**
![Screenshot_20230823-110325](https://github.com/OpenArchive/Save-app-android/assets/4558756/62319c27-6242-416c-b723-d1dccfe7daee)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Comment by tladesignz** [comment]
@purvi-ranawat, I fixed this recently on the fly.

**Comment by purvi-ranawat** [comment]
This is working fine now.
Environment :
OS : Android 11, Android 13
Device : Samsung Galaxy A70, Samsung Galaxy A13
Build Version : 0.3.0-beta3
