### ISSUE TITLE
Proofmode screen does not have extra info as to why it needs the permission to make phone calls

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#482]
**Describe the bug**
Proofmode screen does not have extra info as to why it needs the permission to make phone calls.

**To Reproduce**
1. Go to Proofmode in General Settings

**Expected behavior**
An explanation should be provided, as per designs.

**Screenshots**

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Additional context**

**Comment by tladesignz** [comment]
@hiromipaw: Please bring texts/wireframes/any advice what should be shown where!

**Comment by hiromipaw** [comment]
![ProofMode](https://github.com/OpenArchive/Save-app-android/assets/1177650/fd7e18d3-e3a7-478a-92b5-d01653147fc6)

The text should say:

```
ProofMode gathers metadata from local cell towers to help verify media. Android requires permission to enable this setting. Save will only use this setting to capture data and will NOT access your phone to make/manage calls.
```

This view is opened from the general settings:

![General](https://github.com/OpenArchive/Save-app-android/assets/1177650/1571add1-12db-4a1a-8517-38421ca86056)

**Comment by hiromipaw** [comment]
Related issue: https://github.com/OpenArchive/Save-app-android/issues/445

**Comment by tladesignz** [comment]
@purvi-ranawat: Will be contained in releases **after** 0.3.0-alpha5 build 20534.

**Comment by tladesignz** [comment]
Note: We are using Android-provided Settings infrastructure here, so the UI *is not exactly* like in the UI templates.

**Comment by purvi-ranawat** [comment]
This is working fine.

Below is the details : 

OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
App Version : 0.3.0-alpha6
