### ISSUE TITLE
Requiring users to add another account or connect another space by clicking on an already connected platform isn’t user friendly

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#483]
**Describe the bug**
Requiring users to add another account or connect another space by clicking on an already connected platform isn’t user friendly.

**Expected behavior**
The option should also be present inside General Settings, and/or somewhere clearly visible in the right navigation panel (eg. next to ‘Add folder’).

**Screenshots**
![Screenshot_20230823-112854](https://github.com/OpenArchive/Save-app-android/assets/4558756/d2ac2de3-4bf5-4edd-8e48-133651ff9e44)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Additional context**

**Comment by foundscapes** [comment]
@benjaminroyer are you just saying that our updated ux designs aren't optimal for this part or that the app wasn't conforming to the updated designs? These designs are now implemented, so hopefully it's the latter! ty

**Comment by tladesignz** [comment]
I think he's saying that this design is bad. It's like the old Windows problem: Pressing on "Start" to stop the system.

And he's right. This needs some rethinking. But probably not the most important of our concerns, currently.

**Comment by foundscapes** [comment]
we're working on a ux fix so that servers/folders are top-level, coming soon
