### ISSUE TITLE
Clicking on ‘Acquire key’ option when user wants to add an Internet Archive account lead to a black screen that renders the app unusable

### ISSUE THREAD

**Issue by benjaminroyer** [OpenArchive/Save-app-android#484]
**Describe the bug**
Clicking on ‘Acquire key’ option when user wants to add an Internet Archive account lead to a black screen that renders the app unusable.

**To Reproduce**
1. Add another account
2. Select Internet Archive
3. Click ‘Acquire key’

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 7a
 - App Version 0.3.0-alpha5

**Additional context**

**Comment by tladesignz** [comment]
Cannot reproduce. I see the Internet Archive login page just fine. When I disconnect the Internet, I see a "Website not available" screen.

Can you elaborate on the circumstances when this happens? How often does it happen?

**Comment by foundscapes** [comment]
I can't reproduce either. @purvi-ranawat can you test this with the new beta1 version and see if it's resolved? thanks!

**Comment by purvi-ranawat** [comment]
@foundscapes / @tladesignz : This is working fine. Now on clicking on Acquire key does not leads to the black screen and shows the Log in Screen for Internet Archive

**Comment by purvi-ranawat** [comment]
@foundscapes / @tladesignz : This is working fine. Now on clicking on Acquire key does not leads to the black screen and shows the Log in Screen for Internet Archive.

Environment : 
OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build : 0.3.0-beta2
