### ISSUE TITLE
Back arrow on the upload screen is not visible

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#485]
**Describe the bug**
When we select the media, upload screen is displayed. On this screen, as the background is black, the back arrow is not visible. 

**To Reproduce**
1. Go to Save App
2. Click on "+" icon to select the media
3. Once we select the media, view the upload screen

Actual Result : 
Back arrow on the Upload screen is not visible as the background is black

Expected Result : 
Back arrow on the Upload screen should be in the color which is visible to the user

**Environment (please complete the following information):**
 - OS version: Android 11, Android 13]
 - Device: Samsung Galaxy A13, Samsung Galaxy A70
 - App Version : 0.3.0-alpha5

**Comment by tladesignz** [comment]
This should be fixed while reworking the media selection flow in #441.

**Comment by foundscapes** [comment]
Is this fixed @tladesignz ?

**Comment by tladesignz** [comment]
With latest commits, but not released, yet.

@purvi-ranawat, please confirm with builds after 0.3.0-beta1 due next week latest.

**Comment by purvi-ranawat** [comment]
@tladesignz This is working fine on Android 11, Android 13, Device Samsung A13, Samsung Galaxy A70. app version 0.3.0-beta 2
