### ISSUE TITLE
(Internet Archive) : "i" icon and the "eye" icon on the Secret Key field overlaps each other

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#486]
**Describe the bug**
On the Internet Archive Login screen, when we click on Next without entering the Access Key and Secret Key, the icon "i" and "eye" icon overlaps each other for Secret Key field

1. Click on Add Account on save App
2. Select Internet Archive
3. Without clicking on Acquire Keys or entering Access Key / Secret Key, click on Next

Expected behavior : 
"i" icon and "eye" icon on the Secret Key field should not overlap each other

Actual Result : 
the icon "i" and "eye" icon overlaps each other for Secret Key field

Screenshots : 

![image](https://github.com/OpenArchive/Save-app-android/assets/8190141/10a1d8dd-7bd1-4a81-9fa5-8012b8cc6320)

**Environment (please complete the following information):**
 - OS version: Android 11, Android 13
 - Device: Samsung Galaxy A70, Samsung Galaxy A13
 - App Version : 0.3.0-alpha5

**Comment by tladesignz** [comment]
This is system behaviour. Finding a fix for that is going to be very low on my priority.

**Comment by foundscapes** [comment]
@purvi-ranawat this isn't showing up for Alex anymore (it was never an issue for me), can you please test this on beta5 and then close if it's fixed for you.

**Comment by foundscapes** [comment]
@vanichitkara please test this and close if it's also working for you!

**Comment by purvi-ranawat** [comment]
@foundscapes : The issue still exists for me. I have tested the same on 0.3.0-beta6

**Comment by foundscapes** [comment]
@purvi-ranawat thanks, we will wait for @tladesignz  to work on this when he can.

**Comment by foundscapes** [comment]
@vanichitkara can you test this on beta7? ty!

**Comment by tladesignz** [comment]
I advise to let @uniqx take care of this, since he's very versed with Android UI.

**Comment by vanichitkara** [comment]
@foundscapes The icons are not overlapping for me

![Screenshot_2023-11-16-08-31-38-47_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/8194bb4d-57a1-4284-ba1b-0d787c09fe18)

OS version: Android v13.0
Device: OnePlus 11R 5G
App Version 0.3.0-beta7
