### ISSUE TITLE
It shouldn't be possible to add a second account for dropbox as I think the API doesn't allow that.

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#487]
The app allows a user to add a second dropbox account even if the api doesn't allow it.

![](https://user-images.githubusercontent.com/4558756/262640478-d2ac2de3-4bf5-4edd-8e48-133651ff9e44.png)

**Comment by tladesignz** [comment]
I think that's a misunderstanding out of the messed up UI. When you tap the (+), it doesn't show you the option to add another Dropbox account.

This is better handled in #483.

**Comment by hiromipaw** [comment]
Ok let's close this and let's keep #483 only.
