### ISSUE TITLE
For IA login - acquire keys shows up after key are acquired - need to change to confirmation instead

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#489]
**I Wish...**
that once I have gone to the IA, logged in, acquired keys, are back in the Save app, that I would have a confirmation that keys have been acquired on that page instead of the option to acquire keys again. 

this is how it looks: 
![Screenshot_20230822-130254](https://github.com/OpenArchive/Save-app-android/assets/2231711/be7df747-8bb8-4a9b-8861-52d2af4c9a5c)

**Comment by tladesignz** [comment]
Related to #436
