### ISSUE TITLE
Extend Clean Insights measurements

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-android#491]
> Howdy,
> 
> Are you set to do the code implementation for iOS?  And can you work with uniq on getting the Android one done as well?  As I understand it, the data points to collect are:
> 
> - Which backends folks are using.  I would consider this to be collecting when a user sets up a new backend (each setup of a backend would count, so if they have 2 Next Cloud, that's 2 events).  I would assume doing this on a weekly cadence would be sufficient.
> - "How much data is being uploaded".  I would consider this to be collecting the sum of uploads per week per backend.  E.g. at the end of the week, reporting "John uploaded 3 things to NextCloud and 1 to the Internet Archive".
> 
> Ofc, y'all know better than I your use case so do what suits you :-)

**Comment by tladesignz** [comment]
The consent screen is not up to par with iOS, yet.

**Comment by ryjen** [comment]
I am wondering if clean insights could also do some basic error reporting to see the impact of a bad experience.

Specifically, upload failures.  Let me know what you think.  @tladesignz @foundscapes

**Comment by tladesignz** [comment]
Hmmm. Not sure what you actually want to achieve.

CleanInsights is an anonymizing analytics tool. It will purposefully degrade the resolution of taken measurements (e.g. it will only tell you that something happened x times in a certain time period, not report every event) and strip identifying information like IP addresses.

The main reason we actually added it is, to do GuardianProject a favour. I don't think, anybody here seriously looks at the accrued data, currently, besides maybe John, the project lead of CleanInsights.
Maybe, someone(tm) should start doing that, though.


Before you start thinking something like, "hey, let's add Google Analytics then", please be aware, that the target audience of this app is people, who may be under heavy state surveillance or politically persecuted, and people, who are from the digital rights/privacy movement. Adding privacy invading libs to Save won't fly with these folks.

Also, our sponsors are from this area, and wouldn't really appreciate anything like that, AFAIU.

**Comment by ryjen** [comment]
Yes, I see. I was trying to achieve some data for priority or UX, and I suppose that's why I was asking if CleanInsights could be used for such a purpose, but I did not realize it was purposefully degrading as well.  Thanks.

**Comment by tladesignz** [comment]
Still, CleanInsights could give you some... insights. :-)
We're already recording upload failures:
- Android: [UploadService - try_upload](https://github.com/OpenArchive/Save-app-android/blob/master/app/src/main/java/net/opendasharchive/openarchive/upload/UploadService.kt#L162) -> [UploadManagerActivity - upload_failed](https://github.com/OpenArchive/Save-app-android/blob/master/app/src/main/java/net/opendasharchive/openarchive/upload/UploadManagerActivity.kt#L65-L70)
- iOS: [UploadManager - try_upload](https://github.com/OpenArchive/Save-app-ios/blob/master/Save/Management/UploadManager.swift#L560) -> [UploadManager - upload_failed](https://github.com/OpenArchive/Save-app-ios/blob/master/Save/Management/UploadManager.swift#L392-L428)

You can find the CleanInsights backend here: https://github.com/OpenArchive/Save-app-android/blob/master/app/src/main/assets/cleaninsights.json#L2
(sans the `cleaninsights.php`, that's the API endpoint for the CleanInsights library.)

Let me know via Signal, if you want an account there to look at the data, then I'll get you in touch with John.
