### ISSUE TITLE
Rework empty main scene

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-android#495]
This is branched out from #437:

![Home - First time user](https://github.com/OpenArchive/Save-app-android/assets/1177650/1a233ae6-842c-42a3-be1d-b027c9702343)

![Home - First time user no project](https://github.com/OpenArchive/Save-app-android/assets/1177650/9c03eaf3-51c0-4f0e-bf3b-e60088827bc3)

**Comment by tladesignz** [comment]
I didn't implement the (possibly animated) arrow.

I'll leave this exercise to @uniqx but I suggest to put this at the very end. It seems like the opposite of a "quick win".

**Comment by tladesignz** [comment]
Also, I guess the styling of alert dialogs should be done in one go, as that's probably mostly about modifying the general style. Probably create own issue for this, @hiromipaw. And don't stick to the design too much. Only what's easy to achieve with Android.

**Comment by tladesignz** [comment]
@purvi-ranawat, please QA general functionality with upcoming build 0.3.0-alpha7, 20536 and later.

**Comment by tladesignz** [comment]
Note: Known bug: When deleting last media item, doesn't show again until fragment is reloaded. `MediaListFragment` / `MediaGridFragment` needs some major refactoring. That stuff is still a mess.

**Comment by purvi-ranawat** [comment]
This is working fine.

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-android/assets/8190141/af80e12e-f8d6-4dc5-8e8e-52d97822c1cd)




![Image](https://github.com/OpenArchive/Save-app-android/assets/8190141/e8188852-9ece-4774-acc5-30216a91d963)



Environment : 

OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Environment : 0.3.0-alpha7
