### ISSUE TITLE
"Welcome..Tap the button below.." text is displayed on Uploading screen

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#498]
Bug Description : 
On Uploading screen, "Welcome.Tap the button below to add media" text is displayed and then we get the Uploading status for each media. But the text should not be displayed on uploading screen

1. Go to Save App
2. Click on "+" icon to select the folder and select few images / videos
3. Click on Upload
4. On My Media screen, all the images selected for uploading is displayed with the processing icon
5. Click on the number on top right side of My media screen which shows total images remaining for uploading

**Expected behavior**
When we click on the number, uploading screen is displayed with the upload status of each image. But on this screen, the welcome message should not be displayed

**Screenshots**
![image](https://github.com/OpenArchive/Save-app-android/assets/8190141/2d912857-4b83-423e-8de4-b741f28bc548)

**Environment (please complete the following information):**
 - OS version: Android 11, Android 13
 - Device: Samsung Galaxy A70, Samsung Galaxy A13
 - App Version : 0.3.0-alpha7

**Comment by foundscapes** [comment]
This is still an issue in 0.3.0-beta1

**Comment by tladesignz** [comment]
@purvi-ranawat, this is fixed in 0.3.0-beta3, which I just dropped at the Play Store. Should be available tomorrow.

**Comment by foundscapes** [comment]
fixed!
