### ISSUE TITLE
Add upload chunking setting for webdav

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#499]
For the new webdav view we have a setting to use upload chunking. We should get that implemented for the space settings.

See: https://github.com/OpenArchive/Save-app-android/issues/434

![Private Server - Log In](https://github.com/OpenArchive/Save-app-android/assets/1177650/1deb4290-bce7-41bb-87b4-b4e026b6fc8c)

**Comment by tladesignz** [comment]
QA to be continued in #434.
