### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [OpenArchive/Save-app-android#50]
It would be great to have this on the https://f-droid.org/ catalog

**Comment by ghost** [comment]
@n8fr8 I just added the metadata with https://gitlab.com/fdroid/fdroiddata/commit/e368d736e51c9a47830c17436e07cac265b09ce6. Note that I added the `Binaries:` field. If it fails, should I try to nag @eighthave or someone? Or is it ok to build with an fdroid key?

**Comment by pizzamaker** [comment]
@krt16s ^

**Comment by n8fr8** [comment]
Looks like it is working: https://f-droid.org/packages/net.opendasharchive.openarchive.release/

Can we get it updated to the latest release?

**Comment by eighthave** [comment]
you can either do a merge request to
https://gitlab.com/fdroid/fdroiddata that adds the new release manually.
 Or you can set `Auto Update Mode` to automatically update when there is
a new git tag that matches the specified pattern.
