### ISSUE TITLE
Grammar issue on "Verify" onboarding screen

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#500]
Please change the language to read: Authenticate your media with a cryptographic verification sha256 hash and optional ProofMode. 

(remove the comma after "hash" and before "and")

![IMG_8630](https://github.com/OpenArchive/Save-app-android/assets/2231711/41067fce-df64-46eb-955c-dbfae8094896)

**Comment by uniqx** [comment]
fixed by https://github.com/OpenArchive/Save-app-android/commit/ca83e1507a723e0046f3e7727f05bfc95099637c
available in 0.3.0-alpha9

**Comment by purvi-ranawat** [comment]
This issue is resolved.
Environment :
OS : Android 11, Android 13
Device : Samsung Galaxy A70, Samsung Galaxy A13
Build Version : 0.3.0-beta3

**Comment by purvi-ranawat** [comment]
@foundscapes  : I have tested it on beta3. I will update my app to beta4 and test again and update the same here.

**Comment by purvi-ranawat** [comment]
@foundscapes / @tladesignz : Tested on beta4 version also and it is working fine on beta4
