### ISSUE TITLE
Last image on My Media screen is not visible

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#501]
Bug Description : 

When we select few images and videos, the last image / video is not displayed fully on My Media screen. We are not able to scroll to the view the last image / video

1. Go to Save App
2. Select few images / videos and click on Upload
3. Scroll down on My Media screen

Expected behavior : 
All the images / videos selected for uploading should be visible properly

Actual Result : 
The last image / video selected is not visible properly

Screenshots / Video : 

https://github.com/OpenArchive/Save-app-android/assets/8190141/f6b5b6f7-d344-4235-b3c6-e9fae58c9aaf

Environment (please complete the following information) : 
 - OS version: Android 11, Android 13
 - Device: Samsung Galaxy A70, Samsung Galaxy A13
 - App Version : 0.3.0-alpha7

**Comment by foundscapes** [comment]
This should be fixed once the new designs are implemented

**Comment by foundscapes** [comment]
@tladesignz was this fixed? if so, @purvi-ranawat please re-test, thanks!

**Comment by purvi-ranawat** [comment]
@tladesignz / @foundscapes : This is working fine now. I am able to see full last image.

Environment : 
OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build version : 0.3.0-beta6

**Comment by foundscapes** [comment]
thanks @purvi-ranawat!
