### ISSUE TITLE
Rename "space" to "server" everywhere the user sees that word

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-android#504]
See https://github.com/OpenArchive/Save-app-android/issues/447#issuecomment-1738037009

**Comment by tladesignz** [comment]
@purvi-ranawat: This will be available in builds in and after 0.3.0-beta2. Thank you!

**Comment by purvi-ranawat** [comment]
This is working fine.

"Server" is displayed in place of Space now

Environment : 

OS : Android 11, Andriod 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build Version : 0.3.0-beta 3
