### ISSUE TITLE
Word choice & spelling issue on General Settings page

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#505]
**Describe the bug**
1. For General Settings / "Presentation"
Rename "Style" to "Theme"

2. Under "Style" 
Please change "Safe" to "Save" and have the text read: Change **_Save's_** theme to light/dark

**Screenshots**
![Screenshot_20231009-144901](https://github.com/OpenArchive/Save-app-android/assets/2231711/2e653921-b9b5-40fa-ab79-6a4818338637)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 3a
 - App Version 0.3.0-beta1

**Comment by tladesignz** [comment]
@purvi-ranawat, this will be contained in version 0.3.0-beta2 and after.

**Comment by foundscapes** [comment]
@tladesignz the is definitely better in beta2 - but we need to change "Style" to "Theme" 
Thank you!

**Comment by tladesignz** [comment]
Uuupsi. @purvi-ranawat, fix will be contained in 0.3.0-beta4 not due until next week.

**Comment by purvi-ranawat** [comment]
This is working fine on Version 0.3.0-beta4.
Tested on Android 11 and Android 13 on Samsung Galaxy A13, and Samsung Galaxy A70.
