### ISSUE TITLE
Change the language on Creative Commons settings. 

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-android#509]
New language:

“Set the same Creative Commons license for ALL folders on this server.”
“Set unique Creative Commons licenses for EACH INDIVIDUAL folder on this server.”

Reason:
In settings, the Creative Commons page is maybe a bit confusing to users who are not very technical/not familiar with creative commons. We want to make it clear what the toggle at the top does (set license settings for all folders) vs what the folder specific settings are.

**Comment by tladesignz** [comment]
@purvi-ranawat, this will be fixed in version 0.3.0-beta4 not due for release until next week.

**Comment by purvi-ranawat** [comment]
@tladesignz This is working fine on Version 0.3.0-beta4. 
Tested on Android 11 and Android 13 on Samsung Galaxy A13, and Samsung Galaxy A70.
