### ISSUE TITLE
Add Google Drive as a new backend

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#511]
I wish we could use Save to send media to Google Drive because many of our DACs would like to use it as a backend for their verified collections. (to be done after 2.0 ux android and ios updates are finished, unless Michi can do this for android while benjamin works on ios (ideal scenario)

**Comment by tladesignz** [comment]
iOS sibling issue: https://github.com/OpenArchive/Save-app-ios/issues/252

**Comment by uniqx** [comment]
According to gdrive docs, Save needs to register with Google Cloud Console to obtain access credentials. (credentials.json?) https://developers.google.com/drive/api/quickstart/java#set_up_your_environment @tladesignz @foundscapes  Could you provide these credentials to me?

**Comment by foundscapes** [comment]
Thanks for letting us know @uniqx -  Save needs an account with Google Cloud Console and use that account, to create a API key for Google Drive. @tladesignz can you set this up for us?

**Comment by uniqx** [comment]
During working on this feature, I've discovered this ANR on Android 14: #534

**Comment by uniqx** [comment]
I 've merged Android GDrive support into master now, so the next release will come with GDrive support.

While it seames to be working reliable in my tests, it might still be rough around some edges, so I recommend rigorous testing.

I'm also aware of some edge cases we could look into, if you think it's worth more time:
* handling connection interruptions by retrying uploads. I saw that dropbox implements this, I've found no evidence of GDrive supporting such a feature, of if this would be entirely custom code)
* handling remote permission revocations. Google Drive users have the option to remove Save from the list of allowed apps in the settings section of GDrive. If that happens, all uploads will show following error

<img width="111" src="https://github.com/OpenArchive/Save-app-android/assets/674081/6a591e0e-4c1f-4467-95ab-531c7d319675" />
<img width="111" src="https://github.com/OpenArchive/Save-app-android/assets/674081/b4847ef5-1d58-478c-9f1f-6fe638f191c8" />

---

Next steps are to add the fingerprints of the Save release certificate to cloud console
```
SHA1: A4:FA:BD:AA:6E:72:1C:08:1F:ED:A1:66:03:FE:98:F5:CF:57:F1:24
SHA256: E0:8E:63:CA:87:FD:B9:32:47:DB:AB:38:F2:E7:F4:10:48:96:BB:48:7A:F5:98:08:38:AC:E6:4C:93:C1:5A:3C
```

Here's what this looks like on cloud console with my dev credentials:

<img width="200" src="https://github.com/OpenArchive/Save-app-android/assets/674081/3aad0e17-08bb-48df-ab18-5b44c5a7f77a" />
<img width="200" src="https://github.com/OpenArchive/Save-app-android/assets/674081/2beeef15-202e-4021-8906-cb7447f97bf8" />

**Comment by tladesignz** [comment]
As per the latest prophecies of the Google gods, please reduce requested permission scopes to "https://www.googleapis.com/auth/drive.file".

Otherwise, we'll never accepted by them.

The existing folder selector can stay, since we can at least show the folders, which Save created itself.

**Comment by tladesignz** [comment]
TODOs:

- Remove "metadata.readonly" scope.
- The big "Google Drive" selector button needs a "tm" sign after "Google Drive".
- The Authorization scene needs some disclaimers:
  https://github.com/OpenArchive/Save-app-ios/blob/master/Save/Space/GdriveWizardViewController.swift#L41-L73
- Deny authentication, when user didn't select the needed scope: https://github.com/OpenArchive/Save-app-ios/blob/master/Save/Space/GdriveWizardViewController.swift#L105-L138
- Don't show an error, when the user cancelled the authorization process: https://github.com/OpenArchive/Save-app-ios/blob/master/Save/Space/GdriveWizardViewController.swift#L117-L122

**Comment by uniqx** [comment]
all listed TODOs fixed, and merged; will become available in 0.3.1-alpha2

**Comment by tladesignz** [comment]
Is this ready for QA? If so, please assign to Purvi and set project status to "awaiting QA". Thanks!

**Comment by foundscapes** [comment]
@purvi-ranawat please test asap

**Comment by purvi-ranawat** [comment]
@foundscapes / @uniqx : This is working fine.

Environment : 

OS : Android 14
Device : OnePlus Nord 3 CE Lite, Samsung Galaxy A13
Build version : 0.3.1-alpha2
