### ISSUE TITLE
Upload list view (number in circle in upper right) has disappeared without "Edit" replacing it as per 2.0 designs

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#512]
**Describe the bug**
The list view is no longer visible with the teal circle and number and is instead a greyed out x/y that is unclickable (we could click on the teal circle w/ number to watch upload progress and edit from the list view). I believe this teal circle with number was going to be replaced by an "Edit" button, but that is not implemented yet so there is no way to logically get to the "edit" media list scene at the moment.

However, you can get to the list view if you tap on the in progress uploads, but it is not as intuitive/is confusing this way and doesn't follow our design update:
<img width="577" alt="Screenshot 2023-10-27 at 9 09 20 AM" src="https://github.com/OpenArchive/Save-app-android/assets/2231711/6b4c5a96-fced-4031-b7f9-e651f69bdcac">

So this doesn't get lost in the shuffle, please implement the Edit button as per the designs

**To Reproduce**
1. Add at least one file to upload to your connected server
2. click "upload"
3. try to find a place to edit the media / see the list view - and it's not apparent 

**Expected behavior**
Once the user has added media, they should be able to see the "Edit" button so they know where to edit it before upload.

**Screenshots**
![Screenshot_20231027-090845](https://github.com/OpenArchive/Save-app-android/assets/2231711/ab38dc08-ec2a-46f5-8ed1-aaedf84364b8)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 3a
 - App Version 0.3.0-beta4

**Additional context**
Also, to note - the app crashed 4 times during this process of attempting to upload two files and, once, when I clicked "close app" after the crash, it not only kept me in the app, but the previous successful upload and the upload in progress disappeared. When I closed the app and came back to it, they were both there, showing as uploaded.

**Comment by tladesignz** [comment]
Fixed with dd3907faac56cfc23fdac124838fa28938098c0f

**Comment by tladesignz** [comment]
@purvi-ranawat, this will be contained in release 0.3.0-beta5.

**Comment by purvi-ranawat** [comment]
This is working fine on Version 0.3.0-beta5.
Tested on Android 11 and Android 13 on Samsung Galaxy A13, and Samsung Galaxy A70.
