### ISSUE TITLE
Unexpected behavior in multiple areas of the upload process since beta5 release

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#513]
**Describe the bug**
2/3 photos I tried to upload did not upload, were not able to be cleared from the edit scene, and none of the 3 (including one successful upload) showed up on the gallery view. Then the app crashed, multiple times.

**To Reproduce**
1. Add files to be uploaded
2. Click on upload
3. Error shows up 
4. Unable to delete or retry upload files from edit/list view
5. Neither the unsuccessful uploads nor the successful upload show in the gallery scene (attempted to upload on 10/32/23 vs. what shows on gallery from 10/27/23).

**Expected behavior**
There should be a way to retry upload and also delete them from the list/edit view for the images that didn't upload 
All images should show up in the gallery scene, the ones that didn't upload would be grayed out and the one that did would be clear.

**Screenshots**

![Screenshot_20231031-102948](https://github.com/OpenArchive/Save-app-android/assets/2231711/ff1d233f-0093-4054-84cb-efe38be5cc06)
![Screenshot_20231031-102832](https://github.com/OpenArchive/Save-app-android/assets/2231711/808f7d25-e72a-4d96-9a1c-f116ab585063)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Google Pixel 3a
 - App Version 0.3.0 - beta5

**Additional context**
There were a number of other issues related to this scene that I don't have time to make separate issues for now, so will document them here until I have more time:
- The designs are not matching the updated ux designs in issue #442 such as the trash bins to the left of the images + error messages, etc. - which may fix some of these issues?
- there is no % progress shown in the teal circles on either the gallery or list/edit scenes and there should be 
- Reordering still not sticking in edit list scene

**Comment by tladesignz** [comment]
> **Describe the bug** 2/3 photos I tried to upload did not upload, were not able to be cleared from the edit scene, and none of the 3 (including one successful upload) showed up on the gallery view. Then the app crashed, multiple times.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Add files to be uploaded
> 2. Click on upload
> 3. Error shows up
> 4. Unable to delete or retry upload files from edit/list view

Delete: Hit "Edit", then swipe item to the left.
The design templates actually show iOS behaviour, Android UX guidelines don't do this trash can thing.

About 2/3rds scrolled down on [this webpage](https://www.digitalocean.com/community/tutorials/android-recyclerview-swipe-to-delete-undo), you can see an example of how it should look like in Android.
(Have to admit, I forgot the undo part.)

> 5. Neither the unsuccessful uploads nor the successful upload show in the gallery scene (attempted to upload on 10/32/23 vs. what shows on gallery from 10/27/23).

Well, this should not happen, but it does not happen for me. Can you please find a way to reproduce this in a reliable fashion?
I worked on improving the `UploadService` today, so that might get better.

> **Expected behavior** There should be a way to retry upload and also delete them from the list/edit view for the images that didn't upload

- Delete: See above.
- Retry? The UI templates only show this behaviour on the main scene. Should this be available on the edit priority scene, too? When tapping on the item row when not in edit mode?

While thinking about this, I throw this on top: It might be cumbersome when a dozen or so files have failed one after another because of network issues, to restart every single one. A bulk restart would be good, wouldn't it? But how?

> * The designs are not matching the updated ux designs in issue [Implement media management options #442](https://github.com/OpenArchive/Save-app-android/issues/442) such as the trash bins to the left of the images + error messages, etc. - which may fix some of these issues?

See above.

> * there is no % progress shown in the teal circles on either the gallery or list/edit scenes and there should be

Ah, yeah. Android makes this a hard one. I created an issue for @uniqx: #516

> * Reordering still not sticking in edit list scene

Will take car of this.

**Comment by foundscapes** [comment]
> > **Describe the bug** 2/3 photos I tried to upload did not upload, were not able to be cleared from the edit scene, and none of the 3 (including one successful upload) showed up on the gallery view. Then the app crashed, multiple times.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Add files to be uploaded
> > 2. Click on upload
> > 3. Error shows up
> > 4. Unable to delete or retry upload files from edit/list view
> 
> Delete: Hit "Edit", then swipe item to the left. The design templates actually show iOS behaviour, Android UX guidelines don't do this trash can thing.
> 
Ok, this is working fine then.


> > 5. Neither the unsuccessful uploads nor the successful upload show in the gallery scene (attempted to upload on 10/32/23 vs. what shows on gallery from 10/27/23).
> 
> Well, this should not happen, but it does not happen for me. Can you please find a way to reproduce this in a reliable fashion? I worked on improving the `UploadService` today, so that might get better.

This seems fixed once I uninstalled/reinstalled the app and it's not happening in beta6.

> > **Expected behavior** There should be a way to retry upload and also delete them from the list/edit view for the images that didn't upload
> 
>     * Delete: See above.

yup. ty
> 
>     * Retry? The UI templates only show this behaviour on the main scene. Should this be available on the edit priority scene, too? When tapping on the item row when not in edit mode?
> 
> 
> While thinking about this, I throw this on top: It might be cumbersome when a dozen or so files have failed one after another because of network issues, to restart every single one. A bulk restart would be good, wouldn't it? But how?

Ooh this is a great idea. Let's figure it out?  Added to future coolness.
> 
> > * The designs are not matching the updated ux designs in issue [Implement media management options #442](https://github.com/OpenArchive/Save-app-android/issues/442) such as the trash bins to the left of the images + error messages, etc. - which may fix some of these issues?
> 
> See above.
> 
> > * there is no % progress shown in the teal circles on either the gallery or list/edit scenes and there should be
> 
> Ah, yeah. Android makes this a hard one. I created an issue for @uniqx: #516
I now see a % but it's white text over a white overlay - can @uniqx please just change the text to teal so it will show up? problem solved (unless you can get it into the circle to look more like iOs?)
> 
> > * Reordering still not sticking in edit list scene
> 
> Will take car of this.
fixed in beta6!
