### ISSUE TITLE
App crashes on trying to add the folder to the internet archive

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#514]
Bug Description : 

After connecting to Internet archive, when we click on "+" icon to add the folder for the first time, the app refreshes and My Media screen is displayed instead of New Folder screen. Then when we again click on "+" icon, the app crashes

1. Install Save App
2. Connect to Internet Archive Server
3. Click on "+" icon on My Media screen to add the folder (as it is for the first time after installation)

**Expected behavior**
New folder screen should be displayed to create new folder

Actual Result : 
App refreshes and My Media screen is displayed again. On clicking on the "+" icon again, the app crashes

Below is the video : 

https://github.com/OpenArchive/Save-app-android/assets/8190141/6a6bc1bb-a8bd-4d47-b6f7-88d7e7a3baae

**Environment (please complete the following information):**
 - OS version: Android 11, Android 13
 - Device: Samsung Galaxy A13, Samsung Galaxy A70
 - App Version : 0.3.0-beta5

**Comment by tladesignz** [comment]
Related: #517

Should be fixed in version 0.3.0-beta7

**Comment by purvi-ranawat** [comment]
This is working fine

Environment : 

OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build Version : 0.3.0-beta7
