### ISSUE TITLE
Create New Folder screen is displayed after selecting the existing folder

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#515]
Bug Description : 
For Private Server (Next cloud) and Dropbox , when we click on New Folder, it gives us the option to create new folder or browse existing folder. But on clicking on Browser existing folder and selecting the existing folder, it gives us the create new folder screen with the selected folder name already in the folder name and Create button at the top right side

Steps to Reproduce : 

1. Open Save App
2. For Dropbox or Private Server (For me, it was Next cloud), click on New Folder
3. Select Browse existing folder
4. Select the folder and click on Add

**Expected behavior**
My Media screen should be displayed and user should be able to select the media for uploading

Actual Result : 

New Folder screen is displayed with the folder selected name is displayed in Create Folder Name field and Create button at top right side

Below is the video : 

https://github.com/OpenArchive/Save-app-android/assets/8190141/3c535216-c7f2-4d2e-89cf-5a2e95aef065

**Environment (please complete the following information):**
 - OS version:  Android11, Android 13
 - Device: Samsung Galaxy A13, Samsung Galaxy A70
 - App Version : 0.3.0-beta5

**Comment by tladesignz** [comment]
Yeah, this is the result of wanting CC licensing options on every corner.

@foundscapes, please advise. If you want the user to be able to set up CC licensing for every folder on creation, then this is the price.

**Comment by foundscapes** [comment]
eek, for now, let's just implement by server/folder in the settings and revisit once android and ios ux updates are finished, ty!

**Comment by tladesignz** [comment]
*sigh* As you wish, Ma'am.

@purvi-ranawat, will be undone in release 0.3.0-beta7.

**Comment by foundscapes** [comment]
Ty @tladesignz also mentioned in #520 which we closed.
Will make a new issue to be able to add cc licensing to new folders as you create them, without it breaking desired design.

**Comment by foundscapes** [comment]
fixed in beta7
