### ISSUE TITLE
Flagged content no longer is routed to separate subfolder

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#519]
When I flag media as significant when editing the metadata (select little flag icon) it is no longer routed to a separate folder once uploaded. I tested this on both Nextcloud and Dropbox and the issue persisted

**To Reproduce**
1.Add media
2. Edit media and select the flag
3. Upload media to selected folder/server
4. Check server for upload and see that flagged media isn't in flagged/separate folder

**Expected behavior**
Media that is flagged should go into a separate folder once uploaded.

**Screenshots**
<img width="612" alt="json showing flag is true" src="https://github.com/OpenArchive/Save-app-android/assets/37166640/ec8e46b2-e88f-4c91-a7be-eb51fa2fa51a">

You can see in the json file with data from the image that flag = true but it isn't going into that separate folder

Below you can see that image isn't in separate folder
![image not in separate folder](https://github.com/OpenArchive/Save-app-android/assets/37166640/a33de573-4e6f-46f6-8f40-6780cb01018b)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Samsung Galaxy 10
 - App Version 0.3.0 beta 6

**Additional context**
was also not working on beta 5

**Comment by foundscapes** [comment]
Good catch @ceylana! This happened to me as well 

    OS version: Android 12
    Device: Google Pixel 3a
    App Version 0.3.0 beta 6

**Comment by tladesignz** [comment]
Investigated the code yesterday. Not sure the Android version ever did this. That part of the Android app is still a mess. I already started refactoring this, but won't be able to finish until next week.

**Comment by foundscapes** [comment]
@tladesignz the flagging feature was working on Android during one of our recent trainings.

**Comment by foundscapes** [comment]
@vanichitkara please test after next week, ty!

**Comment by tladesignz** [comment]
> @tladesignz the flagging feature was working on Android during one of our recent trainings.

Well, if that was so, than I destroyed it accidentally, because it must have been an ugly, undocumented hack.

I reworked this mess into something sensible.

@purvi-ranawat, this will be contained in version 0.3.0-beta7 due for release soon.

**Comment by foundscapes** [comment]
This is working fine for OA Core so I'm closing, ty all!
