### ISSUE TITLE
Some Android users in Iraq unable to log into Nextcloud

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#521]
**Describe the bug**
Certain Android app users are unable to log into NextCloud and it times out for them. 

**To Reproduce**
1. Go to connect to private server
3. enter correct URL, username and password
4. Press next
5. server does not connect and given a "timeout" error

**Expected behavior**
Once the server URL, username, and password are entered correctly, user should be connected to server.

**Screenshots**
![signal-2023-11-02-121420_002](https://github.com/OpenArchive/Save-app-android/assets/37166640/c259e99b-4c92-490d-94ef-67c2cc9b93ea)

**Environment (please complete the following information):**
 - OS version: Android v7.6.0
 - Device: Tecno spark 8c
 - App Version 0.3.0-beta6

**Additional context**
One of the users facing this issue tried logging in to the NextCloud server on the iOS version of Save and was successful so I don't think it is user error.

**Comment by foundscapes** [comment]
@vanichitkara see if this happens for you, ty!

**Comment by vanichitkara** [comment]
@foundscapes This doesn't happen with me. I'm able to log in via a private server. I think the issue might be with their internet, or the server must be having some problem at that time
OS version: Android v13.0
Device: OnePlus 11R 5G
App Version 0.3.0-beta6

**Comment by foundscapes** [comment]
@ceylana believes this was a phone-specific issue that isn't happening for others, so will close for now
