### ISSUE TITLE
Photo gallery spelt incorrectly when you long hold the + to add images

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#529]
**Describe the bug**
Just a spelling error that needs to be corrected before we film training videos. Gallery is spelt wrong in the pop-up when you long tap the + sign at the bottom of the screen

**To Reproduce**
1. Go to teal + at the bottom of the screen.
2. Long hold/tap the +
3. See pop-up that says "Photo Galery" which is incorrect

**Expected behavior**
Should say "Photo Gallery"

**Screenshots**
![signal-2023-12-06-113426_002](https://github.com/OpenArchive/Save-app-android/assets/37166640/ab518d00-db73-442f-ae3c-5546f5239362)

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Samsung Galaxy S10
 - App Version [e.g. 2.2]

**Comment by tladesignz** [comment]
This will be fixed in version 0.3.0, build 20547, which I push to release right now.

**Comment by ceylana** [comment]
thanks!
