### ISSUE TITLE
Uploaded numbers formatting change: changing color of circles 

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#530]
This is in reference to the numbers seen here:
![signal-2023-12-20-095339_002](https://github.com/OpenArchive/Save-app-android/assets/37166640/0478cec7-5fac-4006-9caa-a373e6c211d4)

Right now the light grey makes it really difficult to see the numbers, and we have accessibility concerns.

Please make the following color changes:

For dark mode: please change the grey circle to HEX color # 434343 (number should be white).
for light mode: please make sure the grey circle is HEX color #E3E3E4 (number should be black).

**Comment by ryjen** [comment]
Hi @vanichitkara this can be testing with an [internal test build](https://play.google.com/apps/internaltest/4699441400294687809) (version 0.3.2)

**Comment by losalim** [comment]
tested in 0.3.2 and colours of cirlces are fixed. android 10 moto g pure. thank you!

**Comment by vanichitkara** [comment]
This is fixed for me as well. Tested in 0.3.2 on Android 14
