### ISSUE TITLE
Bug when switching from light to dark mode (or vice-versa)

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#531]
**Describe the bug**
When user switches from light to dark mode, or vice versa, some fonts don't change colors and it looks like the screen is blank (e.g. in settings, in folders)

**To Reproduce**
1. Go to Settings, then General settings
2. Click on theme
3. Change to light or dark mode
4. See blank setting screen

**Expected behavior**
When switching from light to dark mode (or vice versa), all screens should be readable and font colors should change.

**Screenshots**

https://github.com/OpenArchive/Save-app-android/assets/37166640/e48a9b92-118a-4fe0-a976-e1c2da52655f

**Environment (please complete the following information):**
 - OS version: Android 12
 - Device: Galaxy s10
 - App Version 0.3.0

**Additional context**
n/a

**Comment by foundscapes** [comment]
@purvi-ranawat please test

**Comment by purvi-ranawat** [comment]
@foundscapes : The issue exists for me also.

Environment : 
OS : Andriod 13
Device : Samsung Galaxy A13
App Version : 0.3.0

**Comment by uniqx** [comment]
should be fixed in 0.3.1-alpha2 please test

**Comment by foundscapes** [comment]
@purvi-ranawat please test, it's working for me, ty!

**Comment by purvi-ranawat** [comment]
@foundscapes : This is working fine for me as well.

Enironment : 

OS : Android 14
Device : OnePlus Nord 3 CE Lite, Samsung Galaxy A13
Build version : 0.3.1-alpha2
