### ISSUE TITLE
"Google Drive Authentication Cancelled" Error

### ISSUE THREAD

**Issue by losalim** [OpenArchive/Save-app-android#535]
**Describe the bug**
Went to connect to gdrive, and after selecting it from the server options and trying to log in to google Save shows an error" authentication cancelled" 

**To Reproduce**
see video
Lauren and Alex both had issue

https://github.com/OpenArchive/Save-app-android/assets/145493085/6b846e30-644b-4ff0-9d6e-4edc6ff3504e

**Environment (please complete the following information):**
 - OS version: Android 11 and 12
 - Device: Galaxy s10
 - App Version 0.3.1-alpha1

**Comment by uniqx** [comment]
@losalim  @purvi-ranawat  could you please check if this issue persists in the latest test release (0.3.1-alpha2)?

**Comment by foundscapes** [comment]
@purvi-ranawat please test on the latest release, tysm!

**Comment by ryjen** [comment]
I get a similar issue, but without the error notification.

https://github.com/OpenArchive/Save-app-android/assets/1249111/bc1abb98-2d3b-419c-9e1c-9021715d4f1b

**Comment by uniqx** [comment]
@ryjen your custom debug builds are expected to not work. You'll need to register your debug key with cloud console
