### ISSUE TITLE
"Sign" is misspelt as "Sing" when we click on Google Drive server to connect to google drive

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#540]
**Describe the bug**
On Google Drive Authentication screen, "Sign" is misspelt as "Sing"

1. Go to Save App
2. On New Server screen, click on Google Drive
3. See the text on Google Drive screen

Expected behavior
"Sign " word should be displayed instead of "Sing"  to indicate "Sign in"

Below is the screenshot : 

![image](https://github.com/OpenArchive/Save-app-android/assets/8190141/0473ee49-a2ec-47d4-b105-37c59b2a51f8)

Environment " 
 - OS version: Andriod 14
 - Device: OnePlus Nord CE 3 lite, Samsung Galaxy A13
 - App Version : 0.3.1-alpha2

**Comment by losalim** [comment]
Updated and fixed. version 3.2.0 moto g pure android 10
