### ISSUE TITLE
some 1-star ratings in Google Play are actually positive

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#56]
They are in Arabic and Farsi, could it be a Right to Left discrepancy? Would love thoughts, not too concerned about it, but could see it scaling to be a larger problem when we get more reviews.

Some mysteries: 
- A few 1-star ratings were negative and the 5-star ones I translated were positive, so I'm really unsure what's going on since it would follow that 5 stars would = dissatisfied if my theory were correct.

- Examples of ratings that didn't correspond to the stars (according to g-translate):

A.M. gave 1 star and wrote: Very good and very good
anon. user gave 3 stars and wrote: Excellent
Q.N.  gave 3 stars and wrote: Great

**Comment by foundscapes** [comment]
I will connect with Localization Lab on this issue

**Comment by foundscapes** [comment]
@hiromipaw I wasn't able to find any solution thus far, but hoping we can work to correct this when we have more capacity

**Comment by hiromipaw** [comment]
I am not sure we can correct reviews from the stores. I think we could close this as this isn't an app issue.
