### ISSUE TITLE
Upload percentage shows up instead of loading spinned while uploading images.

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#562]
**Describe the bug**
While uploading images, according to the Figma design, the loading spinner should show up as opposed to the upload percentage that shows up currently. 

**To Reproduce**
1. Click the + sign to upload media
2. Check the "My Media" page
3. The uploading images will show up with uploading percentage.

**Expected behavior**
The expected behaviour is to show a loading spinner as mentioned in the Figma designs.

**Screenshots**

![Screenshot_2024-02-28-22-24-32-39_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/18b0ba2e-45e3-4164-ba77-f2b10deb74a9)

**Environment (please complete the following information):**
OS version: Android v14.0
Device: OnePlus 11R 5G
App Version 0.3.1-alpha2

**Comment by foundscapes** [comment]
I also cannot replicate this @vanichitkara could it be server-specific? Please re-test when uploading to GDrive and Nextcloud. or @uniqx is it another Android 14 issue? 

OS Version: Android 12
Device: Google Pixel 3a
App Version: 0.3.1-alpha2

**Comment by foundscapes** [comment]
from @uniqx This is an Android 14 issue bc of Netcipher - no quick fixes/no new version of this library, tor services needs to be implemented but that's long-paused...

- easiest way forward for us is for us to disable this feature on Android 14+ and implement what's working on older versions to future proof it - solution: build on custom repo of netcipher  directly into Save - make a library vs. directly into Save? create module in android studio is compromise

**Comment by foundscapes** [comment]
fixed
