### ISSUE TITLE
Security settings implementation missing

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#564]
**Describe the bug**
Implementation of the following settings is missing as described in the Figma file: 
- Lock app with Face ID/password
- Allow 3rd party keyboards
- Hide app content when in background

**To Reproduce**
1. Go to Settings
2. Click on General. 

**Expected behavior**
These settings should have been implemented since they are present in the Figma design file.

**Screenshots**

![Screenshot_2024-02-28-22-27-26-85_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/b4856841-d467-4ee0-ad0d-8497326ec31b)

**Environment (please complete the following information):**
OS version: Android v14.0
Device: OnePlus 11R 5G
App Version 0.3.1-alpha2

**Comment by foundscapes** [comment]
@ryjen is there is a reason the Hide app content when in background setting doesn't work / isn't included for/in android?

**Comment by ryjen** [comment]
@foundscapes I need to know more about the expectations for that setting.  (Do you mean like hiding from "overview" or window switching screens?  That is possible, but already implemented with disabling screenshots, should be combined)

**Comment by ryjen** [comment]
@foundscapes assuming blocking 3rd party keyboards is not implemented (dont see it) and should be a new feature ticket as well
