### ISSUE TITLE
Biometrics setup missing

### ISSUE THREAD

**Issue by ryjen** [OpenArchive/Save-app-android#568]
**Describe the bug**
When toggling biometrics on a device without any biometrics setup, the UX is broken.

**Preconditions**
Remove biometrics on the device
Remove the application from the device

**To Reproduce**
1. Install the application and setup a backend
2. Goto preferences and turn on proof mode and biometrics
3. See blank screen, restarts and no Biometrics unlock

**Expected behavior**
The user is taken outside of the app and prompted to set up biometrics for the first time. Then returns with the setting enabled.

**Environment**
 - OS version: >= 23
 - Device: supports biometrics 
 - App Version 3.0.1-alpha2

**Additional context**
See https://developer.android.com/training/sign-in/biometric-auth

and using a finger print with ADB (for automation)

`adb -e emu finger touch 12341234`

**Comment by ryjen** [comment]
I dunno, looking at this again, the credentials store is the alternative to biometrics.
The UX is bad because of restarting the app because of a singleton.
You can probably just add dependency inject instead, and all will be happy.

You might want to include options to check if the user can enroll in biometrics to prefer setting them up.

**Comment by ryjen** [comment]
Hi @vanichitkara ,  this can be tested with an [internal testing build](https://play.google.com/apps/internaltest/4699441400294687809) (version 0.3.2)

**preconditions**
A phone that supports biometric fingerprints

The process is as follows:
1. remove all PINs and Fingerprints from settings on the device
2. go to settings on the Save app
3. go to ProofMode
4. enable biometrics

**expected**

The app will prompt to setup a PIN and Fingerprint (if available)

**Comment by losalim** [comment]
Works for me! Tested on MotoG Pure, Android 10

**Comment by losalim** [comment]
re-opening as I'm not on the newest release. will QA again when i am!

**Comment by losalim** [comment]
updated to newest version and working well.

**Comment by vanichitkara** [comment]
Though I'm late, but yes, it works for me as well on Android 14, app version 0.3.2
