### ISSUE TITLE
Block Third party Keyboards

### ISSUE THREAD

**Issue by ryjen** [OpenArchive/Save-app-android#570]
See #564 , blocking 3rd party keyboards was a part of the settings mockups but not available 

User flow:

1. user configures setting
2. user blocked from entering text without OS keyboard

Data layer:
Storing a preference whether we have checked already, and whether the keyboard is valid

Domain layer:
A use case to block the user from entering data, the application, or both.

Presentation layer:
A dialog for being blocked.
Settings toggle.

Questions:

Why is it a user setting?  Can I just bypass it?

Is there a DAC or Admin user the setting can be used with instead?

**Comment by rapuckett** [comment]
Removed this setting
