### ISSUE TITLE
Arrow pointing towards + sign to add media not implemented

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#579]
**Describe the bug**
Arrow pointing towards + sign for adding media not implemented. 

**To Reproduce**
1. Go to Save app
2. Add folder via Dropbox or any other server
3. The main screen for adding the media doesn't have the arrow as intended in design here: https://www.figma.com/file/Im6CrTczfYYDTLS6LdRTk0/Save-App-2.0?type=design&node-id=432-2617&mode=design&t=CDNdTMHrJPm0oPYv-0#726591270

**Expected behavior**
The arrow animation should be implemented 

**Screenshots**
![1 3 Home - First time user](https://github.com/OpenArchive/Save-app-android/assets/64951124/8ef02897-4217-4da2-a092-bc3ef01c4e3b)

**Environment (please complete the following information):**
 - Android 14
 - OnePLus 11R 5G
 - 0.3.2

**Comment by foundscapes** [comment]
@ryjen please let @rapuckett know what the blocker here is

**Comment by ryjen** [comment]
@foundscapes @rapuckett  it is not blocked.  

other than time, priority and whether iOS can do as well.  I think there are bigger problems to solve.  My understanding is that Apple native SVG might require us to bump minumum supported iOS, or evaluating a third-party lib.

**Comment by foundscapes** [comment]
ty - it's low priority but B said there was a blocker.
