### ISSUE TITLE
EventBus causing LibNearby to Crash

### ISSUE THREAD

**Issue by sabzo** [OpenArchive/Save-app-android#58]
## Issue
Eventbus isn't registered properly, perhaps should be registered during an activity lifecycle event.  

## Reproduce by
1. Click floating action button (represented by a "plus" sign).
2. Click "Nearby Receive" button
3. Click "cancel" on bottom right of screen, or "paired devices only". 

This will try to unregister EventBus which may have not been registered if bluetooth isn't turned on. 
If EventBus is registered even on the constructor of _BluetoothReceiver_ this will still fail.

## Fix 
Register Eventbus in an Activity.
Or substitute Libnearby library with a similar library.

## Error 
```
Process: net.opendasharchive.openarchive.release, PID: 22535  java.lang.NoClassDefFoundError: Failed resolution of: Lde/greenrobot/event/EventBus; at info.guardianproject.nearby.bluetooth.BluetoothReceiver.start(BluetoothReceiver.java:67)
     at net.opendasharchive.openarchive.nearby.NearbyActivity.startClient(NearbyActivity.java:359)
 at net.opendasharchive.openarchive.nearby.NearbyActivity.onCreate(NearbyActivity.java:161)
```

**Comment by n8fr8** [comment]
Thanks for tracking this down. I think in my work to update and switch to Ayanda, I've gotten stuck in the middle with this strange issue. Let's talk about it in realtime.

**Comment by n8fr8** [comment]
I think the goal is to remove LibNearbyShare... I just had some lingering classes in there.

**Comment by n8fr8** [comment]
Just pushed to master branch w/o dependency on LibNearbyShare and eventbus

**Comment by sabzo** [comment]
Awesome. The latest push you made has fixed the eventbus crash error. Now we're ready to being calling ayanda functionality. I'm gonna update Ayanda README to display the latest use of the library, or you can also check out the example.

**Comment by n8fr8** [comment]
Xclnt!
