### ISSUE TITLE
Implement new Internet Archive setup

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#580]
Implement new screen designs for Internet Archive login.

Internet Archive login works with two steps:
![0 5 Internet Archive - Log In](https://github.com/OpenArchive/Save-app-android/assets/64951124/c0794e61-e373-4115-9d45-faa9bc72ffdf)
![0 5a Internet Archive - Keys Aquired](https://github.com/OpenArchive/Save-app-android/assets/64951124/ecb3052c-21db-4eb2-a9b0-d369fd358906)
![0 5b Internet Archive - Success](https://github.com/OpenArchive/Save-app-android/assets/64951124/8bd3bcd5-7a24-4858-b298-e27127cd282a)

Button typography:
```
styleName: 16pt;
font-family: Montserrat;
font-size: 16px;
font-weight: 600;
line-height: 20px;
letter-spacing: 0.01em;
text-align: left;
```

Figma: https://www.figma.com/file/Im6CrTczfYYDTLS6LdRTk0/Save-App-2.0?type=design&node-id=421-1929&mode=design&t=VT64Hlm9YhdKUrQL-4

**Comment by ryjen** [comment]
note: check to see if the IA API has a link to the media folders once uploaded (like it used to)

then have share options (see old version of android app in repository)

**Comment by ryjen** [comment]
Hi @vanichitkara :  I made a new beta build last night that should be available to testers sometime today

**Comment by vanichitkara** [comment]
Hi @ryjen @foundscapes, I checked the flows, and they are working as expected!
Environment (please complete the following information):
OS version: Android 14
Device: OnePlus 11R 5G
App Version 0.3.2

**Comment by ryjen** [comment]
merged into development branch, when the release is in production, close this ticket

**Comment by foundscapes** [comment]
we are still having the issue with duplicate (sometimes many many dupes) uploads when uploading just one file - it's repeatable @vanichitkara can you login to the IA to check to see how many copies are uploading from one image file and post a screenshot here? ty!

**Comment by vanichitkara** [comment]
For images IMG20240305173422.jpg and IMG20240305173412.jpg, there are a total of 6 copies. The rest of the images have 3-4 copies each. @foundscapes 
![Screenshot_2024-04-07-16-01-12-06_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/OpenArchive/Save-app-android/assets/64951124/69373b45-181e-484c-a494-69d468c0febf)
![Screenshot_2024-04-07-16-01-21-61_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/OpenArchive/Save-app-android/assets/64951124/8934ca7f-f0be-40a5-b7f6-e3facb9ebece)

**Comment by rapuckett** [comment]
DUP of https://github.com/OpenArchive/Save-app-ios/issues/279
