### ISSUE TITLE
The Next and Done buttons in the Android app have white font color instead of black as suggested in Figma design

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#581]
**Describe the bug**
The Next and Done buttons in the Android app have a white font colour instead of black, as suggested in the Figma design. This is for every screen in the app. 

**To Reproduce**
1. Go to the "Connect to a server" screen
2. Add a new server
3. The login screen will have the Next button
4. Logging in to the server will get us to the Done button next

**Expected behaviour**
The Next and Done button should have the font colour black

**Screenshots**
![Screenshot_2024-03-12-22-02-36-95_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/c2f9afc2-8c1a-4b31-85b7-df944a7c2069)
![Screenshot_2024-03-12-22-02-48-54_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/e7df769e-5e7e-4b22-9d44-48356b4b71f9)

**Environment (please complete the following information):**
 - Android 14
 - OnePlus 11R 5G
 - version 0.3.2

**Comment by ryjen** [comment]
This is an accessibility issue reported on Google Play as well. 

A fix should look at all occurrences within the application.

Assuming dark mode and light mode won't matter, the text should always be black.

The plus button is a unique case because it is in the footer - but still applies

**Comment by purvi-ranawat** [comment]
@foundscapes / @upulw2020 : This is working fine
