### ISSUE TITLE
Update language for adding new folder for first time user

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#582]
**Describe the bug**
The current language needs to be updated as per the Figma design

**Expected behavior**
The language should be as suggested here: 
![1 0 Home - First time user no project](https://github.com/OpenArchive/Save-app-android/assets/64951124/a907362b-3c70-49b9-85da-d655312ee9eb)

**Comment by ryjen** [comment]
is blocked by #583

**Comment by foundscapes** [comment]
@ryjen please let @rapuckett know why this is blocked, ty!

**Comment by ryjen** [comment]
Seemed logical the pop up needed to be implemented before changing the language

misunderstood the pop up is  already implemented

Not blocked

Thanks @rapuckett

**Comment by foundscapes** [comment]
@vanichitkara please re-test this to see if it's been fixed, tysm!

**Comment by upulw2020** [comment]
@foundscapes Implemented. Language is good enough. Closing this issue.
![image](https://github.com/user-attachments/assets/28dac5e1-9a08-4315-ab94-c3927208187e)
