### ISSUE TITLE
Need to have the pop-up to add new folder right after connecting to new server

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#583]
**Describe the bug**
The add a folder pop-up should appear after users click "Done" on the "You've successfully connected to a server" screen (right now, they are taken to the home screen first). 

**Expected behaviour**
It needs to be changed such that the "To get started, please add a folder" pop-up shows immediately after you connect to a server", and then when they click to add a folder, they are brought to the add a folder pop-up.

**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://www.figma.com/file/Im6CrTczfYYDTLS6LdRTk0/Save-App-2.0?node-id=4%3A24&mode=dev#726591675)

**Comment by rapuckett** [comment]
Dup of #281
