### ISSUE TITLE
The folder icon in Android has teal outlined folder instead of teal filled folder icon as suggested in the Figma design

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#584]
**Describe the bug**
Currently, the folder icon in Android has a teal-outlined icon, which is different from the Figma design. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a new server
2. Add some folder 
3. Click on the top right hamburger menu
4. You'll see the list of folders with the teal-outlined folder icon

**Exbehaviourehavior**
The folder icon should be a teal-filled, as the Figma design suggests.

**Screenshots**
![Screenshot_2024-03-10-16-47-22-72_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/3f689ffd-5773-42f1-ac33-a80059fcd54d)

**Environment (please complete the following information):**
 - OS version: Android 14
 - Device: OnePlus 11R 5G
 - App Version 0.3.2

**Comment by ryjen** [comment]
already doing a refactor on the whole side panel menu layout.  Please refer to it when it is available.

**Comment by foundscapes** [comment]
@ryjen was this done? can we close?

**Comment by ryjen** [comment]
@foundscapes Negative
