### ISSUE TITLE
Floating buttons are inactive in the latest release.

### ISSUE THREAD

**Issue by organik1** [OpenArchive/Save-app-android#59]
Only one out of the five floating action button works, the rest are inactive in the latest release.

### How to reproduce.

* Launch the app and grant the necessary permissions.
(Even after granting, check the app's info to confirm that permissions have been granted, in my case I noticed and had to grant them manually)

* Complete the slides to arrive at the homepage.

* While on the homepage, locate a big , blue, floating (+) action button at the bottom right corner.

* Click on this big button to reveal other labelled sub-action buttons.

* The issue tend to exist with the second button from below and the rest upward.
While the first button from below work as expected.

* Now click on the sub-action buttons to test their functions.

App version: V0.0.17 beta 4

Operating system: Android v6.0 marshmallow

**Comment by n8fr8** [comment]
Fixed in beta 5:
https://github.com/OpenArchive/openarchive-android/releases/tag/0.0.17-beta-5
