### ISSUE TITLE
View additonal server pop-up not implemented for first time users.

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#590]
**Describe the bug**
Currently, first-time users don't have a pop-up suggesting where to view additional server information. This feature was in the Figma design files but not implemented. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the hamburger menu on the top right of the main screen.
2. The expected pop-up should come, but it doesn't. We only see the current server and the associated folders. 

**Expected behaviour**
The expected behaviour is to have this pop-up as suggested in the Figma design file.
![Home - First time user](https://github.com/OpenArchive/Save-app-android/assets/64951124/4b3dd992-9378-4f66-a22f-7fccf631bebe)

**Environment (please complete the following information):**
 - OS version: Android 14
 - Device: OnePlus 11R 5G
 - App Version 0.3.2

**Comment by foundscapes** [comment]
@rapuckett I believe Rachel was going to put language in that gray box, hold off until that's done @ceylana please share insights when you have them.

**Comment by ceylana** [comment]
Rachel will give an update on it tomorrow Natalie!

**Comment by foundscapes** [comment]
This was fixed by adding "Servers" in the top level nav of hamburger
