### ISSUE TITLE
Proofmode: Add location and network info to proof

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/Save-app-android#593]
Similar to what I did on iOS, we need to add support for GPS location and GSM network info, when the user adds a fresh image.

On iOS, though, the library used to pick media from the gallery also contains an inline camera app. (Which is actually provided by iOS itself. A very spec'd-down version of the camera app, unfortunately.)

So, what we do here is switch on the extra proof metadata, when the asset is younger than 5 minutes.

For Android, I suggest an additional option when long-pressing the "plus/add" button, where the user is sent to the camera app which then returns all freshly created assets.

This freshly created assets then should be ProofMode'd with additional location and GSM info.

These are the necessary changes for iOS:

https://github.com/OpenArchive/Save-app-ios/commit/4c32671a059c5e78d5ce668bd21bf07b9c1ef061

Please let me know, if you need more advice/info!

**Comment by foundscapes** [comment]
@rapuckett we need to first enable in-app capture in Save before this can be properly implemented
