### ISSUE TITLE
New Hamburger implementation for servers

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#594]
Implementation of a new hamburger menu for the servers.

The new design:
![1 4c Home - Media - Private Server signed in](https://github.com/OpenArchive/Save-app-android/assets/64951124/37f50413-398d-4b84-badf-86479a57cfe0)
![1 4d Home - Menu](https://github.com/OpenArchive/Save-app-android/assets/64951124/9ba748c8-1f1b-4287-8ac7-ebd3557c11f6)

**Comment by rapuckett** [comment]
@vanichitkara  Should "Add Folder" have the same UX as "Add Server"? I like how the action is close to the list of existing items.

**Comment by rapuckett** [comment]
Will be released in 0.6.0 on 4/9/2024
