### ISSUE TITLE
(Dropbox) : On selecting dropbox as the server, it should present us with the option with which account it should connect

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#595]
After installing the Save App, when we select Dropbox as the server to connect, it directly logins into the default account when we click on Authorize. It presents us with the Sign out option on top right side on permission screen and then we can select another account. Instead, when we click on drop box server and click on Authorize, instead of directly login into the default account, it should present us with the option to select the account to login or add another account.

**Comment by foundscapes** [comment]
@rapuckett to close once removing DropBox

**Comment by purvi-ranawat** [comment]
@rapuckett / @foundscapes : Now Dropbox is not available as the server for selection.

Build : 0.7.2
Device : One Note plus Nord CE lite
OS Version : Android 13

**Comment by rapuckett** [comment]
Dropbox has been officially removed from the app

**Comment by upulw2020** [comment]
@foundscapes @purvi-ranawat Dropbox removed in public app v 0.7.2. Closing this.
