### ISSUE TITLE
Upload Service: Internet Archive uploads multiple copies

### ISSUE THREAD

**Issue by ryjen** [OpenArchive/Save-app-android#599]
**Describe the bug**
When uploading a file to internet archive, if you confirm the upload by visiting your https://archive.org account, duplicate files are uploaded.

**To Reproduce**
1. Log into or setup an Internet Archive backend
2. Click on the '+' and/or create a folder
3. Select a single image to upload
4. upload the file
5. wait 10-30 minutes for the internet archive processes to complete archiving
6. log into your internet archive account and go to 'my uploads'
7. See error

**Expected behavior**
A single copy of the image, related metadata, and proof

**Actual behaviour**

multiple copies

**Screenshots**
![Screenshot 2024-03-20 at 5 35 26 PM](https://github.com/OpenArchive/Save-app-android/assets/1249111/0d610d7e-8350-4e19-9d42-bfef48f1abe2)

**Environment (please complete the following information):**
 - OS version: Android
 - Device:Any
 - App Version: build from 'ia-refactor'

**Additional context**

The problem could be two things:

1. an error or lifecycle issues with the upload service, causing multiple uploads of the same file
2. the identifier for the upload changes and IA treats as separate files

**Comment by vanichitkara** [comment]
I'm still getting the same issue as described above. @ryjen @foundscapes 
![Screenshot_2024-03-27-23-06-16-12_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/OpenArchive/Save-app-android/assets/64951124/21ce8168-34d1-4404-a8c7-5934fdb8e975)

OS: Android 14
Device: OnePlus 11R
version: 0.3.3

**Comment by ryjen** [comment]
@vanichitkara  Can you confirm those are not dups from testing with the same image?  If you click into them do they have the same identifier?

![Screenshot 2024-03-27 at 10 42 56 AM](https://github.com/OpenArchive/Save-app-android/assets/1249111/04e5d8e0-7196-49a1-864f-de9269ea06ef)

**Comment by vanichitkara** [comment]
@ryjen They have different identifiers. These are the following identifiers for the multiple copies of the same image:
`IMG20240309104945-jpg-rtboz`
`IMG20240309104945-jpg-lyek`
`IMG20240309104945-jpg-1uy2`
 `IMG20240309104945-jpg-npcl`
 
 The picture with this image name was uploaded 4 times, and this associated file also came up four times. The picture that was intended to upload also has 4 different identifiers associated with each of them.

**Comment by ryjen** [comment]
@vanichitkara Do you know if any errors occured to achieve the duplicates?

I suspect the uploader is re-running after an error and creating a new identifier now.

It is still better than my previous testing where there was 10+

**Comment by vanichitkara** [comment]
@ryjen I'll need to test again to see if upload retry is the culprit of these multiple uploads. Give me some time, I'll get back to you tomorrow for this.

**Comment by vanichitkara** [comment]
@ryjen I tested if the duplicates are coming only for errors while uploading or not. According to my tests, the duplicates came in regardless of whether the uploads had to be retried or not. 4 of my 5 images went in without retry and 5th one had to be retried, but all these images have their duplicates created.

**Comment by foundscapes** [comment]
@vanichitkara this is working for me (no dupes), can you retest this weekend and close if it's fixed for you? ty!

**Comment by vanichitkara** [comment]
@foundscapes, I still see duplicate images after uploading. I uploaded these pictures today to test the teal % and spinner. 
Phone: OnePlus 11R
OS: Android 14
Save version: 0.4.0

![Screenshot_2024-04-07-16-51-40-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/OpenArchive/Save-app-android/assets/64951124/bcddfd7f-461c-423f-ad72-23271956cbbf)

**Comment by ryjen** [comment]
Keep in mind, yes, it is still possible to upload the same picture more than once if you intended to.

Based on my testing, the picture evidence is still a vast improvement from the background processes uploading unintentionally (it got quite spammy)

@rapuckett 

You might perhaps need to examine the requirements for IA needing a unique filename with randomness generated

a) As to whether it was to bypass errors

Or b) because it has something to do with needing an identifier for the API

In the likely case of b) you may need to design a better folder structure as an identifier or some other method instead of randomness to *truly* stop intentional and unintentional duplicates.

**Comment by foundscapes** [comment]
I have not had this issue in over a month
