### ISSUE TITLE
Size of app?

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#60]
It is now 5.7MB, just want to check in about size.

**Comment by n8fr8** [comment]
Is there a size target? In general, the goal is to be under 10MB for a "light" app these days. As we add more support for different back-end services, as well as more nearby code, that will increase the size of the app. However, we can also do more optimization of the release to remove unused code from third-party libraries.

In summary, 5.7MB is still small, and I think a range of 5-10MB is reasonable.

**Comment by foundscapes** [comment]
Nope, just wondering what you thought about it, thanks for clarifying.
