### ISSUE TITLE
"eye" icon in password field is wrong

### ISSUE THREAD

**Issue by rapuckett** [OpenArchive/Save-app-android#605]
**Describe the bug**
When the password is visible, the eye icon indicates that the password is NOT visible, and vice-versa.

**To Reproduce**
Attempt to create a new server connection (eg: Internet Archive)
Type some characters into the password field
Tap the eye icon and observe results

**Comment by foundscapes** [comment]
@purvi-ranawat  please test

**Comment by purvi-ranawat** [comment]
@foundscapes : This is working fine. Now on clicking on 'eye' icon shows the password and the cross on 'eye' icon hides the password.

Below are the details : 

OS Version : Android 14
Device : OnePlus Nord 3 CE lite / Samsung Galaxy A13
Build Version : 0.7.2

**Comment by foundscapes** [comment]
@purvi-ranawat please double-check this is still working and close, thanks!

**Comment by purvi-ranawat** [comment]
@foundscapes : Tested on publicly available version : 0.7.2 and it is working fine.

OS Version : Android 14
Device : OnePlus Nord 3 CE lite / Samsung Galaxy A13
Build Version : 0.7.2
