### ISSUE TITLE
Encrypt audio/video on device?

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#61]

**Comment by n8fr8** [comment]
That would add a lot of complexity and size to the app. OpenArchive is not CameraV... i.e. it is meant to preserve media people are capturing on the device through whatever means, and not as a super secret camera crypto app.

**Comment by foundscapes** [comment]
I know, but some people are asking about it and I wanted to check in about potentially merging the two in a future version (optional)...to discuss later!
