### ISSUE TITLE
Browse exitsing folders not working for Dropbox

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#610]
**Describe the bug**
When trying to browse existing folders for Dropbox, the folders don't show up

**To Reproduce**
1. Select Dropbox Servers
2. Go to hamburger menu and click on Add Folder
3. Click on Browse Existing Folders - No folders show up for Android app whereas they do for iOS app

**Expected behavior**
The existing folders should show up for Android as well.

**Screenshots**
iOS App Screenshot
![IMG_0004](https://github.com/OpenArchive/Save-app-android/assets/64951124/224761e1-c1da-451e-8c53-04921ad8ee52)
Android app screenshot
![Screenshot_2024-05-26-20-58-13-01_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/3309130a-2ce1-4510-9335-2f73768b7096)

**Environment (please complete the following information):**
 - OS version: Android 14
 - Device: OnePlus 11R
 - App Version 0.7.2

**Comment by foundscapes** [comment]
@rapuckett will close once he removes DB from the app soon

**Comment by upulw2020** [comment]
@foundscapes @purvi-ranawat Dropbox removed in public app v 0.7.2. Closing this.
