### ISSUE TITLE
Dropbox Setting UI is not correct

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#613]
**Describe the bug**
The Dropbox settings UI is not how it should be and is more likely the private server settings UI. Also, the logo for Dropbox is not right.

**To Reproduce**
1. Go to Settings
2. Click on Dropbox

**Expected behavior**
The UI should be like how it is for iOS

**Screenshots**
![Screenshot_2024-05-26-21-02-33-09_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/2056b19f-66ca-4640-ac2f-55f9684a6a2c)
![Screenshot_2024-05-26-21-02-38-41_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/7052dfcb-0740-4b84-8d98-e616f4aad372)
![IMG_0010](https://github.com/OpenArchive/Save-app-android/assets/64951124/78044ba0-81f3-4343-9a95-e8c97b55eeaf)

**Environment (please complete the following information):**
 - OS version: Android 14
 - Device: OnePlus 11R
 - App Version: 0.7.2

**Comment by foundscapes** [comment]
@rapuckett will close once he removes DB from the app soon

**Comment by upulw2020** [comment]
@foundscapes @purvi-ranawat Dropbox removed in public app v 0.7.2. Closing this.
