### ISSUE TITLE
Toggle Bluetooth  option off and on within the app setting and the receive nearby option becomes inactive.

### ISSUE THREAD

**Issue by organik1** [OpenArchive/Save-app-android#62]
#### Actual behavior

Clicking the receive nearby icon does nothing, after the bluetooth option under the app settings had been toggled off and on.

#### How to reproduce

1. Launch Openarchive

2. Click on the floating action button to reveal the receive nearby icon.

3. Click on the icon to observe its behavior.
(It will prompt you to switch bluetooth on and then it will begin a search for nearby hosts)

4. Press the back key on your device to dismiss the activity 

5.  Access the settings page, from the three dot menu located at the top right corner of the homepage.

6. Locate the bluetooth option toggle and turn it Off and then On again

7. Press the back button once to arrive at the home page and repeat steps 2 and 3.

* OpenArchive version: V0.0.17 beta 5

* Operating system:  Android v6.0 marshmallow

     * Chipset: Spread

* Device: Itel p12

**Comment by elric-wamugu** [comment]
The nearby/Bluetooth feature seems deprecated from later versions of the OA app
