### ISSUE TITLE
Taking a photo with PicsArt Camera break OpenArchive

### ISSUE THREAD

**Issue by organik1** [OpenArchive/Save-app-android#63]
Hello dev.

I like taking pictures with PicsArt camera due to the fact that it produces better output than my stock camera does.

I'm constantly experiencing a crash with Openarchive v0.017 beta 5, each time I choose PicsArt camera as a medium to take photos.

Device: Android v6.0 (spread chipset)

**Comment by n8fr8** [comment]
Do you mean the "PicsArt Photo Studio" app?

**Comment by n8fr8** [comment]
With the latest code, it no longer crashes, but we can't get it to return the actual URI path to the photo. For now, you'll have to "IMPORT MEDIA" instead, or share to OpenArchive from PicsArt.
