### ISSUE TITLE
App not automatically updating on phones after new release

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#64]
From Google Play and maybe fdroid?

**Comment by n8fr8** [comment]
That isn't something we can control.

**Comment by foundscapes** [comment]
Most apps prompt users to install new versions, this needs to happen.

**Comment by n8fr8** [comment]
Not sure I agree about "most apps". App upgrades and notifications of updates being available are handled by Google Play and F-Droid. You can add extra functionality in an app to ping github or a website to check an update file, but that is extra network traffic to a centralized host that could be considered "tracking". Let's discuss!

**Comment by foundscapes** [comment]
How does Signal do it?

**Comment by n8fr8** [comment]
We know how to do it technically if we want to, I just want to make it clear that in app update checking is a new feature, and not just a default option. It also requires accessing an "updates" file hosted somewhere (OA website, github, etc) on a regular basis (once a day), to see if it has changes, and to read in the information about the new release.

Signal likely does it using one of the existing open source libraries or patterns for doing this kind of thing.

This is the library we usually use for this: https://github.com/javiersantos/AppUpdater

**Comment by foundscapes** [comment]
I think this is important given that anyone who has the released version from play may be very confused about how to use it and never go back to the app if UI isn't updated.

**Comment by foundscapes** [comment]
@n8fr8 can we implement this?

**Comment by foundscapes** [comment]
@ozgegn would you be able to do this?

**Comment by ozgegn** [comment]
Hi @foundscapes ,
We can implement this library for redirection to Play Store or fDroid. But until user gets in to application, we can't force to update.

**Comment by foundscapes** [comment]
It'd be great to implement this for ios as well, @tladesignz

**Comment by tladesignz** [comment]
> It'd be great to implement this for ios as well, @tladesignz

No way. This is a ridiculous anti-feature for something which is provided by the OS in a fully automated fashion for an app which wasn't updated in over a year.

**Comment by foundscapes** [comment]
I'm sorry I don't understand @tladesignz - the idea is to automatically push updates for both apps so everyone has the most updated version without having to remember to do it (no one does). 
We will have a number of new updates for android in the next few months and we will need to make those metadata fixes for ios as well plus a few other updates, so why would it be difficult/problematic?

**Comment by tladesignz** [comment]
The OS pushes updates of apps automatically. The OS provides all infrastructure to handle this. It doesn't make sense to implement this and on top of it all it is a privacy leak. **As already explained by Nate**.

**Comment by foundscapes** [comment]
So it sounds like the OS will automatically update and we don't have to worry about this? My priority is to make sure people have our most updated version without having to go look for it. If that is the case here, then we can close this issue, am I right with this @tladesignz ? Thank you!

**Comment by foundscapes** [comment]
Ok. I just like that signal (among other apps) asks to update whenever there are updates, but it sounds like that is not as secure as we'd want it to be, which surprises me. I'll defer to you all.

**Comment by n8fr8** [comment]
Signal runs their own servers, that their client connects to, and so it can push update notifications. 

Save does not run its own servers.

**Comment by tladesignz** [comment]
They do this, because they have a huge ecosystem of servers and different client apps which all need to work together. Annoying the user about updates helps them in keeping the different versions in the field closer together so they can move forward more quickly and don't spend too much time on legacy support. 

They also have the situation that they have client apps, where the OS doesn't take care of automatically updating.

All of this doesn't apply to us.

**Comment by foundscapes** [comment]
Thanks for clarifying @tladesignz and @n8fr8. Closing
