### ISSUE TITLE
Bug with shared PHOTOs

### ISSUE THREAD

**Issue by organik1** [OpenArchive/Save-app-android#65]
Hello dev.

Photos which are share to OpenArchive through other apps appear to be blank. 

I have tried several mediums including stock FileManager and Gallery but It seems to be that the sharing process has some bad effect on pictures, whereas other media files are not affected.

App version: V0.0.17beta 5

Device: Android v6.0

**Comment by n8fr8** [comment]
Related to this issue: https://github.com/commons-app/apps-android-commons/issues/173
