### ISSUE TITLE
Confusion about everything is public

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#68]
Through testing with community there is confusion about media being public or private. Need to add a clear statement "everything you upload is public"

**Comment by n8fr8** [comment]
This was a comment from Mexico users. They thought by turning off all creative commons licensing features it would mean it would not be shared publicly. 

These are for users who installed the app without reading the website (hablas espanol solamente!)

**Comment by foundscapes** [comment]
Gotcha! Hmm, I guess we need a disclaimer?

Or perhaps it's a language issue? The app still needs to be fully translated into Spanish, which should happen very soon, right?

**Comment by n8fr8** [comment]
Yes, for the next release we will have it all in Spanish.
