### ISSUE TITLE
Request from potential partner - auto-login for org. account at IA

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#72]
Could we release a version of the App. that has the login built in to the IA so that everyone from one org can just auto-upload to the IA and then access it online through the same account?

**Comment by n8fr8** [comment]
It is tricky do to do this for the IA, and in general, sharing a single account across multiple users, without being able to distinguish who is who, is not a great approach.

That said, this may be possible through use of an invite link or QR code to auto-provision the app. This could be useful for many organizations and back end configurations going forward.

**Comment by foundscapes** [comment]
@n8fr8 Let's revisit QR codes to auto-provision unique users.

**Comment by n8fr8** [comment]
Nextcloud now supports QR codes for logging in, as part of the "app password" feature with 2FA.

1.     /settings/user/security
2.     Devices & sessions
3.     in the input box left of “Create new app password” put “mobile” or something related
4.     Create new app password
5.     Show QR code for mobile apps

We should add "scan QR code" as an option when adding a new space.

**Comment by n8fr8** [comment]
nc://login/ is the base format.

**Comment by n8fr8** [comment]
Now if you scan the QR code provided by NextCloud, it will automatically setup the account, filling in username, password and server.

This is also the current solution to use generated "app passwords" for when 2FA is enabled.

**Comment by foundscapes** [comment]
Awesome @n8fr8!

@roseregina and I will test asap

Let's add "scan QR code" as an option when adding a new space (nextcloud and goodcloud only, right?)

**Comment by n8fr8** [comment]
It works with any webdav server that supports the "nc://login/" format.

I will create "scan QR code" as a new feature ticket, since it requires a good amount of work to handle loading a separate QR code app, etc.

**Comment by n8fr8** [comment]
(Closed this since sharing a single "built-in" IA account across all users is insecure and not viable)
