### ISSUE TITLE
Change archive.org account

### ISSUE THREAD

**Issue by ingfabby** [OpenArchive/Save-app-android#74]
Currently the app does not allow the user to change accounts, I deleted my account on Archive.org, I open the app and I didn't get any message asking me to register or sign into Archive.org, I tried to upload a file and I got a message saying "Error during upload", but nothing telling me that I needed an account in Archive.org.

**Comment by n8fr8** [comment]
https://github.com/OpenArchive/openarchive-android/releases/tag/0.2.1-beta-2

**Comment by n8fr8** [comment]
@purvi-ranawat please test archive.org account support, and multi-account support account

You can get an archive account at https://archive.org

**Comment by purvi-ranawat** [comment]
@n8fr8 : This is still not working correctly. After the successful registration on Save app for Internet Archive, when I deleted the account on archive.org and then access the Save app again, it does not give me the message stating to register or sign - in on archive. org. Also, when I try to upload the media after deleting the account on archive.org, it did not give me any error message. Instead it shows that the media has been uploaded successfully.

**Comment by n8fr8** [comment]
Ah interesting. I didn't test with deleting my account on Archive.org. Also, strange that the success is showing as successful. Will debug! Fortunately, this is an edge case, but something to work on for sure in the next sprint.

**Comment by n8fr8** [comment]
I think for now, this is fixed. If the user deletes their account on Archive.org website, that is out of scope for us. As long as the SAVE app itself allows you to remove an account, and added a new one, or add multiple accounts, then we are done.

**Comment by purvi-ranawat** [comment]
@n8fr8  / @foundscapes : On Samsung A70 - Android 10 version, this is working fine. But on MI - Note 4 - Android 7, when I click on Acquire Keys for trying to create internet archive account, the app hangs and it says that it is not responding

**Comment by purvi-ranawat** [comment]
@foundscapes This is working fine on Samung A70, Android 11.
