### ISSUE TITLE
Back button takes back to homepage, not to most recent page

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#77]
Tapping the back button on my device always brings me to the ‘home’/’sign in’ screen. Not back to where I just was... I can’t navigate through the app easily.

Tiff tested
Moto G play
OS: Android 6.0.1 
App version: beta-4

**Comment by foundscapes** [comment]
@n8fr8 this may no longer be an issue

**Comment by foundscapes** [comment]
@ozgegn would you be able to test to make sure this is resolved and then close?

**Comment by purvi-ranawat** [comment]
@foundscapes Unable to reproduce the issue on Samsung Galaxy a70 Android 11

**Comment by foundscapes** [comment]
@purvi-ranawat great, can you close these issues when they're fixed?

**Comment by purvi-ranawat** [comment]
@foundscapes @n8fr8  The issue seems to be fixed now, can close the issue.
