### ISSUE TITLE
need message during delay when signing up for a virtual library card

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#78]
Add ‘processing’ feedback while user is ‘waiting’ for their virtual card to be created.

Tiff tested
Moto G play
OS: Android 6.0.1 
App version: beta-4

**Comment by foundscapes** [comment]
@ozgegn would you be able to test to make sure this is resolved and then close?

**Comment by n8fr8** [comment]
I don't think we have sign-up for virtual IA library card anymore, do we? At least, that isn't an official feature of Save. Users are expected to have an existing account for the cloud services they are adding.

**Comment by n8fr8** [comment]
Yeah, just checking the app now, and this isn't there anymore. For Internet Archive, we just tell them "you need an account", but don't provide a link to get one. Closing this since it isn't relevant anymore.
