### ISSUE TITLE
Hangs for over 3 mins and counting when trying to upload image

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#79]
Hangs when uploading via Import image or video from gallery -  Reproduced 3x
Do not have an audio file to upload/test from gallery, forthcoming...

NOTE: does not hang when using it for photo taken w/in app., uploading video w/in app, uploading audio w/in app.

Natalie testing on:
Moto G
OS: Android 5.1
App version: 0.017-beta-5

**Comment by n8fr8** [comment]
Does it hang when you import the file, or when you are uploading?

**Comment by foundscapes** [comment]
When I am uploading directly. Import is fine. Problem persists with beta-7 version too.

**Comment by foundscapes** [comment]
![screenshot_2018-06-15-16-58-50](https://user-images.githubusercontent.com/2231711/41493614-d41e5f5e-70bd-11e8-8d3d-a6eab7173974.png)

**Comment by foundscapes** [comment]
It worked right after, so could not reproduce in beta-7 yet.

**Comment by n8fr8** [comment]
The upload is in the background, and could take awhile depending on your network situation.

"Hang" means the user interface is frozen. Is that what is happening?

**Comment by foundscapes** [comment]
Yes, it froze and never uploaded.
