### ISSUE TITLE
Upload link sends you to error screen

### ISSUE THREAD

**Issue by ingfabby** [OpenArchive/Save-app-android#81]
It takes a few minutes after the link is displayed to work. Before that it takes you to screen that says " the item cannot be found"

Fabby Testing on Galaxy J7 Perx
Android 7.0
App version:  0.0.17-beta-7

![screenshot_20180615-155929](https://user-images.githubusercontent.com/28932186/41492680-7d92f544-70b5-11e8-9a58-7d744aa5d1e3.png)

**Comment by n8fr8** [comment]
This is more a UX issue, but yes, annoying. We don't know when the content on archive.org is "ready"

**Comment by foundscapes** [comment]
@ozgegn would you be able to test to make sure this is resolved and then close?

**Comment by ozgegn** [comment]
Hi @foundscapes ,
What is the expected behavior to see if it's resolved ?

**Comment by foundscapes** [comment]
May be out of scope, will try to reproduce and let you know @ozgegn!

**Comment by elric-wamugu** [comment]
Failed to reproduce this on a Galaxy Nexus with Android 7.
Uploading to InternetArchive is working on Android 11 with the Save App version `0.2.3-BETA-3`

**Comment by purvi-ranawat** [comment]
@n8fr8 / @foundscapes : This is working fine on Samsung A70 - Android 11. We can close the issue
