### ISSUE TITLE
Deleted items stay listed in the account

### ISSUE THREAD

**Issue by ingfabby** [OpenArchive/Save-app-android#82]
Fabby Testing on Galaxy J7 Perx
Android 7.0
App version:  0.0.17-beta-7
When an item is deleted from the app and the Archive library the name of the file stays listed in the Archive account, even when  it can not longer be open.

**Comment by foundscapes** [comment]
This is an archive.org setting we can't do anything about as far as I know.

**Comment by n8fr8** [comment]
Yes, we delete the media files, but we can't remove the listing.
