### ISSUE TITLE
Video recorder option fails to upload the file

### ISSUE THREAD

**Issue by ingfabby** [OpenArchive/Save-app-android#84]
Fabby Testing on Galaxy J7 Perx
Android 7.0
App version: 0.0.17-beta-7

When a video is recorded using the video icon in the app the upload fails

**Comment by n8fr8** [comment]
Is the video imported into the app otherwise? Everything else works?

**Comment by ingfabby** [comment]
The video is imported to the app, nearby did not work on my devices

**Comment by n8fr8** [comment]
no longer supported
