### ISSUE TITLE
Thumbnails, media disappear when Google Photos remove

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#89]
When you clean/remove data using Google Photos, the thumbnail and photos disappear from OpenArchive. We need to cache a copy of the thumbnail in the OA app, and possibly the media as well.

**Comment by roseregina** [comment]
Save 0.2.2-beta-7

Galaxy S7
MotoG

Good Cloud server


@n8fr8 were you describing: 
1. Open a project folder tab on Good Cloud server
2. Successfully add images, including verifying that the photo was visible in the project 
3. Switch to Google Photos app
4. In Google Photo (Galaxy S7)/ Gallery (MotoG), delete a photo that you had previously added in step 2
5. Return to _**Save**_ app and check the thumbnail in the project view
6. **Expected Result** Thumbnail is unchanged (still visible)
6. **Your Result** Thumbnail is not visible, presenting either as a broken image file or as just not present content

My step 6 results matched the expected results described above. I even force quit through Settings > Apps checked and the thumbnail still displayed properly

If so, then this issue can be closed. 

If not, please provide more details.

**Comment by foundscapes** [comment]
Tested on Pixel 3a, expected result of thumbnail remained after removing video
