### ISSUE TITLE
Error uploading image not detected

### ISSUE THREAD

**Issue by mrtndwrd** [OpenArchive/Save-app-android#90]
Here's the feedback that you asked for in the OTF-active mailing list.

## Description

I was testing the application (my first use of the application and archive.org). I was trying to upload an image, but I'm in a train, so the internet connection is not really stable and the upload failed. The app did not detect that and kept showing "Uploading image"

Edit: I'm using the 0.0.18-alpha-1 version: https://github.com/OpenArchive/openarchive-android/releases/download/0.0.18-alpha-1/OpenArchive-0.0.18-alpha-1-releaseflavor-release.apk

## Steps to reproduce

1. Make a photo
1. Upload the image with the OA Android app
2. Disconnect your internet

## Expected behaviour

The app shows a message saying "upload failed" and preferably also a retry-button.

## Actual behaviour

App keeps saying "Uploading image". To retry you have to click back, click your image again and click upload again.

## Screenshot

![image](https://user-images.githubusercontent.com/832723/45418302-733b3b00-b684-11e8-88b2-e0d47b868b19.png)

**Comment by n8fr8** [comment]
This should no longer be an issue with the latest 2.0 beta releases.
