### ISSUE TITLE
Clean install is not prompting user to install Orbot or give information about that feature

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#91]
OA version 0.0.18

Phone
Moto G first generation running Android 5.1.1

**Comment by foundscapes** [comment]
Once Orbot is downloaded, there is still no prompt to enable onionrouting in the app. However, Orbot does start automatically and is running. It should only start if OnionRouting is enabled.

**Comment by n8fr8** [comment]
Pref is enabled and working. We no longer show an active prompt to install Orbot, but the pref now reads "If Orbot is installed, use the Tor network"
