### ISSUE TITLE
Need issue Template 

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#92]
Create template for QA testers: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by roseregina** [comment]
I think I can help with/ do this since it is also something I need to speed up/ write better issues already

**Comment by elric-wamugu** [comment]
@foundscapes Two new issue templates are now live when [creating a new issue](https://github.com/OpenArchive/Save-app-android/issues/new/choose)
