### ISSUE TITLE
Browse/Create Projects

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/Save-app-android#96]
Details and flow for Browse Projects view are found here.
https://github.com/OpenArchive/openarchive-ios/issues/8
Android UI for browse
![android-browse-projects](https://user-images.githubusercontent.com/36669955/50847492-59aab700-1337-11e9-9f05-59743228e1be.png)
Android UI for Creating New Project
![android-new-project](https://user-images.githubusercontent.com/36669955/50848057-ce322580-1338-11e9-9804-90e710bcde11.png)

**Comment by n8fr8** [comment]
Create is implemented.

Next up is Browse.
